### ISSUE TITLE
Save data checkpoints for input data processing

### ISSUE THREAD

**Issue by Timoeller** [deepset-ai/FARM#101]
**Is your feature request related to a problem or particular use case?**
Creating training data takes a long time and also consumes a lot of memory, especially for Language Model adaptation.

**Describe the solution you'd like**
Since FARM processes data chunkwise transformed chunks can be saved to disk.
Ideally these chunks are also removed from memory to save RAM space.

**Comment by tanaysoni** [comment]
This is implemented by #177.
