### ISSUE TITLE
Get probability distribution over all classes in Inference mode

### ISSUE THREAD

**Issue by Alex-Zien** [deepset-ai/FARM#102]
When we use the inferencer to get predictions it might be useful to return probability values for all labels, not just the maximum. My use case would be for NER, but I see it being useful for other classification tasks as well.

**Comment by Timoeller** [comment]
Hey @Alex-Zien Thanks for creating this issue.
We realized it is a very important feature and super easy to implement, so we pushed it into master. Have a look at #103 
Please update your FARM. You can now return class probs with setting the return_class_probs parameter to True in the Inferencer.
Hope that helps.
