### ISSUE TITLE
excessive uncalled-for warnings when using the inferencer

### ISSUE THREAD

**Issue by Alex-Zien** [deepset-ai/FARM#104]
While evaluating a trained model on some held-out data, we get literally hundreds or thousands of warnings of this type:

      "09/26/2019 17:33:12 - WARNING - farm.data_handler.input_features -   [Task: text_classification] Could not convert labels to ids via label_list!\n",
      "If your are running in *inference* mode: Don't worry!\n",
      "If you are running in *training* mode: Verify you are supplying a proper label list to your processor.\n",

I am running in inference mode, so I am not worried, but I am troubled by the vast number of warnings that make it hard to find the important information in all of that output.

Expected behavior: As FARM knows that is runs in inference mode, it should not print this warning. And otherwise it should print it only once.

**Comment by Timoeller** [comment]
Totally agreed! 
I already had a short go at reducing this warning message but realized it needs some more complex changes. We will find a solution for that and keep you updated.
Hope this doesn't block you? I guess the relevant info will also be saved in the results coming back from the inferencer : )

**Comment by brandenchan** [comment]
This should help! #105
