### ISSUE TITLE
Loading Inferencer from Directory

### ISSUE THREAD

**Issue by FlorianRauls** [deepset-ai/FARM#143]
Is there a way to load the Inferencer from a directory containing a saved Adaptive Model and Processor? When browsing the examples inside your documentation I can find some options for it but when testing it out (and looking a the source code) it seems impossible since the Inferencer class does require a not-None model object when initializing.

**Comment by tholor** [comment]
Yes, absolutely! Just use `Inferencer.load()`. 

See also the example scripts:

https://github.com/deepset-ai/FARM/blob/fb6370ad5d99efa0b9126d72ce87c872234fff45/examples/doc_classification.py#L94-L106

**Comment by FlorianRauls** [comment]
Thank you very much!
