### ISSUE TITLE
Running FARM with FLAIR and BioFLAIR

### ISSUE THREAD

**Issue by Alex-Zien** [deepset-ai/FARM#145]
How can I run FARM with FLAIR and BioFLAIR?

"Performance on bioNER benchmarks continues to improve due to advances like BERT, GPT, and XLNet. FLAIR (1) is an alternative embedding model which is less computationally intensive than the others mentioned." [from the BioFLAIR publication]

https://www.aclweb.org/anthology/N19-4010/
https://github.com/shreyashub/BioFLAIR

**Comment by tholor** [comment]
Hi @Alex-Zien, 

you could implement it as a child class of a FARM language model (https://github.com/deepset-ai/FARM/blob/master/farm/modeling/language_model.py#L36) 

The class offers quite some flexibility. You would only need to implement:
- init()
- load() / save()
- forward() 

The forward() is probably the biggest part of work where you would need to pass a batch of data to the model and return the FLAIR embeddings. 

Most of the rest should then be handled automatically by the AdaptiveModel (e.g. passing the flair embeddings to the prediction head).

We did some similar experiment with fasttext in the past. We would love to see a PR and are happy to support you along the way ...

**Comment by tholor** [comment]
Closing this for now. Let us know if you want to investigate it further with a PR
