### ISSUE TITLE
Make it easier to use own metrics, log more metrics

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#152]
Currently the metric (for TextClassificationProcessor) needs to get specified as a string and picked from one of the pre-defined ones. That metric will then also get logged during training.

It would be very useful if it was possible to specify my own metric definition instead by allowing a function to get passed which takes preds/labels and returns the name and value of the metric. 

Also it would be very useful to specify a list of metrics so that several metrics can be logged (e.g. log the per-label f1 for classification)

**Comment by tholor** [comment]
Hi @johann-petrak, 

Valid point. Having an option to provide a custom function would give some more flexibility to the user. If you find some time to work on this, we would be happy to see a PR here and could support you on the way there.

**Comment by tholor** [comment]
Thanks to the work of @johann-petrak in #165 , we have now a workflow for supporting custom metrics. 

1) Define your own function that takes "preds" and "labels" as input and returns a dictionary of one or multiple metrics
2) Register the function with a name via register_metric() 
3) Pass the name to the processor

Example: 
https://github.com/deepset-ai/FARM/blob/3b0c5215442c3afbd76bbd7879a323c426be3274/examples/doc_classification_with_earlystopping.py#L53-L70

**Comment by rollator3000** [comment]
Thanks for the great work @johann-petrak, it works fine in my case! I only had to adjust two things:

*(1)* Spelling-Error:
` f1micro = f1_score(y_true=labels, y_pred=preds, average="macro")`
should actually be 
` f1micro = f1_score(y_true=labels, y_pred=preds, average="micro")`

*(2)* register_metrics _(in farm 0.8.0)_ is imported via:
`from farm.evaluation.metrics import simple_accuracy, register_metrics`

**Comment by johann-petrak** [comment]
@rollator3000 if you look at the example files, the code there should be correct, e.g. https://github.com/deepset-ai/FARM/blob/56ed798d0f4b9fc6baa49b388e4ad49d3cd8f949/examples/doc_classification_with_earlystopping.py#L61 or https://github.com/deepset-ai/FARM/blob/56ed798d0f4b9fc6baa49b388e4ad49d3cd8f949/examples/doc_classification_crossvalidation.py#L77 and also the imports in those files. 

Is your comment just about the code snippet in this issue or about code somewhere in the library or examples as well?
