### ISSUE TITLE
How to use bert-base-german-cased model to do NER?

### ISSUE THREAD

**Issue by greg121** [deepset-ai/FARM#153]
**Question**
https://demos.deepset.ai/ner
is there a source code to this specific problem? how I can achieve this and use the german bert model to recognize entities. very impressed with the performance on my examples.

**Comment by tholor** [comment]
Hi @greg121, 

Yes absolutely, I would suggest you to have a look into this example script where you can see the "Building blocks": 
https://github.com/deepset-ai/FARM/blob/master/examples/ner.py

Running this scripts trains a german bert model for NER on CONLL 2003 data. 

The one for the demo was trained with slightly different parameters - you can find the exact values here: https://github.com/deepset-ai/FARM/blob/master/experiments/ner/conll2003_de_config.json

You can either adjust the params in the script above or use the "experiment mode" in FARM to replicate this experiment:
```
from farm.experiment import run_experiment, load_experiments

experiments = load_experiments("experiments/ner/conll2003_de_config.json")
for experiment in experiments:
    run_experiment(experiment)
```

We haven't optimized for parameters yet, so you might gain some additional performance by experimenting yourself.

**Comment by greg121** [comment]
Thank you for your quick comment. Since I'm not a NLP Person and also only did a few simple mashine learning tasks before.

My understanding was I download your pretrained german model, use it on my data since I was already very happy with the results as stated in my initial post. From what I understand now FARM is used to transfer the model to my specific domain texts. Please correct me if I'm wrong.

I'm currently running https://github.com/deepset-ai/FARM/blob/master/examples/ner.py on a Google's Colab and it takes around 9h to save the model to "harvest my delicious fruits" :-)
