### ISSUE TITLE
Class weights calculated from all datasets.

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#166]
I stumbled over this by chance:
it appears that the DataSilo method calculate_class_weights uses all data sets to calculate the weights. This violates the principle that no information about the unseen data should be used for training, and that includes class probabilities. 

For training, only the training set class frequencies should be used.

So my suggestion would be to use the training set only for this by default, and maybe allow using all sets only if a keyword parameter is set explicitly?

**Comment by brandenchan** [comment]
Thanks for picking up on this. Totally agree that dev and test should remain unseen by default. This has been fixed in the latest commit (21a439d2fcdd9695398abf51e6b16a0e7999c46f)
