### ISSUE TITLE
DistilBERT Support

### ISSUE THREAD

**Issue by maknotavailable** [deepset-ai/FARM#185]
**Question**
Are you currently working on adding support for DistilBERT?

**Additional context**
I am specifically interested in the publicly available DE version of the model (distilbert-base-german-cased). If not, I will work on the integration.

**Comment by tholor** [comment]
Hey @maknotavailable, 

it's in our backlog, but we haven't started working on it yet. So it would be awesome if you could work on the integration. It should be relatively comparable to adding any of the other models.

You would basically need to: 
1. Add a DistilBERT Language model [here](https://github.com/deepset-ai/FARM/blob/master/farm/modeling/language_model.py#L236)
2. Add a DistilBERT Tokenizer [here](https://github.com/deepset-ai/FARM/blob/master/farm/modeling/tokenization.py#L52)

I am happy to support you in case of any questions coming up.

**Comment by maknotavailable** [comment]
See #187.
