### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by Seb0** [deepset-ai/FARM#19]
I advocate for adding a CHANGELOG.md or CHANGES.md document as a toplevel resource in the repo to be able to follow changes / fixes / new commits. Having to look at the commits is a lot of work for users of your framework, especially when you have rapid iteration and are getting a lot of stuff done.

If you don't want to write down changes by hand, you could generate them from squashed commits. Using something like the angular commit message format (https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit) helps immensely.

**Comment by Timoeller** [comment]
We really like this idea and already discussed it over lunch. 
We will try to find a good balance between nuisance of very structured commit msgs and useful information being in the changelog. We might also use structured commit msgs to generate better release notes.
Thanks for the hint @Seb0 , we will ping you once it is in place.

**Comment by tanaysoni** [comment]
Hi @Seb0. Thank you for raising the issue. We evaluated a couple of approaches for automating generation of release notes/changelogs and decided for https://github.com/github-tools/github-release-notes.

We'll have it setup before the next release!
