### ISSUE TITLE
Own model visible in Docker API but not in UI

### ISSUE THREAD

**Issue by agoeroeg** [deepset-ai/FARM#207]
**Question**
I have a text_classification model saved under saved models and visible in the docker api (localhost:5000), but not visible in the UI/document_classification (http://localhost:3000/doc_class). Could somebody help me and explain why? Thanks!

**Additional context**
curl -X GET "http://localhost:5000/models" -H "accept: application/json" finds my text_classification model with id: 1

**Comment by tholor** [comment]
In order to replicate this: 
- What exact FARM version are you using (e.g. PyPI release or current master)?
- What versions of the docker images are you using?
Thanks :)

**Comment by agoeroeg** [comment]
FARM current master
farm_inference-ui_1 deepset/farm-inference-ui:0.3
farm_inference-api_1 deepset/farm-inference-api:base-models-0.3.1

Windows 10 Pro,  Docker version 19.03.5, build 633a0ea,

**Comment by tanaysoni** [comment]
Hi @agoeroeg. The UI Docker Image was pointing to an incorrect URL for the inference API. It has now been fixed. Could you try running again after deleting the local copy of `deepset/farm-inference-ui:0.3`Docker Image and pulling the updated version?

**Comment by agoeroeg** [comment]
It works, thanks!
