### ISSUE TITLE
Better support for classification cross-validation

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#219]
There are at least two things that should get improved in the example program for doing cross-validation (`examples/doc_classification_crossvalidation.py`)

1) free GPU memory after each fold

I have noticed that GPU memory tends to accumulate with the current code and it helps to run `model.cpu()` followed by `torch.cuda.empty_cache()` (of course only if the model is really on the GPU). I do not understand this fully, because the model variable gets re-used and I thought that should the data on the GPU reusable as well. 

2) !! calculate the class weights from the fold data, not the overall data

This is actually a bug since calculating the class weights from the full data provides information that may slightly improve the estimate. The best solution here would be to add a method calculate_class_weights(task, source) to the DataSiloForCrossVal class.

**Comment by tholor** [comment]
Good points, @johann-petrak!

1. Maybe we face one of the two cases mentioned here :thinking: https://pytorch.org/docs/stable/notes/faq.html#my-model-reports-cuda-runtime-error-2-out-of-memory?

2. Absolutely! Would you be willing to implement this?

**Comment by johann-petrak** [comment]
I will have a look at implementing the class weights calculation for xval fold silos. 

Regarding the memory issues, I am not sure. If we are holding on to some variable somewhere, then what helps in my case should not make a difference. Will have to investigate further.

**Comment by johann-petrak** [comment]
Thanks for the reminder, bot :) 
Still on my TODO list.

**Comment by Timoeller** [comment]
Closing this for now. 
- The cleaning of model from cache has been added to both QA and doc classification crossval examples
- Please feel free to add a PR concerning a correct class weights computation
