### ISSUE TITLE
Model not found at inference time

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#232]
Hey, I get this error after training for regressor:

```Traceback (most recent call last):
  File "/XXX/bert.py", line 32, in <module>
    train_big_five_model()
  File "/XXX/bert.py", line 25, in train_big_five_model
    model = Inferencer.load(save_dir, task_type="regression")
  File "/XXX/FARM/farm/infer.py", line 147, in load
    model = AdaptiveModel.convert_from_transformers(model_name_or_path, device, task_type)
  File "/XXX/FARM/farm/modeling/adaptive_model.py", line 417, in convert_from_transformers
    lm = LanguageModel.load(model_name_or_path)
  File "/XXX/FARM/farm/modeling/language_model.py", line 131, in load
    f"Model not found for {pretrained_model_name_or_path}. Either supply the local path for a saved model "
Exception: Model not found for models/language_model. Either supply the local path for a saved model or one of bert/roberta/xlnet/albert/distilbert models that can be downloaded from remote. Here's the list of available models: https://farm.deepset.ai/api/modeling.html#farm.modeling.language_model.LanguageModel.load
```

The code is very similar to the doc_regression.py found in the farm/examples.

Here is how i save my model after training:
`save_dir = Path("models") where models is a directory in my project.` 
and here is the rest of the code:
```model = Inferencer.load(save_dir, task_type="regression")
    result = model.inference_from_dicts(dicts=basic_texts) ```

Please, could you tell me how to specify the path ?

**Comment by brandenchan** [comment]
So do you see the saved model in save_dir that you specified? This folder should contain files like language_model.bin and language_model_config.json. You should be pointing the Inferencer to this folder.

`model = Inferencer.load(Path("path/to/saved/model"))`

**Comment by zolekode** [comment]
Yes, actually when i look into the folder, `!ls models` i get:
```language_model.bin	       processor_config.json
language_model_config.json     special_tokens_map.json
prediction_head_0.bin	       tokenizer_config.json
prediction_head_0_config.json  vocab.txt```

**Comment by zolekode** [comment]
Ok, it seems, the problem is else where. because the model is now loaded successfully. So my paths must have been messed up.
But the program still crashes on this line:

`result = model.inference_from_dicts(dicts=basic_texts)` 

Unfortunately, since i am on sage maker, the notebook just freezes so i get no error message

**Comment by zolekode** [comment]
I tried the model.inference_from_file(file_path) to see if it works then but here is the error i get:
`KeyError: '[None] not in index'`. Is there any special format for files at inference time? I didn't understand the comments in the source code.

**Comment by zolekode** [comment]
I ran the model on my PC and everything works fine there. So this is probably a SageMaker issue.
