### ISSUE TITLE
Input is not valid. Should be String

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#233]
I want to build a model for text classification following the tutorial found under FARM/tutorial/1_farm_building_blocks but I came across this error:

```ValueError: Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.``` 

I am not quite sure if it is FARM related or if i just messed up my csv export somehow. Here is a sample of my dataset (in particular, the first four lines of the train.csv file)

``` "text","Label"
"The Portuguese started to develop townships, trading posts, logging camps and small processing factories.","0.0"
"Gradually, this inland sea became a massive swampy, freshwater lake and the marine inhabitants adapted to life in freshwater.","0.0"
"Wendish","1.0", 
"1.0","1.0" ``` 

Here is the snippet used to create the preprocessor:

``` label_list = ["1.0", "0.0"]
    metric = "f1_macro"

    processor = TextClassificationProcessor(tokenizer=tokenizer,
                                            max_seq_len=256,
                                            data_dir=Path("testing_distil"),
                                            label_list=label_list,
                                            metric=metric,
                                            label_column_name="Label",
                                            train_filename="train.csv",
                                            test_filename="test.csv",
                                            delimiter=",",
                                            quote_char='"',
                                            )```

**Comment by zolekode** [comment]
I have to note that the csv works fine with standard editors like numbers, excel and apis like pandas or vaex. That's why i don't know if the error is directly related to farm

**Comment by Timoeller** [comment]
Hey @zolekode to me it seems your CSV file doesn't have a correct header indicating the names for labels and text columns. Maybe try adding those.

**Comment by zolekode** [comment]
Hi @Timoeller, the label column name is "Label" as provided to the TextClassificationProcessor and the text column is "text".

**Comment by zolekode** [comment]
```test["text"] = test["text"].str.encode('utf-8')```  😄 👍 
Just solved it. There may have been some issues with encoding, although the file was already exported with utf-8 encoding before, the text column was cast to str and all "nan"-s were dropped.
Maybe in the future you could add something like "preferred" encoding to the interface and then maybe use that line to cast the text column ?
Tx :)
