### ISSUE TITLE
FARM in Sage Maker

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#234]
Possibly Provide a tutorial to install, configure and run Farm on SageMaker.

**Comment by Timoeller** [comment]
Thanks for the feedback. @tanaysoni is currently working on this, we will let you know once it is pushed.

**Comment by tanaysoni** [comment]
Hi @zolekode, we now have a [tutorial](https://github.com/deepset-ai/FARM/blob/master/tutorials/sagemaker/3_train_with_sagemaker.ipynb) for getting started with down-stream task training using the SageMaker Python SDK. The tutorial is an early version, so any feedback would help improve it!

**Comment by Timoeller** [comment]
Oh, that was quick :) 
And yes, any feedback would be highly appreciated. We can also set up a short call if you run into deeper problems. Just let us know.

**Comment by zolekode** [comment]
Ok thanks. That was really quick :D :D
