### ISSUE TITLE
Certain strings are not recognised as strings

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#243]
I had this problem before during training and encoded the strings. But now at inference time, this problem is back. The string variable is passed to the inference head.

```Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers```
Clear Text: 
 	text: ©
Tokenized: 
 	tokens: []
 	offsets: []
 	start_of_word: []
Features: 
 	None

**Comment by zolekode** [comment]
Problem seems to come from transformers

**Comment by Timoeller** [comment]
Hey @zolekode 
Looks like your text just consists of a single "©" symbol, which might not get converted at all.
Could you try converting a string like "This is a © test"?

And yes, you are right, the error message comes from transformers in tokenization_utils.py
I suspect though this special symbol gets removed somewhere on the way, resulting in an empty string.

**Comment by zolekode** [comment]
Hey @Timoeller thanks for the tip. I have added a little filter before to check if there are at least 3 alpha chars in the string before making predictions. Now it runs fine.

**Comment by Timoeller** [comment]
Nice @zolekode  
Do you think you could add a check and better error message like this to FARM and raise a PR?
That would make the framework much better, since there is a lot of people struggling with data processing and not really informative error messages...

**Comment by zolekode** [comment]
Yes sure thing. :)
