### ISSUE TITLE
Example for extracting embeddings from text does not work out-of-the-box

### ISSUE THREAD

**Issue by polars05** [deepset-ai/FARM#25]
I am trying to run <examples/embeddings_extraction.py> as it is but the following line throws an error "TypeError: expected str, bytes or os.PathLike object, not AdaptiveModel":

https://github.com/deepset-ai/FARM/blob/b5a4f412ab718c7ea317f1d281ec5b77abe0cdbf/examples/embeddings_extraction.py#L46

I would just like to ask: what is the issue here? Thanks!

**Comment by Timoeller** [comment]
Could it be that you installed FARM through `pip install farm` and are running embeddings_extraction.py via command line? 
We made some changes to the Inferencer yesterday, so please reinstall the latest changes by deinstalling through `pip uninstall farm` and then install FARM again through git as explained here: https://github.com/deepset-ai/FARM#installation

Thanks for the hint btw, we also updated the readme to make people aware of issues like these.

**Comment by polars05** [comment]
Thx for the info, @Timoeller! Do you guys intend to make update FARM's pypi package soon?

**Comment by Timoeller** [comment]
Yes we will, but not as often as we push changes to github (happens on a daily basis) and we want to have well documented releases (which would be too much overhead for each commit).

So I understand installing from github resolved the issue?

**Comment by polars05** [comment]
Yes, this issue is resolved; thanks for your help! Have closed the issue :)
