### ISSUE TITLE
GermEval 2014 experiment configuration

### ISSUE THREAD

**Issue by stefan-it** [deepset-ai/FARM#251]
Hi,

I just wanted to play around with the GermEval 2014 experiment. Here are two issues that I found with the current configuration - I'm using latest master branch for experiments:

## JSON configuration

After loading the JSON configuration, the following message is shown:

```bash
 ERROR - farm.file_utils -   Config is too deeply nested, at {'value': None, 'default': {'name': 'LinearWarmup', 'warmup_proportion': 0.4}, 'desc': 'opts for lr schedule'}
```

## Development data is missing

I think the development data is currently not located in the downloaded archive:

```bash
FileNotFoundError: [Errno 2] No such file or directory: 'data/germeval14/dev.txt'
```
I quickly checked the archive specified in the [dataloader](https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/utils.py#L20) and `dev.txt` is missing, training and test files are ok.

Thanks,

Stefan

**Comment by Timoeller** [comment]
Hey @stefan-it, fixed and tested it in #252 . Thanks for reporting.
