### ISSUE TITLE
Add Multiprocessing for Datahandling

### ISSUE THREAD

**Issue by busyxin** [deepset-ai/FARM#26]
This could save us a lot of time when processing large datasets.

**Comment by Timoeller** [comment]
I will take care of this the coming days. We need it for SQuAD processing and for large LM finetuning datasets, too.

**Comment by Timoeller** [comment]
We currently have a PR for this: #45 it is still WIP and will be hopefully resolved this week.

**Comment by tholor** [comment]
Done in #45
