### ISSUE TITLE
farm.modeling.language_model.load does not make use of 'language' **kargs if present

### ISSUE THREAD

**Issue by ftesser** [deepset-ai/FARM#261]
**Describe the bug**
As suggested from the WARNING below if the  'language' **kargs is present in `farm.modeling.language_model.load` method that should be used to setup the language. This is not realized now.

The referred method is:
https://github.com/deepset-ai/FARM/blob/d200a73aa77929fcd3365da81b510a490bfe2a18/farm/modeling/language_model.py#L70

**Error message**
I obtained the following after executing the code  listed in the **To Reproduce** section below:
```
02/21/2020 15:05:25 - INFO - transformers.file_utils -   PyTorch version 1.4.0 available.
02/21/2020 15:05:33 - INFO - transformers.modeling_utils -   loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/bert-base-italian-cased/pytorch_model.bin from cache at /home/fabio/.cache/torch/transformers/0dfce644f7b32078740bac235987e578d0d382d92aca41523ac6ca8b7cbedffd.80750f31a4b5680a47b8eca76074e68d18a2b39563db9d3648e9c30433e3fdef
02/21/2020 15:05:35 - WARNING - farm.modeling.language_model -   Could not automatically detect from language model name what language it is. 
	 We guess it's an *ENGLISH* model ... 
	 If not: Init the language model by supplying the 'language' param.
```
**Expected behavior**
Set `language` as the kargs passed.
 
**Additional context**
Add any other context about the problem here, like type of downstream task, part of  etc.. 

**To Reproduce**
```python
from farm.modeling.language_model import LanguageModel

language_model = LanguageModel.load('dbmdz/bert-base-italian-cased', language='italian')
```
**System:**
 - OS: Ubuntu 19.10 
 - GPU/CPU: both
 - FARM version: 0.4.1

**Comment by tholor** [comment]
You are totally right, @ftesser. The warning message had a good intention, but totally missed the implementation behind it. Thanks for spotting & fixing!
