### ISSUE TITLE
Add the option to define the language model class manually

### ISSUE THREAD

**Issue by ftesser** [deepset-ai/FARM#263]
**Is your feature request related to a problem or particular use case?**
In `farm.modeling.language_model.load` language model class is inferred from model filename.
Sometimes should be necessary to explicit force a particular LM class.

**Describe the solution you'd like**
Add a default parameter `language_model_class=None` like as is  already done in the Tokenizer class.

**Comment by tholor** [comment]
Thanks for reporting & directly raising a PR! Really appreciated :+1: 
I just merged it.

**Comment by ftesser** [comment]
Thanks for your work, and for the fast approval!
