### ISSUE TITLE
Missing `next_sentence_head` in examples/lm_finetuning.py

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#272]
The `examples/lm_finetuning.py` is creating but not using the `next_sentence_head`.
See here: https://github.com/deepset-ai/FARM/blob/master/examples/lm_finetuning.py#L55

I think it should say `prediction_heads=[lm_prediction_head, next_sentence_head],` instead of `        prediction_heads=[lm_prediction_head],`.

Also see here in `examples/train_from_scratch.py`: https://github.com/deepset-ai/FARM/blob/master/examples/train_from_scratch.py#L73

**Comment by tholor** [comment]
Yes, you are totally right! Thanks for reporting. 
Do you want to create a PR or shall I take care of it?

**Comment by PhilipMay** [comment]
I can do (try) that tonight. :-)

**Comment by PhilipMay** [comment]
Well - the fix was not that hard. :-) See PR #273

**Comment by tholor** [comment]
We really appreciate any support from the community. Even if it's such small fixes :)
Thank you, @PhilipMay !
