### ISSUE TITLE
Utilize all max_seq_len tokens in Language Model adaptation or training from scratch

### ISSUE THREAD

**Issue by Timoeller** [deepset-ai/FARM#280]
While training from scratch or adjusting Language Models to other domains (LM adaptation/ LM finetuning), FARM does not always use max sequence length number of tokens.
FARM only fetches two sentences, not accounting for their length. If these two sentences are shorter than max seq len tokens computation is wasted by zero padding.

**Describe the solution you'd like**
We need to avoid zero padding by filling up the whole sequence with text. So there is a need to fetch more than just two lines/sentences.

**Additional context**
Already implemented in Hugginface, see [TextDataset](https://github.com/huggingface/transformers/blob/879e1d32346cc4d24fb54bb336dcd5db4cd7005d/examples/run_language_modeling.py#L86) vs LineByLineDataset (just below).

**Comment by Timoeller** [comment]
[Here](https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/utils.py#L400) is the code where Farm fetches only two sentences and not two sequences that fill up all of max_seq_len.

**Comment by Timoeller** [comment]
I know @PhilipMay and @tripl3a were particularly interested in this feature.

**Comment by PhilipMay** [comment]
> I know @PhilipMay and @tripl3a were particularly interested in this feature.

Yes - thanks for this implementation!

**Comment by PhilipMay** [comment]
One interesting question for me is: Do you see any more substantial differences between Hugging Faces and FARM? For me this was one very important difference (that is "fixed"now).

**Comment by Timoeller** [comment]
Honestly Huggingface doesn't do next sentence prediction NSP any longer in their [script](https://github.com/huggingface/transformers/blob/master/examples/run_language_modeling.py).

The changes add NSP similar to the style of the original Bert repository.
Additionally whole word masking is included by default.
