### ISSUE TITLE
FARMReader is not applying max sequence length 

### ISSUE THREAD

**Issue by RobKnop** [deepset-ai/FARM#289]
**Describe the bug**

I get this:
```
03/22/2020 20:49:40 - INFO - farm.data_handler.data_silo -   Max sequence length:     256
03/22/2020 20:49:40 - INFO - farm.data_handler.data_silo -   Average sequence length after clipping: 254.1953488372093
03/22/2020 20:49:40 - INFO - farm.data_handler.data_silo -   Proportion clipped:      0.9662790697674418
03/22/2020 20:49:40 - INFO - farm.data_handler.data_silo -   [Farmer's Tip] 96.6% of your samples got cut down to 256 tokens. Consider increasing max_seq_len. This will lead to higher memory consumption but is likely to improve your model performance
```
My code:
```
### TRAINING #############
# Let's take a reader as a base model
reader = FARMReader(model_name_or_path="distilbert-base-uncased-distilled-squad", max_seq_len=512, use_gpu=False)
```

**Error message**

I used a different max_seq_len. But I still get the output 
```
import logging
logging.getLogger('farm').setLevel(logging.INFO)
```

**Expected behavior**
I would expect the right seq_len in the logger info output

**Additional context**
I use Haystack atm

**To Reproduce**

1. Set logging to info
2. Use the haystack tutorial and create FarmReader

**System:**
 - OS: MacOS Mojave 10.14.6
 - GPU/CPU: CPU
 - FARM version: 0.4.1
 - Haystack: current master, cloned 6pm on 22nd of March

**Comment by brandenchan** [comment]
Hi Rob, thanks for a detailed issue report. I got to the bottom of this on the Haystack side. The params that you set when initialising FARMReader now become the defaults when FARMReader.train() gets called. That was implemented in (https://github.com/deepset-ai/haystack/pull/47). This should fix the issue!
