### ISSUE TITLE
Own model visible in Docker API but not in UI

### ISSUE THREAD

**Issue by akupka** [deepset-ai/FARM#296]
**Describe the bug**
I have a NER classification model saved under saved models and visible in the docker api (localhost:5000), but not visible in the UI/document_classification (http://localhost:3000/ner). Could somebody help me and explain why? Thanks!

**Additional context**
curl -X GET "http://localhost:5000/models" -H "accept: application/json" finds my NER model with id: 1

Similar to Bug #207 
**System:**
 - OS: Ubuntun
 - GPU/CPU:GPU
 - FARM version:Master
- Docker: deepset/farm-inference-api:base-models-0.4.1
- Docker: deepset/farm-inference-ui:latest

**Comment by tanaysoni** [comment]
Hi @akupka, thank you for raising the issue! It is indeed related to #207. It should now have been fixed. Can you try again after deleting your local Docker Image `deepset/farm-inference-ui:latest` and pulling it again from the remote?
