### ISSUE TITLE
[data_handler/utils.py] read_docs_from_txt() is not robust to sentence made of Out-of-vocabulary characters

### ISSUE THREAD

**Issue by cregouby** [deepset-ai/FARM#298]
**Describe the bug**
When a text file with one sentence per line is read by `read_docs_from_txt()` with the sentence being made only on UTF-8 <spaces> characters, pipeline end-up silently with a tokeniser exception. Such sentences may occur when text comes out of an automatic extraction workflow.

**Error message**
```
      .--.        _____                       _
    .'_\/_'.     / ____|                     | |
    '. /\ .'    | (___   __ _ _ __ ___  _ __ | | ___
      "||"       \___ \ / _` | '_ ` _ \| '_ \| |/ _ \
       || /\     ____) | (_| | | | | | | |_) | |  __/
    /\ ||//\)   |_____/ \__,_|_| |_| |_| .__/|_|\___|
   (/\||/                             |_|
______\||/___________________________________________

ID: train-2283-0
Clear Text:
        doc_id: 02789c9e-a975-3e0a-be08-bd6d8fa1f864
        sent_id: 2
        text: ��������������������������������������������������������������������������������������������������������������������������������
Tokenized:
        tokens: []
        offsets: []
        start_of_word: []
Features:
        None
```

**Expected behavior**
You could maybe add an explicit error message, and a fallback to [UNK] token

**To Reproduce**
Create a syntetic dataset with sentences made of utf-8 space characters

**System:**
 - OS: Linux
 - GPU/CPU: GPU
 - FARM version: https://github.com/deepset-ai/FARM/commit/4ab81bdddae2b4e346e6f2dad220091a10034748

**Comment by brandenchan** [comment]
Hi, this pull request (#308) should fix the issue. Could you try it out and let us know if it solves it?
