### ISSUE TITLE
model.inference_from_dicts does not return an item if no named entity is found in text

### ISSUE THREAD

**Issue by renaud** [deepset-ai/FARM#326]
**Describe the bug**
When calling model.inference_from_dicts,  does not return an item if no named entity is found in text

**To Reproduce**
model = Inferencer.load(save_dir) # Connl EN NER
basic_texts = [
    {"text": "I love you."},
    {"text": "I love Anna."}, # only this sentence has a NE, Anna
    {"text": "I love you so much!"},
]
result = model.inference_from_dicts(dicts=basic_texts)

**actual output**
[{'task': 'ner', 'predictions': [{'start': 7, 'end': 12, 'context': 'Anna.', 'label': 'PER', 'probability': 0.9851147}]}]

**expected output**
[{'task': 'ner', 'predictions': [{}, {'start': 7, 'end': 12, 'context': 'Anna.', 'label': 'PER', 'probability': 0.9851147}, {}]}]
(note the two empty dicts for the sentences where no NE was found.

**Why it's important**
Otherwise it's tricky to map it back to the original text...

Thanks!

**Comment by brandenchan** [comment]
Hey, I totally agree that we need a better grouped output from the NER inferencer. I opened a pull request that now makes the Inferencer return one list per input_text that contains all the predictions for that input_text. The output looks like this:

[{'task': 'ner', 'predictions': [[], [{'start': 7, 'end': 11, 'context': 'Anna', 'label': 'PER', 'probability': 0.9971745}], []]}]

Can you give this a go and let me know if it's working for you?

**Comment by renaud** [comment]
Thanks @brandenchan , exactly!

(I guess you noticed, but your branch merge did not work. I was about to fix the text myself, but you beat me to it in #bc738b5 )

**Comment by brandenchan** [comment]
The tests have been fixed and the branch is now merged. You can now try out these changes in master!

**Comment by renaud** [comment]
thanks a lot @brandenchan !
