### ISSUE TITLE
QA: Returning answers that are longer than context

### ISSUE THREAD

**Issue by tholor** [deepset-ai/FARM#333]
**Describe the bug**
When the length of the answer is longer than `context_window_size` the `QuestionAnsweringHead` returns invalid, negative offsets. This is only relevant at inference time, but can cause problem then in upstream usage (e.g. in haystack).

**Expected behavior**
Context should always cover the full answer

**Details**
We should add a check in `create_context()` to increase the context for such cases
https://github.com/deepset-ai/FARM/blob/89826c1f4269a5c0d0b5a6193ece94a3401766d9/farm/modeling/prediction_head.py#L1262-L1282

**System:**
 - FARM version: 0.4.2

**Comment by Timoeller** [comment]
The context is around the midpoint of the answer. That is why for long answers the context can be negative. 
When we take context around start and end of answer we should be good (and have actual context around long answers).

**Comment by Timoeller** [comment]
@brandenchan can you please check if this issue persists with current code?
