### ISSUE TITLE
Match output types and prediction heads in AdaptiveModel

### ISSUE THREAD

**Issue by gsarti** [deepset-ai/FARM#336]
Dear maintainers,

When creating an `AdaptiveModel` instance, there are no checks to ensure that the number of specified `lm_output_types` matches the number of `prediction_head`. When they don't, zipping them together in the forward pass will only consider a portion of the heads, which is likely to cause unwanted behavior.

In my specific case, I wanted to do multi-tasking with multiple heads on the same task (`per_token`) but only the first was considered in the forward pass since I set the `lm_output_type` parameter to `per_token` instead of using a list of `per_token` matching the head list length.

A possible solution is to implement the following behavior:
- **1 head. 1 output type**: the head gets the output_type
- **multiple head, 1 output type**: The output type gets broadcasted to all heads, to avoid repetition.
- **1 head, multiple output types**: raise error of size mismatch (a head can have only one type)
- **multiple head, multiple output types**: If the length of head and output types list match, each head receives its type, else an error of size mismatch is raised (heads and output types sizes must match)

If you deem this issue noteworthy, I will create a dedicated PR in the next few days.

Best,

Gabriele Sarti

**Comment by tholor** [comment]
Totally agree. This is an annoying and hard-to-spot issue. 
We would highly appreciate a PR here. I also like the sketched solution. 
I would only suggest logging an info message for the `multiple head, 1 output type` case to make the user aware of this broadcast. Otherwise, it's still very easy to introduce a bug here when you do multitask learning with different types of heads.

**Comment by Timoeller** [comment]
Hey @gsarti do you need help on this? Creating a Work In Progress PR is also fine, so we can discuss the proposed changes better.

I guess a quick and safe implementation is to log warnings as Malte suggested - with hard assertions all types of tasks have to be tested for correctness.

**Comment by gsarti** [comment]
Hey @Timoeller , thanks for the ping! Sorry but I got quite busy lately with my thesis, so I'm using quick adaptations of your classes for the moment. When I'm done with my rush (probably around September), I will be more than happy to share my fixes so that you can include what you find useful inside FARM. Sadly, until then I won't have any time to work on issues and related stuff, sorry!

**Comment by Timoeller** [comment]
Alright, no problem, thanks for checking in.
Good luck with your thesis
