### ISSUE TITLE
Synergy Jina <> FARM

### ISSUE THREAD

**Issue by hanxiao** [deepset-ai/FARM#341]
**Is your feature request related to a problem or particular use case?**

Hi 👋 , I just leave a thread here to brainstorm potential synergy between Jina (https://github.com/jina-ai/jina/) and Farm

**Describe the solution you'd like**

**Additional context**

We had an internal discussion and listed this as potential task at here https://github.com/jina-ai/jina/issues/71

**Comment by tholor** [comment]
Hey @hanxiao, 

sure, happy to brainstorm. While I believe the synergies between Haystack and Jina might be more exciting to explore, I also see some potential between FARM & Jina. 

I think the most obvious use case would be adding a "FARM Encoder" in Jina similar to the [transformers](https://github.com/jina-ai/jina/blob/master/jina/executors/encoders/nlp/transformer.py#L13) one.

**Comment by hanxiao** [comment]
ok it's done https://github.com/jina-ai/jina/pull/383

**Comment by tholor** [comment]
Awesome :tada:

**Comment by hanxiao** [comment]
I will also write a blog post to talk about how to extend Jina and use FARM as an example. Currently our blog infra is not ready yet 😅

**Comment by hanxiao** [comment]
And we will cohost a webinar on July 23rd. Registration link: https://deepset.jina.ai
