### ISSUE TITLE
Fix activation function for pooled ELECTRA output

### ISSUE THREAD

**Issue by stefan-it** [deepset-ai/FARM#362]
Hi,

inspired by https://github.com/huggingface/transformers/pull/4257 I just had a look at the original ELECTRA implementation, and it seems that they're using `gelu` instead of `tanh` for getting a pooled output:

https://github.com/google-research/electra/blob/79111328070e491b287c307906701ebc61091eb2/model/modeling.py#L247

and:

https://github.com/google-research/electra/blob/79111328070e491b287c307906701ebc61091eb2/model/modeling.py#L45

Unfortunately, I used `tanh` in the ELECTRA model integration:

https://github.com/deepset-ai/FARM/blob/37591d198813c999afe3766be2fa281af26a25e5/farm/modeling/language_model.py#L1240

I will open a PR to fix that :)

**Comment by brandenchan** [comment]
Implemented in #364
