### ISSUE TITLE
Extremely Slow Response Time

### ISSUE THREAD

**Issue by adrianpaiva1** [deepset-ai/FARM#371]
**Question**

I'm running the docker image (deepset/farm-inference-api:base-models-0.4.2) locally with the provided api and my response times are super slow. 

With smaller text (around 500 characters) it's taking around 10 seconds through postman.

With Larger text it's taking at least 30 seconds.

Just wondering if this is to be expected or there is something I'm not doing correctly. I have a pretty beefy system (3770k with 16gb ram) but I'm using an AMD GPU so no CUDA if that has any effect.

I'm trying to extract answers from blocks of text.

Love the package BTW, any help is greatly appreciated.

**Additional context**
![Screenshot from 2020-05-21 18-28-09](https://user-images.githubusercontent.com/19557611/82612642-56614580-9b91-11ea-9082-d0f0502534cc.png)

**Comment by Timoeller** [comment]
Hey @adrianpaiva1 
Jugding from pytorch/pytorch/issues/10657 comment from yesterday, pytorch does not support AMD GPUs:  
> Pytorch on AMD graphic cards is long waited capability and highly appreciated. Wishing hardly to get this soon, thanks.

--------------------------------------------

**concerning your response times on CPU then:**
We have a detailed QA inference benchmark sheet [here](https://docs.google.com/spreadsheets/d/1ak9Cxj1zcNBDtjf7qn2j_ydKDDzpBgWiyJ7cO-7BPvA/edit#gid=0) also including CPU times.

In general the slow response time (although yours are particularly slow :) for large QA models is a blocker for creating useful applications. That is why we created [haystack](https://github.com/deepset-ai/haystack) to scale QA systems to large texts or many documents.

May I ask for what use case you are extracting the answers and how the text blocks look like. Might be that haystack is what you are looking for...

**Comment by Timoeller** [comment]
I am closing this now because of inactivity.
