### ISSUE TITLE
examples/ner.py  -- Inference problems 

### ISSUE THREAD

**Issue by deloitte-sp** [deepset-ai/FARM#376]
Hi there, 

thanks for your great farm package. I've used the package many times for classification and it worked like a charm. Now iam trying to do some NER. Basic setup like ur setup in the NER examples, with the similar data (https://github.com/MaviccPRP/ger_ner_evals/tree/master/corpora/conll2003):

- deuutf.testa --> dev.txt
- deuutf.train --> train.txt
-  deuutf.dev --> test.txt

Training works good., after 4 epochs dev results:

            precision    recall  f1-score   support

      ORG       0.82      0.75      0.79      1188
      PER       0.95      0.88      0.91      1401
     MISC       0.78      0.73      0.75      1010
      LOC       0.81      0.84      0.82      1181

micro avg       0.82      0.81      0.82      4780
macro avg       0.85      0.81      0.83      4780

test results:

            precision    recall  f1-score   support

      PER       1.00      1.00      1.00        19
      ORG       1.00      1.00      1.00         3
      LOC       1.00      1.00      1.00        15
     MISC       0.90      0.90      0.90        10

micro avg       0.98      0.98      0.98        47
macro avg       0.98      0.98      0.98        47

But i cant get any inference out of my saved model:

![image](https://user-images.githubusercontent.com/44645052/83130452-9ae36880-a0de-11ea-9b2c-5bd5ec8c666d.png)

Your demo model is 100% correct on this example:
![image](https://user-images.githubusercontent.com/44645052/83130510-b0589280-a0de-11ea-9f93-a099079b87a7.png)

Thank you for your patience.
All the best
Sebastian

**Comment by brandenchan** [comment]
Hi Sebastian, sorry the late response. We used to have a bug just like this in a slightly older version of FARM. Would you mind making sure that you're on the latest version and then seeing if this issue is still there?

**Comment by Timoeller** [comment]
Issue seems fixed. Closing now. Feel free to reopen if the problem persists
