### ISSUE TITLE
Document magic data loading in `TextClassificationProcessor`

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#378]
**A clear and concise description of what the problem or use case is**
In the examples `doc_classification.py` and `doc_classification_cola.py` the `TextClassificationProcessor` specifies a `data_dir`. For me it is (was) not clear if and how I have to provide the data. After just executing the code I saw that some magic did just load the data from an S3 storage. This magic maybe should be documented in `TextClassificationProcessor`.

**Describe the solution you'd like**
This magic should be documented in the docstring of `TextClassificationProcessor` and the examples. If you agree and want to I can provide a PR.

**Comment by Timoeller** [comment]
Agreed, magic it is : )

And also agreed, some documentation on how the data is loaded would be more user-friendly. Happy to merge a PR quickly on this topic.

**Comment by PhilipMay** [comment]
Updated documentation in PR #383. Closing this.
