### ISSUE TITLE
Add possibility to specify text col name in `TextClassificationProcessor`

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#379]
With `label_column_name` it is possible to set the col name of the labels in `TextClassificationProcessor`. IMO it should also be possible to specify the text col name. At the moment it seems to be fixed to `text`.

If you agree and want to I can provide a PR.

**Comment by Timoeller** [comment]
We would love a PR on this one! It is on our roadmap but we didn't find time for it yet.

**Comment by PhilipMay** [comment]
@Timoeller one question that came up while coding this PR:
Under which condition can `self.tasks.values()` contain more than one value? See here:
- https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/processor.py#L463
- https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/processor.py#L508
- and so on...

IMO the `add_task` function only adds exactly one task per `Processor` class.

**Comment by PhilipMay** [comment]
Implemented in #387. Closing this.
