### ISSUE TITLE
Support for Google TPUs

### ISSUE THREAD

**Issue by nemaniarjun** [deepset-ai/FARM#384]
**Question**
Hello all, I have been following this project for a while. 
I dont think the code supports using TPUs for running FARM.
What would be the easiest way to achieve that? 
I am currently thinking of using the `xla-spawn` script from transformers examples repository work with FARM? 

**Side Question**
How can we support multiple TPU training?

Thanks for the help!

**Comment by Timoeller** [comment]
You are correct. FARM currently doesn't support TPUs, though supporting them through xla would be great! 

Would you like to start working on this? Please feel free to add a PR and we support wherever possible.

**Comment by nemaniarjun** [comment]
@Timoeller since my understanding is limited, if you have any general ideas on how to get started would be awesome otherwise I'll dig deep and send in a PR soon!

**Comment by Timoeller** [comment]
Honestly we also do not have experience with pytorch xla, though the hint you gave to the [documentation of the xla spawn script](https://github.com/huggingface/transformers/blob/7b75aa9fa55bee577e2c7403301ed31103125a35/examples/README.md#running-on-tpus) seems like a good start.

1. It would be important to understand how the "--tpu_num_cores" parameter is used inside the transformers scripts. So how data and model are assigned to each TPU core. If this is very similar to how torch distributed DDP with the parameter "local_rank" works it should also be possible to integrate xla into FARM.
2. If xla works in a similar way as DDP + local_rank you could test out DDP on a [FARM example](https://github.com/deepset-ai/FARM/blob/master/examples/doc_classification.py) script and then migrate transformers xla_spawn script to FARM.
3. Another complexity will be setting up xla to work with your TPU environment. I believe this has to be done outside of FARM, but should be documented clearly.

**Comment by Timoeller** [comment]
Are there any updates?
I would close this issue for now and reopen it, when we make progress.
