### ISSUE TITLE
CI Pipeline seems to be broken

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#385]
For some reason the CI errors out. See here:

https://dev.azure.com/deepset/FARM/_build/results?buildId=285&view=logs&j=5f32d555-91de-5b47-aa96-4f80d9326a6b&t=813bfe30-cb15-55d3-e33c-c7c8b5f23c95&l=81

This is from the last commit: https://github.com/deepset-ai/FARM/commit/258a76fface7652248530bdd9c841d6022c89af5

In the PR (before merging) the CI was all green: https://github.com/deepset-ai/FARM/pull/382

What is the reason here?

**Comment by Timoeller** [comment]
So the error: `Bash exited with code '137'` has to do with memory issues. We recently changed from Travis CI to Azure pipelines because we thought this fixes OOM issues. @tanaysoni could you please have a look at it?

**Comment by PhilipMay** [comment]
We should reduce the memory usage of the `test_question_answering.py ` test. Maybe use a smaller model then `distilbert-base-uncased`?

**Comment by PhilipMay** [comment]
Fixed by: https://github.com/deepset-ai/FARM/commit/32fe61ba17870e0f43b42b3e3d179dfa8fb4d910

Closing this.

**Comment by PhilipMay** [comment]
Well, there still seems to be a problem which does not always happen but just from time to time. See here: https://dev.azure.com/deepset/FARM/_build/results?buildId=303&view=logs&j=5f32d555-91de-5b47-aa96-4f80d9326a6b&t=813bfe30-cb15-55d3-e33c-c7c8b5f23c95&l=87

This happened after I rebased master and got the Update to pytorch 1.5.0.
Could you please investigate this?

I will reopen this. Issue.

Thanks
Philip

**Comment by PhilipMay** [comment]
More strange things happening:
- `test_ner.py` crash: https://dev.azure.com/deepset/FARM/_build/results?buildId=311&view=logs&j=5f32d555-91de-5b47-aa96-4f80d9326a6b&t=813bfe30-cb15-55d3-e33c-c7c8b5f23c95&l=81
- complete f*up: https://github.com/deepset-ai/FARM/runs/728689459

**Comment by Timoeller** [comment]
:D jap, confirming there is no such thing as a free lunch and our azure CI pipeline is on a free plan for now...
I spoke to our engineer and the good news is the CI issues - especially the OOM issue - popped up a while ago and might not be related to our PRs. Fixing these issues properly will require some more time on our end.

**Comment by PhilipMay** [comment]
Do you see any possibility to add more debug code so we can see in detail what is happening? Do we have memory leaks somewhere? PyTorch, Huggingfaces, ...

Are we even sure if it is an OOM problem?

**Comment by PhilipMay** [comment]
Any news on this topic? Did you come to new insights? Is there anything I can help with?

**Comment by PhilipMay** [comment]
The `test_lm_finetuning.py` test(-s) seem to spawn many threads (see screenshot).

![Screenshot from 2020-06-06 18-29-56](https://user-images.githubusercontent.com/229382/83949403-de974a00-a823-11ea-8351-d1fd17615552.png)

Each thread seems to use 3 GB ram. Might that be part of the problem? Could it help to reduce the number of threads?

**Comment by PhilipMay** [comment]
I think it would reduce memory usage when `None` is removed from this line:
https://github.com/deepset-ai/FARM/blob/master/test/test_inference.py#L6

**Comment by PhilipMay** [comment]
I observed that when `test_inference.py` is executed it spawns several threads using about 3 GB memory. When executing all tests (with just `pytest`) the spawned threads are not stopped after `test_inference.py` has been executed. That is strange.

I think the `@pytest.mark.parametrize("num_processes", [2, 0, None], scope="session")` command in  somehow is persistent.

**Comment by PhilipMay** [comment]
> 
> 
> Warning
> 
> multiprocessing.pool objects have internal resources that need to be properly managed (like any other resource) by using the pool as a context manager or by calling close() and terminate() manually. Failure to do this can lead to the process hanging on finalization.
> 
> Note that is not correct to rely on the garbage colletor to destroy the pool as CPython does not assure that the finalizer of the pool will be called (see object.__del__() for more information).
> 

See here: https://docs.python.org/3.7/library/multiprocessing.html#module-multiprocessing.pool

**Comment by PhilipMay** [comment]
I home here is a fix for the unclosed worker pool: #403

This might also fix the CI problems.
