### ISSUE TITLE
Problems with `**kwargs` in `TextClassificationProcessor`

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#388]
The `TextClassificationProcessor` has an `**kwargs` param in its constructor. See here: https://github.com/deepset-ai/FARM/blob/258a76fface7652248530bdd9c841d6022c89af5/farm/data_handler/processor.py#L386

The `**kwargs` param is not used anywhere and should be removed. The reason is that can "eat" wrong parameter names without notice. Exactly this happens here:
https://github.com/deepset-ai/FARM/blob/master/test/test_processor_saving_loading.py#L18

Where `metrics` is wrong. It should be `metric` without `s`. Also `columns` is an unknown param and just "eaten" by `**kwargs`.

What do you think? As always I could provide a PR.

**Comment by Timoeller** [comment]
Agreed, it is nasty when this happens unexpectedly and we should avoid generic kwargs wherever possible.

I was going through the code to check if it is feasible and realized we get into trouble when generically loading. I might have a working solution in #390 but will test it more thoughoughly later on.

Thanks for raising this issue!
