### ISSUE TITLE
Get Failed to log params warning without using MLFlowLogger 

### ISSUE THREAD

**Issue by lingsond** [deepset-ai/FARM#401]
I'm testing the lm_finetuning script on Kubernetes. The docker image is based on Dockerfile-GPU.

The script has been modified a little where I remove the import MLFlowLogger and also the use of it in the lm_finetuning method (so I'm not using the MLFlowLogger at all). I still use the logging.basicConfig(..) though so I still can see the infos during runtime.

However, when I run the script, I see this showed up almost after every INFO:
WARNING - farm.utils -   Failed to log params: 'getpwuid(): uid not found: 1174'

I looked into farm.utils and the only part that will throw this message is inside the log_params method of MLFlowLogger.

I didn't use the MLFlowLogger at all, why do I get this warning? How to solve this problem?
Thanks in advance.

**Comment by lingsond** [comment]
Additional information:

I added some line to my Dockerfile:

```
## config
ARG USER=myusernamewashere
ARG UID=1174

RUN adduser ${USER} --uid ${UID} --home /home/${USER}/ --disabled-password --gecos "" --no-create-home
RUN mkdir -p /home/${USER}
RUN chown -R ${USER} /home/${USER}
```

So the warning has disappeared now. The reason the warning showed up was because my user information wasn't included in the Docker image.

However, it doesn't answer my original question:
I didn't use the MLFlowLogger at all, why do I get this warning?

Thanks in advance! :)

**Comment by tanaysoni** [comment]
Hi @lingsond, thank you for raising the issue. In the current version, an MLFlowLogger instance is instantiated by default. With work in progress #305, there's a new [StdoutLogger](https://github.com/deepset-ai/FARM/pull/305/files#diff-a33f2f632da3090ea746b7071b52a756) being added that'd allow logging params/metrics on the stdout.

**Comment by lingsond** [comment]
Thanks for the info!
