### ISSUE TITLE
Trainer fixes all seeds to 39

### ISSUE THREAD

**Issue by tstadel** [deepset-ai/FARM#423]
**Describe the bug**
In Trainer.train() seeds are hardcoded to 39 by calling set_all_seeds(seed=39) (two times).
Thus any calls to set_all_seeds in training scripts are ignored.

**Error message**
None

**Expected behavior**
Calling set_all_seeds from arbitrary training scripts works as intended and is not ignored. 

**To Reproduce**
start arbitrary training

**System:**
 - OS: all
 - GPU/CPU: all
 - FARM version: since 5151b36bbdc77c9a571a57e5c571b8c45f87acf5

**Comment by tholor** [comment]
Thanks for flagging this and proposing a PR. I added a comment in the PR.
