### ISSUE TITLE
Loading of saved model results in Unexpected key(s) in state_dict: "loss_fct.weight"

### ISSUE THREAD

**Issue by Timoeller** [deepset-ai/FARM#428]
**Describe the bug**
We cannot load a Prediction Head with class weights.

**Error message**
RuntimeError: Error(s) in loading state_dict for TextClassificationHead:
	Unexpected key(s) in state_dict: "loss_fct.weight". 

I suspect this bug was introduced by updating to pytorch version 1.5.0.
Unfortunately we do not have tests covering this use case, so we cannot pin the cause exactly.

**Comment by PhilipMay** [comment]
See #422 for a detailed exception.

**Comment by PhilipMay** [comment]
See RP #431 for fix.
