### ISSUE TITLE
`use_amp` param in `initialize_device_settings` not used.

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#433]
The `initialize_device_settings` function has a `use_amp` param that is only used for logging. This smells like a bug. See here:

https://github.com/deepset-ai/FARM/blob/451bc0bdd6146f5cbd8b2ca5047814874de717de/farm/utils.py#L66

**Comment by tholor** [comment]
I see why this might look unusual, but it's not a bug. The `use_amp` parameter is used for logging here as that's the earliest time where we have all "device settings" like GPU, distributed etc. together. AMP usage is an important piece of information at this point, too. 

The actual initialization of AMP however can only happen after model and optimizer init. 
Therefore, you will find a `use_amp` parameter in `initialize_optimizer()` and `Trainer()`.

**Comment by PhilipMay** [comment]
Passing a parameter only for logging without any functionality is very strange IMO. It should be logged where it is actually used. At the end of the day the user forgets to pass it here and everything is confusing, inconsistent and misleading.
