### ISSUE TITLE
Document TPU usage

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#434]
This is both -  a question and a feature request:

Can FARM be used with TPUs? I found nothing in the documentation or in the code. So I think this is not possible. Maybe this should be documented.

**Comment by tholor** [comment]
Hey @PhilipMay, 

TPUs are currently not supported, as PyTorch doesn't support it out of the box but rather requires the usage of PyTorch XLA https://github.com/pytorch/xla  

There was already a related discussion here: https://github.com/deepset-ai/FARM/issues/384
While it would, of course, be nice to support TPUs, there are quite many other topics where we see a higher priority. 
As always, happy to see a community contribution if this is an important feature for you guys.

**Comment by Timoeller** [comment]
Seems fixed. Closing this.
