### ISSUE TITLE
Setting `num_training_steps` in `schedule_opts` is not good in function `initialize_optimizer`

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#436]
This line:

https://github.com/deepset-ai/FARM/blob/a5bda34f0731a6f50c80309d86c79e4710dee052/farm/modeling/optimization.py#L144

is not nice when the API user sets an explicit `schedule_opts` dictionary. It overwrites values. IMO it should be deleted.
What do you think?

**Comment by tholor** [comment]
I wouldn't delete it, as this would be a breaking change requiring users to always compute the `num_training_steps` themselves (not difficult, but annoying). However, I agree that we should not overwrite in the case where a user supplies this already in `schedul_opts`. 
So how about adding a condition there that prevents overwriting?

**Comment by PhilipMay** [comment]
see PR #437
