### ISSUE TITLE
Findings: Loading and saving models

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#439]
I trained a `bert-base-german-cased` model on the GermEval17 dataset. After training I saved the model and the processor with:

```python
model.save(save_dir)
processor.save(save_dir)
```

This saving created the following files:
- language_model.bin
- language_model_config.json
- prediction_head_0.bin
- prediction_head_0_config.json
- processor_config.json
- special_tokens_map.json
- tokenizer_config.json
- vocab.txt

So far so good. Then I tried to load the model and processor again to evaluate them to simulate a prediction server. 

```python
model = AdaptiveModel.convert_from_transformers(save_dir, device=device, task_type="text_classification")
```

I made some "findings":

When loading the model it complained that `config.json` is missing. So I renamed `language_model_config.json`
to `config.json`. Then it complained that "`no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found`".
So I renamed `language_model.bin` to `pytorch_model.bin`. Then everything was ok...

This is very strange behavior. A consistent framework should be able to load the stuff it saved without manual intervention. What do you think about this? Should the file search be improved to be able to load the model without manual changes? What is the background of this behavior?

**Comment by tholor** [comment]
Hey @PhilipMay , 

Please try loading your saved model via `AdaptiveModel.load()`: 
https://github.com/deepset-ai/FARM/blob/daa629184a334cd5f9d118d267f08f9c3fa08d8b/farm/modeling/adaptive_model.py#L287

`AdaptiveModel.convert_from_transformers()` is meant to load a model that was stored via huggingface's transformers library (which uses a slightly different format).

Hope that helps.

**Comment by PhilipMay** [comment]
Great! Thanks @tholor

**Comment by julianhoegerl** [comment]
Which line of Code do you need to load the processor?
