### ISSUE TITLE
How do I do text classification with multiple heads?

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#441]
Hi,
I have a dataset with two columns of label.
- one column encodes the first class (always one of 4)
- one column encodes the 2nd class (always one of 5)

So I want to use 2 heads to predict the first and 2nd class.
How do I connect the data (TextClassificationProcessor) with the 2 heads?
I saw an example of multi label classification. But that does not exactly fit my need.
Is that even possible with the current implementation of FARM?

Thanks
Philip

**Comment by tholor** [comment]
Hi, 
While I personally haven't worked on this for a while, the basic functionality should be in place. 
Please have a look at the [release notes of v0.2.2](https://github.com/deepset-ai/FARM/releases/tag/0.2.2), where we included an example of how to add multiple tasks. Hope this helps!

**Comment by PhilipMay** [comment]
> Please have a look at the [release notes of v0.2.2](https://github.com/deepset-ai/FARM/releases/tag/0.2.2), where we included an example of how to add multiple tasks. Hope this helps!

Ahh ok. Thanks. I will check that because this PR from me might not be needed: #442

**Comment by Timoeller** [comment]
Closing this issue now as well.
