### ISSUE TITLE
regression processor label standardization inconsistencies

### ISSUE THREAD

**Issue by rohanag** [deepset-ai/FARM#452]
**Describe the bug**
Problem with label standardization in regression processor. Label mean and std deviation are being calculated for train set, then those values are being overwritten with the same calculation for dev and test set [link to code](https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/processor.py#L1578) 
After that, standardization is not actually performed on any data because of key mismatch [over here](https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/processor.py#L1616). Instead of checking for the "label" key, you must look for self.tasks["regression"]["label_name"]

**Error message**
Silent error.

**Expected behavior**
RegressionProcessor should store regression label mean and std dev values only for train set. And standardization must be performed on the actual labels.

**Additional context**

**To Reproduce**
add print statements to view the output of [this function](https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/processor.py#L1603) and you will see that standardization of regression label is not taking place.

**System:**
 - OS: Ubuntu 16.04.5 LTS
 - GPU/CPU: Both
 - FARM version: 0.4.5

**Comment by rohanag** [comment]
I'm also trying to push a fix but I get 
`fatal: unable to access 'https://github.com/deepset-ai/FARM.git/': The requested URL returned error: 403`
Just wondering if the problem is on my end, or if there is an actual permission issue.

**Comment by tholor** [comment]
@rohanag thanks for spotting this. We would highly appreciate a fix!
When do you get the above access error? Did you maybe try to push directly to the FARM repo? In order to create a PR you'll need to fork the repo, push your changes to a branch in your repo, and then create a pull request from there.

**Comment by rohanag** [comment]
Ah yes ofc, I forgot forking! sending one PR shortly
