### ISSUE TITLE
Extracting results from fine-tuned trained model

### ISSUE THREAD

**Issue by YojanaGadiya** [deepset-ai/FARM#465]
Dear all,
I wanted to know if there is any way to extract results/metrics from the trained fine-tuned model? This fine-tuning of the model is done using the train and the validation dataset and I need to record the metrics for each of the hyperparameter combinations and use it for optimization purposes.

Thank You.

**Comment by Timoeller** [comment]
Sure please have a look at our [evaluation example](https://github.com/deepset-ai/FARM/blob/master/examples/evaluation.py).
If you want to load a locally saved FARM model you can do so like shown in [this line](https://github.com/deepset-ai/FARM/blob/master/examples/evaluation.py#L116)
``

**Comment by YojanaGadiya** [comment]
Okay. Thank you!

**Comment by Timoeller** [comment]
Seems fixed. Closing now
