### ISSUE TITLE
Splitted files need perhaps to be deleted.

### ISSUE THREAD

**Issue by lingsond** [deepset-ai/FARM#467]
During my testing of using the split_file method (in farm.data_handler.utils), I noticed that if I used the same folder (path) as my output_dir, old split files are not deleted. So if at first the split_file created 60 parts (part_1 to part_60), and the second use of split_file resulted only in 30 parts created (part_1 to part_30), what happens is that it only overwrite part_1 to part_30, but part_31 to part_60 is still left intact.

In processor, for the train_filename, only the path to these split_files is given. And from the _StreamingDataSet code, I notice that if a folder/directory is given as train_filename instead of a file, it will get a list of all files in that folder and process it all instead of just processing the 30 parts it should process. This will result in unpredictable training results, which would actually be incorrect, but then the cause would be very hard to trace, unless you happen to look into the folder and notice it.

A safer approach in my opinion would be giving the parts a unique extension during the creation (for example the files will then be named part_1.tsf to part_60.tsf, where tsf stands for temporary split files), so it will be safe to delete all files with that extension at the beginning of the split_file method.

**Comment by Timoeller** [comment]
Nice catch.

Since output dir is a parameter set by the user I would not automatically delete files in there, imaging FARM would delete important files still needed by the user. How about creating a logger warning if the directory is already filled with files? Would you like to create a PR for that?

**Comment by lingsond** [comment]
Hi Timo,

It would be a bit complicated if I'm doing it. There will be still a few things to consider. Should the process then stop after the logger warning? Otherwise it kind of makes no sense just to give a warning but the process goes on. If the process stops, it means the whole script has to be rerun all from the beginning. If there has been many things done before it is stopped and the user has to start all over again after wasting a lot of times (the script can be complicated as well also be simple, so who knows).
So I think you need to further discuss with your team how to handle this issue the best way. Thus I pass on this one.  (Besides, I'm not too familiar with logger LOL). Thanks for the offer though.

**Comment by lingsond** [comment]
Btw, in my opinion, giving the split files a unique extension that no application is using would be quite safe (which means that those files can only be split files from before). Even if there are old split files there, it would nevertheless be overwritten by the split_file method. So by giving them a unique extension and only deleting files with those extensions shouldn't cause any problems.
Well, it's just an option to consider. But as I said above, I pass on this one.

**Comment by Timoeller** [comment]
I like your train of thought. This is exactly what you need to consider for open source applications. 

The custom file extension idea might be ok, but I still feel unwell when deleting files without consent of a user. Just imagine the potential harm you can create. So I think a logger warning that files are already present and letting the script continue is fine. FARM users are expected to and (hopefully) want to think about the code they are writing.

About logger warnings. It is quite easy. Just use `logger.warning("warning message here")`. 
Would you like to create a PR with this? If you have a fail safe solution for your file extension I am also happy to reconsider adding it.

**Comment by lingsond** [comment]
Sorry, I was on holiday for a while.

Thanks for the info regarding using logging.

The only solution that I can think of is what I suggested before. To give the generated split files a custom file extension, and then only deleting the files with that extension in the folder. The split files should be treated like temporary files (it is common practice to delete temp files in our devices) and the user wouldn't lose the original previous dataset since no other files except those with the custom extension would be deleted. 

If you only warn the user without stopping or pausing the process, although the user could read the warning afterward, however, the damage would already been done. If the supposed training data only has like 10 files, but there are still old files from previous training numbered to like 20, then it will train using the 10 files it is supposed to use, plus file 11 to 20 from the previous process. This should not happen because the new and old dataset could be totally unrelated, and the training result would be ruined.

Of course, the user can then delete the old files (which he might only recognize because of the different timestamp) or just delete all files and do the splitting again from beginning, then training the data again. Depends on the size, the user would 'only' lose hours, days, or weeks of his time. Unless this is stated in the documentation (which isn't at the moment), then if the user didn't read it, it would be the user's fault.

This has quite an important impact, so I still rather stay out from this.

Should I close this issue?

**Comment by Timoeller** [comment]
Ok, I understand your concerns. And agreed, temp files can also be deleted, if they are constructed like [temp files](https://docs.python.org/3/library/tempfile.html) and conform with certain OS dependent standards. 
If you want to implement such a method we are happy to consider including it.
Otherwise feel free to close the issue.
