### ISSUE TITLE
LM finetuning example missing data

### ISSUE THREAD

**Issue by bnic24** [deepset-ai/FARM#47]
Trying to run `examples/lm_finetuning.py` results in `FileNotFoundError: [Errno 2] No such file or directory: '../data/finetune_sample/train.txt'`. The other examples seem to be able to automatically download the dataset if it's not present.

**Comment by tholor** [comment]
Yep, there's already a PR in the making: https://github.com/deepset-ai/FARM/pull/44
It's currently under review but will be merged soon :)

**Comment by tholor** [comment]
Just merged it! You should have some dataset containing NIPS papers now for running the example. Just be aware that data preprocessing is currently sequential and therefore rather slow on large datasets. We are already working on speeding things up via multiprocessing in #45. Should be ready within the next days ...
