### ISSUE TITLE
How to get model metrics after training?

### ISSUE THREAD

**Issue by pmavrodiev** [deepset-ai/FARM#473]
**Question**
How do I get the metrics of interest after training is complete?

**Additional context**
After **trainer.train()** is executed, we get diagnostic logs in the terminal (such as model metrics after each epoch and so on). How can one retrieve the final metric of interest after trainer.train() is done? All examples simply show how to save the model and then load it to make predictions.

**Comment by Timoeller** [comment]
Hey thanks for using FARM. Here we have some examples of how to do evaluation on a saved model: https://github.com/deepset-ai/FARM/blob/master/examples/evaluation.py
The reported stats for the dev or test sets during training are not stored when saving the model though. You have to recompute those. 
Hope that helps?

**Comment by Timoeller** [comment]
Any updates on the progress of this issue so far @pmavrodiev ? If the additional info resolved the issue, please close it.

**Comment by pmavrodiev** [comment]
Hi @Timoeller 

As you mentioned in your comment "The reported stats for the dev or test sets during training are not stored when saving the model though". So, I take it that the performance logs reported during training are not saved. One either has to implement some custom logging functionality (e.g. save stats to a file every 100th iteration or so) or simply learn to live without it. I've done the latter.

I will mark this issue as closed, though a more appropriate tag would be 'not implemented'

**Comment by Timoeller** [comment]
Ah thanks for clarification. I thought you wanted to compute stats for after training but now I understand you want the stats during training (accessible after training :)

We have implemented MLflow logging of stats. You could add your custom MLflow instance to it or the default it that it logs to our public instance https://public-mlflow.deepset.ai/ where you can see all the details you need.
