### ISSUE TITLE
Logging results for evaluation

### ISSUE THREAD

**Issue by YojanaGadiya** [deepset-ai/FARM#478]
Dear all,

I am trying to log my results for evaluation using Evaluator.log_results( ). I wanted to know whether this would log the results as a message or in a specific file in the mlflow logging directory?

Thank You.

**Comment by Timoeller** [comment]
The signature of log_results() is as follows:
`def log_results(results, dataset_name, steps, logging=True, print=True, num_fold=None):`
So you can choose weather you want to print to stdout and/or log to MLlogger, which can be of type MLFlow. How you setup the MLflow logger is up to you. To answer your question, the default is both, printing and logging to however you configured MLFlow.

I guess though you want to collect the results somehow for further processing? As mentioned in the issue #465 you created you can look at the evaluation example and adjust that to your use case.
For Question Answering you extract the results from the evaluator like so:
```
# 6. Run the Evaluator
results = evaluator.eval(model)
f1_score = results[0]["f1"]
em_score = results[0]["EM"]

**Comment by Timoeller** [comment]
Any updates on the progress of this issue so far @YojanaGadiya ?

**Comment by YojanaGadiya** [comment]
Hey! sorry for the delay in replying. It works! Thank you.

**Comment by Timoeller** [comment]
Awesome, glad to help. Closing now
