### ISSUE TITLE
Hyperparameters of your BERT Model evaluation

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#487]
Hi,

your BERT model evaluation here: https://deepset.ai/german-bert

Are these your hyperparameters you used: https://github.com/deepset-ai/FARM/tree/master/experiments/german-bert2.0-eval

If not - could you please give me an hint?

Thanks
Philip

**Comment by Timoeller** [comment]
Nope, those parameters are from the next generation of German LMs and not the original german-Bert ones.
But you could use those as a starting point of course.

Normally it is pretty difficult to overfit LMs, so you do not have to be afraid of using many epochs.
The nasty complexity comes from small and/or very difficult datasets. There you might get quite different results when doing multiple runs with different random seeds.

**Comment by PhilipMay** [comment]
Ahh I see! :-)
