### ISSUE TITLE
`dev_size` param in run-by-config is being ignored

### ISSUE THREAD

**Issue by tripl3a** [deepset-ai/FARM#49]
I tried setting the `dev_size`parameter in the following ways (in different runs).

```
"dev_size": {"value": [0.2,0.3], "default": 0.1, "desc": "Split a dev set from the training set using dev_size as proportion."}
"dev_size": {"value": 0.2, "default": 0.1, "desc": "Split a dev set from the training set using dev_size as proportion."}
"dev_size": {"value": null, "default": 0.2, "desc": "Split a dev set from the training set using dev_size as proportion."}
```

It always defaulted to `dev_size=0.1`. This value is being set in the constructor of my processor, just as in the GermEval examples.

Is this supposed behaviour?

**Comment by tanaysoni** [comment]
Hi @tripl3a. It isn't the supposed behaviour, but an error. It's now fixed by #53.
