### ISSUE TITLE
Format of test and train input files for multilabel classification

### ISSUE THREAD

**Issue by rdpulgar** [deepset-ai/FARM#493]
Hi,
I have multiple labels for one text entry in different columns in my dataset, however FARM asks me for a "label_column_name" so I merged all the columns in one column named "label" separated by \n, however FARM does not read the file:
ValueError: 'MM\nPR' is not in list

Could you tell me how to format the input file in my case.

Thank you

**Additional context**
I am new in text classification.

**Comment by mozzerela** [comment]
8999Sent via the Samsung Galaxy S8, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: rdpulgar <notifications@github.com> Date: 8/15/20  12:36 AM  (GMT-06:00) To: deepset-ai/FARM <FARM@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [deepset-ai/FARM] Format of test and train input files for multilabel classification (#493) 
Hi,
I have multiple labels for one text entry in different columns in my dataset, however FARM asks me for a "label_column_name" so I merged all the columns in one column named "label" separated by \n, however FARM does not read the file:
ValueError: 'MM\nPR' is not in list
Could you tell me how to format the input file in my case.
Thank you
Additional context
I am new in text classification.

**Comment by Timoeller** [comment]
Hey, no problem. Specifying the data input can be non trivial.

We do have an example script for doing multilabel classification here: https://github.com/deepset-ai/FARM/blob/master/examples/doc_classification_multilabel.py
This script downloads some data files and you can check out the structure there.

In general you want to separate multiple labels with a comma and the default in FARM for separating text from label is to use a tab delimiter.

Hope that helps? If anything else comes up let us know.

**Comment by Timoeller** [comment]
Did this resolve the issue @rdpulgar ? If so please close it

**Comment by rdpulgar** [comment]
Hi, Yes, I do. I am sorry I did not know that I have to close it. I learned more today.

**Comment by rdpulgar** [comment]
Thank you.

**Comment by Timoeller** [comment]
Hey @rdpulgar thanks for closing. 
There is of course no obligation to close the issue, it is just easier for us (and other people having similar issues) when we get feedback on proposed solutions and if they worked.
