### ISSUE TITLE
Store Test Eval. Result in Variable

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#496]
FARM is doing test set evaluation when certain conditions are met. The results are only logged but it is impossible / hard to get them with downstream Python code. I think the test set evaluation results should be stored in a variable so they can be read. 

What do you think? As always I would crate a PR.

**Comment by tholor** [comment]
Yes, I think it would be useful as long as it doesn't complicate the trainer too much or introduces breaking changes. 

Results could either be saved in a variable or potentially as an alternative also written to a file. The latter wouldn't introduce changes to the return signature of trainer.train(). Open do other design ideas, too.  

FYI There was a slightly related discussion in #353 about storing the **predictions** made during eval to a file (for external eval scripts). Possibly we could even tackle both use cases ...

**Comment by PhilipMay** [comment]
I made a PR for this on #506 
It does not introduce any breaking change.
