### ISSUE TITLE
Update to torch 1.6 and use "native" amp

### ISSUE THREAD

**Issue by djstrong** [deepset-ai/FARM#497]
Update to torch 1.6 and use "native" amp

**Comment by tholor** [comment]
Definitely on our roadmap! 
Update to torch 1.6 rather soon. "Native" amp might take a bit more testing and integration work. 

Would you maybe interested in contributing the change to native amp @djstrong ?

**Comment by Timoeller** [comment]
updated FARM to use torch 1.6, feel free to reopen once there is news about native amp
