### ISSUE TITLE
Multitask learning with separate datasets

### ISSUE THREAD

**Issue by djstrong** [deepset-ai/FARM#499]
**Question**
How to configure multitask learning with separate datasets? I have 2 `DataSilo`s with separate prediction heads. Or there is a need to have only one `Processor` and one `DataSilo`?

**Comment by tholor** [comment]
Yeah, the Trainer expects a single DataSilo. For multitask learning you would usually rather adjust the processor. In many cases merging the datasets to one (e.g. csv with multiple columns) can also simplify the implementation.

**Comment by djstrong** [comment]
So, can I write a processor that reads many datasets in different formats (token classification, text classification) and repeating tasks (e.g. I have two NER datasets, but with different annotation schema, so it needs two separate heads)?

**Comment by tholor** [comment]
Yes, you could write such a new processor. In the end, the abstraction for the processor is: take in a file and return a pytorch dataset with tensors. However, if you really need to deal with multiple files as input, this will revolve quite some implementation work on your side. 

We mostly worked in multitask settings where you have multiple annotations / tasks per text sequence, i.e. one sample is a text sequence and you have e.g. MLM, NER and classification tasks at the same time to create a more robust LM. 

 > I have two NER datasets, but with different annotation schema, so it needs two separate heads

If it's only the annotation format, but the input tensors / task will look similar, you could also consider one NER head. Depends also a bit on your ultimate goal (one strong NER head vs. two different ones). Also: if you have two different NER datasets from different corpora, why do you want to train in a multitask setting and not sequentially (first on one, then on the second)?

**Comment by djstrong** [comment]
I am interested in one head for the second NER annotation schema.

> Also: if you have two different NER datasets from different corpora, why do you want to train in a multitask setting and not sequentially (first on one, then on the second)?

I think it is more complicated, I can not train too much on the first, because LM can forget knowledge necessary for classes present in the second NER. Also, hyperparameter optimization is more complicated in that scenario. In my opinion, multitask learning with proper losses weights will give the best result.

**Comment by tholor** [comment]
How did you end up doing this @djstrong?

**Comment by djstrong** [comment]
In the end, I have chosen [jiant](https://github.com/jiant-dev/jiant/) for these experiments. So, you can close this issue. Thank you!
