### ISSUE TITLE
Example Bug: micro and macro confusion.

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#501]
See here: https://github.com/deepset-ai/FARM/blob/761028ff017bff339c3e742c35033e3a4fcd843d/examples/doc_classification_with_earlystopping.py#L62

I can provide a PR if you want.

**Comment by tholor** [comment]
Oh, good spotting! Thanks for reporting. A PR would be very much appreciated :)

**Comment by PhilipMay** [comment]
see PR #505
