### ISSUE TITLE
Feature Request: Add Option to save model in memory when doing EarlyStopping

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#509]
When I am doing EarlyStopping and want to evaluate my model on the test set I have to store it on disk
every time the EarlyStopping evaluates the model and it improved. This costs much time.

What do you think about an option to store the model in memory? That would improve speed a lot.
Did you ever try to implement that? Do you think it is hard? Would you accept a PR?

**Comment by PhilipMay** [comment]
Maybe an in memory filesystem can be used: https://docs.pyfilesystem.org/en/latest/reference/memoryfs.html

**Comment by Timoeller** [comment]
In general training and evaluating with large LMs like BERT take quite some time, so caching models in memory is less useful.

For your use case, did you benchmark the times spend on actual modelling vs saving + loading? Do you have SSD attached to your instance?

If you find a way to implement this feature without breaking changes we are of course happy to help integrating this feature. Please first make sure it is actually needed and improves the speed significantly.

**Comment by PhilipMay** [comment]
One reason why I am interested in this is that AWS sometimes has low performance on saving models....

**Comment by Timoeller** [comment]
Please first report saving and loading times of the models under different settings (e.g. instances, model types, model size, task type?).

My gut feeling is it takes less than 5 seconds for loading or saving each.

**Comment by PhilipMay** [comment]
Well - I discovered the option to just save the model somewhere to `/dev/shm` which is an in memory filesystem on linux boxes. That is enough for me. 

Closing this again.
