### ISSUE TITLE
Trainer does not use loaded model for test set evaluation

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#522]
When using early stopping the best models are saved. Later they are loaded here:
https://github.com/deepset-ai/FARM/blob/c6871b67401eef36f9d4310c966063eda10b0dfe/farm/train.py#L355-L356

But here the evaluator does not get the loaded model `model` but the old model `self.model`:
https://github.com/deepset-ai/FARM/blob/c6871b67401eef36f9d4310c966063eda10b0dfe/farm/train.py#L365

This is a bug...

**Comment by PhilipMay** [comment]
Also the question is if the trainer should return the last model or the best model? See here:

https://github.com/deepset-ai/FARM/blob/c6871b67401eef36f9d4310c966063eda10b0dfe/farm/train.py#L367

**Comment by PhilipMay** [comment]
Fix in #524

**Comment by PhilipMay** [comment]
PR was merged. Closing this.

**Comment by Timoeller** [comment]
Thanks for spotting and also fixing!

**Comment by PhilipMay** [comment]
Was a nasty little bug - right? :-)
