### ISSUE TITLE
Link to notebook or tutorial

### ISSUE THREAD

**Issue by dsvrsec** [deepset-ai/FARM#534]
**Question**
I have tried question answering system in https://demos.deepset.ai/ .Is there any notebook using or link to model bert-english-qa-large,where i can do some hands on

**Additional context**
Add any other context or screenshots about the question (optional).

**Comment by Timoeller** [comment]
Hey, I guess you want to work with the model inside code and not just on the demos page? 

The model we are using in the demo is uploaded to the [transformers model hub](https://huggingface.co/deepset/bert-large-uncased-whole-word-masking-squad2) 

You can then use the model like:
```
from farm.modeling.adaptive_model import AdaptiveModel
from farm.modeling.tokenization import Tokenizer
from farm.infer import Inferencer

model_name = "deepset/bert-large-uncased-whole-word-masking-squad2"
nlp = Inferencer.load(model_name, task_type="question_answering")
QA_input = [{"questions": ["Why is model conversion important?"],
             "text": "The option to convert models between FARM and transformers gives freedom to the user and let people easily switch between frameworks."}]
res = nlp.inference_from_dicts(dicts=QA_input, rest_api_schema=True)

**Comment by tholor** [comment]
If you want to do QA on a larger set of documents (instead of single paragraphs), you might also be interested in our [Haystack](https://github.com/deepset-ai/haystack/) framework and this [Colab Tutorial Notebook](https://colab.research.google.com/github/deepset-ai/haystack/blob/master/tutorials/Tutorial1_Basic_QA_Pipeline.ipynb).

**Comment by dsvrsec** [comment]
If I have a set of documents(pdf,ppt,docx,xlsx).Is there any way i can use haystack ,to build query system.If so,can you please provide a reference document

**Comment by Timoeller** [comment]
This is a very specific haystack question so can you please ask that question in haystack directly? So others can benefit from this conversation, they will unlikely find it here on another repo...
