### ISSUE TITLE
Data format for using lm_finetuning.py?

### ISSUE THREAD

**Issue by marcusau** [deepset-ai/FARM#545]
I am finetuning the bert model with my own corpus in train.txt

The text data is stored as one sentence one line format.
![image](https://user-images.githubusercontent.com/31444195/93452176-b0d59d00-f90a-11ea-802d-743c8e06f1e9.png)

However , i encountered with the following problem
    
# 2. Create a DataProcessor that handles all the conversion from raw text into a pytorch Dataset
processor = BertStyleLMProcessor(  data_dir=Path(data_dir),tokenizer=tokenizer, max_seq_len=202,  max_docs=1,  next_sent_pred_style=next_sent_pred_style )

    # 3. Create a DataSilo that loads several datasets (train/dev/test), provides DataLoaders for them and calculates a few descriptive statistics of our datasets
data_silo = DataSilo(processor=processor, batch_size=batch_size, max_multiprocessing_chunksize=20)

![image](https://user-images.githubusercontent.com/31444195/93450678-d2358980-f908-11ea-86a3-429e1d3b0e59.png)

**Comment by Timoeller** [comment]
answered in https://github.com/deepset-ai/FARM/issues/244

**Comment by marcusau** [comment]
Thanks a lot
