### ISSUE TITLE
problem in google colab about cuda

### ISSUE THREAD

**Issue by marcusau** [deepset-ai/FARM#547]
I have problem for cuda on google colab..

![image](https://user-images.githubusercontent.com/31444195/93456091-cef1cc00-f90f-11ea-8094-1ce97fb51e0b.png)

**Additional context**
Add any other context or screenshots about the question (optional).
![image](https://user-images.githubusercontent.com/31444195/93456049-c1d4dd00-f90f-11ea-8f8a-90d88e1d386f.png)

**Comment by tholor** [comment]
Hey @marcusau , 

Seems like a hickup of pytorch / cuda versions on your colab. 
Can you try to run `!pip install torch==1.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`?

Regarding amp: This will very likely not work on Colab. The installation of apex.amp can be quite tricky. We will move to Pytorch's new native amp in future. This should simplify usage in Colab.

**Comment by marcusau** [comment]
i am trying your solution now... give me 5 mins.

thanks

**Comment by marcusau** [comment]
sorry 

> Hey @marcusau ,
> 
> Seems like a hickup of pytorch / cuda versions on your colab.
> Can you try to run `!pip install torch==1.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`?
> 
> Regarding amp: This will very likely not work on Colab. The installation of apex.amp can be quite tricky. We will move to Pytorch's new native amp in future. This should simplify usage in Colab.

sorry just tried ..it does not work at all

**Comment by marcusau** [comment]
also , the thing is..... Farm cannot detect the cuda in colab  , but just amp.

I have installed nvidia amp on my colab,. i know the installation is quite tricky but i did succeed to make it..

However, the issue here is....Farm cannot connect to cuda on google colab.

**Comment by tholor** [comment]
I believe this is not really a FARM issue then, but rather that your GPU is not detected in PyTorch. Possible due to your AMP installation(?)
 
You can do a check via: 
```
import torch
torch.cuda.is_available()
```

**Comment by tholor** [comment]
FYI we also relaxed now the torch version requirements in FARM to allow 1.6.0+cu101 (the version preinstalled on colab)

**Comment by tholor** [comment]
Seems resolved. Feel free to re-open if not
