### ISSUE TITLE
Can I use haystack Elasticsearch to do the onnx inference?

### ISSUE THREAD

**Issue by laifuchicago** [deepset-ai/FARM#548]
To Author:
After I converted my model to onnx, how can I use haystack Elasticsearch to do the inference? Or currently haystack does not support?

Jonathan Sung

_Originally posted by @laifuchicago in https://github.com/deepset-ai/FARM/issues/537#issuecomment-693102039_

**Comment by Timoeller** [comment]
Could you ask this question in haystack please? Other people will be interested in the answer as well.
