### ISSUE TITLE
Natural Questions Inference return just one prediction result if there are more than one questions  

### ISSUE THREAD

**Issue by ftesser** [deepset-ai/FARM#551]
**Describe the bug**
Given a QA_input dictionary with more than one question e.g.:
```python
 QA_input = [
        {
            "qas": ["Did GameTrailers rated Twilight Princess as one of the best games ever created?", "Did GameTrailers rated Twilight Princess as one of the worst games ever created?"],
            "context":  "Twilight Princess was released to universal critical acclaim and commercial success. It received perfect scores from major publications such as 1UP.com, Computer and Video Games, Electronic Gaming Monthly, Game Informer, GamesRadar, and GameSpy. On the review aggregators GameRankings and Metacritic, Twilight Princess has average scores of 95% and 95 for the Wii version and scores of 95% and 96 for the GameCube version. GameTrailers in their review called it one of the greatest games ever created."
        }
    ]
```
the returned inference object:  
```python
result = model.inference_from_dicts(dicts=QA_input, return_json=False)
```
is a list that contains just one QApred object:
```python
[<farm.modeling.predictions.QAPred object at 0x7f50dcb73e20>]
```
that contains just the results for the first question.

**Expected behavior**
Do return a list of QAPred objects of the same size of the number questions listed in qas (like the "normal" Squad model does). 

**Additional context**
I understand that probably the reason of that is because the original NQ dataset contains just a question for each document, but I think that the API user it expect to receive answers for each question (or at least to be warned that Natural Questions Inference return just one prediction also of there are more questions).
   
**To Reproduce**
Modify  the `QA_input` in `examples/natural_questions.py` adding one or more questions (like above). 

Then run `examples/natural_questions.py` (to save time: the same error is obtained  running the script just from point 9 (https://github.com/deepset-ai/FARM/blob/c6871b67401eef36f9d4310c966063eda10b0dfe/examples/natural_questions.py#L125)

**System:**
 - OS: 
 - GPU/CPU:
 - FARM version:

**Comment by Timoeller** [comment]
Hey thanks for raising this issue, agreed this is unexpected behaviour but I would not necessarily call it a bug. We are currently refactoring the input dicts and will possibly handle this case differently. 

As you suggested: a warning message would be nice for now. Would you like to create a PR with it?

**Comment by ftesser** [comment]
Hello @Timoeller, yes I will make a PR for a warning message. 
But I really like to have this feature in FARM, I am going to explain why: 
In some scenarios, given a document, it is usual to make several questions for the same document, making just one call of:

```python
result = model.inference_from_dicts(dicts=QA_input, return_json=False)
```
is more efficient because the tokenization (and feature computation?) of the document is made just one time for document.

**Comment by Timoeller** [comment]
This is a good idea we also were trying to implement, 
but at least the feature computation has to be handled on one question + one document level, since question and doc text is concatenated when put into the language model.

The time it takes to tokenize a doc is really negligible, especially with fast tokenizers. So tokenizing twice to have a more clear structure and readable code is something we decided to go for. Do you agree with this?

**Comment by ftesser** [comment]
OK, you are right about feature computation (my fault). I just experiments some differences in performances between squadprocessor and naturalquestionprocessor, and I was thinking about the re-tokenization. 
I will make a try with fast tokenizers.

I agree that the structure is more clear with the constraint of [one doc + one question], and if the tokenization time is negligible I agree that is simple to manage that structure.

**Comment by ftesser** [comment]
Please @Timoeller see this last PR #565.

**Comment by Timoeller** [comment]
Thanks for adding the warning. Is it ok with you if we close this issue now while still working on a solution for including multiple questions in NQ inferencing?

**Comment by ftesser** [comment]
Yes, it is ok. Thanks!
