### ISSUE TITLE
Epoch (Step) vs Accuracy

### ISSUE THREAD

**Issue by gokberkyar** [deepset-ai/FARM#556]
I want to create a graph of metrics vs epoch or step. As far as I understand, all logging is done internally ?
Is it possible to access a epochs/steps log results that printed on console ?

I want to do this, logging is quite good but it does not give a clear picture of should a train more or stop ?
I am aware their is early stop option but it I would to visually confirm the behaviour of the model.

Best Regards,
Gökberk

**Comment by Timoeller** [comment]
Do you know mlflow? We have quite automatic mlflow integration. There you can visualize your performance over time.

**Comment by gokberkyar** [comment]
Thanks a lot
