### ISSUE TITLE
Preprocessing before tokenizer

### ISSUE THREAD

**Issue by datistiquo** [deepset-ai/FARM#561]
Hey!

I feel like this is a silly question.  What kind of preprocessing should I do for (german) text for your german trained BERT model?What about preprocessing like word stemming/lemmatization and stopwords. How is the advise for using BERT models? Should I replace umlauts like ä to ae?

Does it makes problems if I do stemming or lemmatization before feeding to BERT tokenizer?

Thank you for your advice!

**Comment by Timoeller** [comment]
There is no such thing as silly questions.

Language Models like Bert use subword tokenization. There you normally do not do any stemming or lemmatization, everything is handled by the tokenizer. 
You might want to process all uppercase words if you use a cased model, it might be that BANK is split into "B" "A" "N" and "K", depending on you vocab. 

When you run any of our examples you also see printouts how the tokenizer splits words - there you can find useful info about potential preprocessing. Normally text fits as is though :D

**Comment by datistiquo** [comment]
I just use your german base deeps bert model with tf2.  Up to now not within your framework. ;) Could you tell me what preprocessing steps you did to train this model? Then I just would need to do the same. 

Importantly the umlauts like ä,ü?

So, stemming is not necessary? Butt stemming could still be usefull as it trucnated the space. 

Could I remove stopwords still?

**Comment by Timoeller** [comment]
In the end there was not much preprocessing for cleaning the data. I can copy over the interesting bits from our scripts:

1. some whitespace and newline cleaning
2. removal of uncommon characters (in hindsight this step was actually suboptimal and our newer models are not character filtered)

```
    mytext = mytext.strip()
    mytext = mytext.replace("\n", " ")  # often used as delimiter
    mytext = re.sub(" +", " ", mytext)

    to_remove = ["\x0b", "\x0c", "\r", "\t", "\n"]
    to_add = ["§", "€", "ä", "Ä", "ü", "Ü", "ö", "Ö", "ß"]
    acceptable_chars = string.printable
    for s in to_remove:
        acceptable_chars = acceptable_chars.replace(s, "")
    acceptable_chars += "".join(to_add)

    mytext = "".join(filter(lambda x: x in acceptable_chars, mytext))

**Comment by datistiquo** [comment]
Thank you very much. Whitespace cleaning is just done with the split() method?

Do you use for german the wordpiece tokenizatioon like google did?

And I think a whitespace has an embedding too such that a sentence with more than one whitespace between words is different than with just one whitespace?

And of course, did you lowered the words? Did you find any differences in using just lowered text with a model which was  trained on upper cases?
> 2\. in hindsight this step was actually suboptimal and our newer models are not character filtered

Is this true for the current models using hugginface pretrained models?

**Comment by Timoeller** [comment]
Hey we also open sourced some newer German LMs. See https://twitter.com/deepset_ai/status/1319239276039733253?s=20

For tokenization we used the https://github.com/google/sentencepiece library, as written on our blog post about https://deepset.ai/german-bert

We did not lowercase any of our models. Our feeling is that for German and tasks like NER casing info is slightly more performant - we did not publish quantitative proof of this.

The newer models that we released are not charatcer filtered. See the accompanying [vocab file](https://cdn.huggingface.co/deepset/gbert-base/vocab.txt)

**Comment by Timoeller** [comment]
Seems fixed, closing now, feel free to reopen

**Comment by datistiquo** [comment]
Hey, sorry but still few questions. :-)

1) Are your deepset models the same as when using them by using "from_pretrained" with huggingface interface?
   - are just the newest models (not character filtered) on huggingface? Are older version somehow available?

2) Where did you get this vocab file? How can I generate this from my tokenizer (a pretrained model from huggingface)?

3) **I currently discovered large difference between cases and uncased words in german!** For information ´retrieval my system works well with cased words but when just lower casing the word, all is messed up.
So actually this is not very useful, when using the model for use cases where there is no distinction between cased/uncased... Do you have a lowered cased bert model? Or is there any uncased BERT model?

4)If I have to stick on a cased model what can I do about when I don't want a distinction between cased and uncased?

5) What is a cased model doing when seeing a lower cased word where it just has the cased word in the vocab? Actually very important to know...

6) Could'nt I just hack the tokenizer and lower cases everythinghaving a uncased model? So in above vocab file I would lower case evreything..

**Comment by datistiquo** [comment]
Also, it would be nice if you can see information about the models like what was the trainingdata? Maybe I cannot find it, but what kind of data is underlying for example this model?

https://huggingface.co/deepset/covid_bert_base

**Comment by datistiquo** [comment]
@Timoeller Any response ideas? :)

**Comment by tholor** [comment]
> Also, it would be nice if you can see information about the models like what was the trainingdata? Maybe I cannot find it, but what kind of data is underlying for example this model?

Hey @datistiquo, the model was trained on the CORD-19 dataset https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge

**Comment by datistiquo** [comment]
@Timoeller  @tholor  Adding lowercased examples to the training data ist not giving any great impact, sadly. 

I wonder if I can just simple finetuning the cased language model on text data and its lower cased version?
