### ISSUE TITLE
Support MultiGPU Training for DPR 

### ISSUE THREAD

**Issue by tholor** [deepset-ai/FARM#575]
**Is your feature request related to a problem or particular use case?**
Once we have basic DPR training merged ( #513), we should test and improve multi GPU training.

**Describe the solution you'd like**
Re-use the existing FARM pipeline to support DP and DDP.
DP should work pretty much out of the box. DDP might need additional checks for the local rank of the process.

**Comment by Timoeller** [comment]
Seems fixed with #619 
We will refactor in #623
