### ISSUE TITLE
Order of response with respect to multi context payload in case of multiprocessing

### ISSUE THREAD

**Issue by mdliyakat-dev** [deepset-ai/FARM#578]
**Question**
Is there any way to map the response back to the document Id in case of multi-processing?

**Additional context**
I have a list of documents along with content and id, I am sending content as the context. It is working fine if I send the contexts one by one as i can map the bert response back to the doc id after the response from BERT like {'answer': 'ans_text', 'score': 9, 'doc_id': doc['id']} in the code in the for loop.
But if I use multiprocessing feature here in order to improve the performance then how can map the response back to my doc ids.? as I don't know which response comes first, Should I assume the order as first things first? Is there a way I send doc_id along with context and BERT just returns the doc_id as it is as a part of the response?

**Comment by brandenchan** [comment]
Hi, even in multiprocessing you can assume that the order of the inference output is the same as the order of the input. One caveat to note is that if any of your inputs could not be processed, they will be skipped. In this case, you will see a warning message in the console output, and you will have one less output. 

If you're doing Question Answering, and you'd really like to have ids tied to each sample, you can simply add an "id" key to the input dictionary i.e.
```

{"qas": ...,
 "context": ...,
 "id": ...}
```

Does this help?

**Comment by mdliyakat-dev** [comment]
Thanks for the response, yes i am using this for question answer model. i am passing the 'id' in each dict but id is coming as None.
I am passing the payload as [{'question': 'who won the foozo game', 'context': 'a foozo game was played on India and Carbon team won the match', 'id': 'abcd123'}, {'question': 'who won the foozo game', 'context': 'a foozo game was played on India and Silver team lost the match', 'id': 'pqrst123'}]

**response as below:**

[{'id': None, 'preds': [['Carbon team won the match', 10, 14, 8.996845245361328], [None, -1, -1, -6.517568588256836]]}, {'id': None, 'preds': [['Silver team lost the match', 10, 14, 9.012173652648926], [None, -1, -1, -5.013319492340088]]}]

**Comment by brandenchan** [comment]
Hmmm that's odd. Could you post a code snippet to reproduce this? It would help us debug the issue!

**Comment by mdliyakat-dev** [comment]
Sure! Here below.

**=======================HERE IS THE ACTUAL PAYLOAD==================**

{
  "question": "who won the foozo game",
  "contexts": [
  {"content": "a foozo game was played on India and golden team lost the match", "id": "1234"},
  {"content": "a foozo game was played on India and carbon team won the match", "id": "9876"}
  ]
}


**=======================AND here is the code=======================**
question = json.loads(request.data)["question"]
contexts = json.loads(request.data)["contexts"]
print("received question as:", question)
print("received contexts as:", contexts)
qas = [{'qas': [question], 'context': context['content'], "id": context['id']} for context in contexts]

predictions = nlp.inference_from_dicts(dicts=qas)
print(f'predictions from list of qas {predictions}')

**=======================HERE IS THE RESPONSE======================**
received question as: who won the foozo game
received contexts as: [{'content': 'a foozo game was played on India and golden team lost the match', 'id': '1234'}, {'content': 'a foozo game was played on India and carbon team won the match', 'id': '9876'}]

**predictions from list of qas [{'id': None, 'preds': [['golden team lost the match', 10, 14, 7.1835174560546875], [None, -1, -1, -4.794795989990234]]}, {'id': None, 'preds': [['carbon team won the match', 10, 14, 8.996845245361328], [None, -1, -1, -6.517568588256836]]}]**

You can see "id" None above in the actual response.

**Comment by brandenchan** [comment]
So I was able to propagate id through the Inferencer. I first created a json called `inference_order.json` with the following contents

```
{
  "question": "who won the foozo game",
  "contexts": [
    {"content": "a foozo game was played on India and golden team lost the match", "id": "1234"},
    {"content": "a foozo game was played on India and carbon team won the match", "id": "9876"}
  ]
}
```

Then I ran the following script

```
import json
from pprint import pprint
from farm.infer import QAInferencer

f = open("inference_order.json")

data = json.load(f)
question = data["question"]
contexts = data["contexts"]
qas = [{'qas': [question], 'context': context['content'], "id": context['id']} for context in contexts]

nlp = QAInferencer.load("deepset/roberta-base-squad2", batch_size=40, gpu=True, task_type="question_answering")

predictions = nlp.inference_from_dicts(dicts=qas)
pprint(predictions)
```

My output is the following:

```

[{'predictions': [{'answers': [{'answer': 'golden team',
                                'context': 'a foozo game was played on India '
                                           'and golden team lost the match',
                                'document_id': '1234',
                                ...},
                               {'answer': 'no_answer',
                                'context': '',
                                'document_id': '1234',
                                ...}],
                   'ground_truth': [],
                   'id': '1234',
                   'no_ans_gap': 1.3637971878051758,
                   'question': 'who won the foozo game'}],
  'task': 'qa'},
 {'predictions': [{'answers': [{'answer': 'carbon team',
                                'context': 'a foozo game was played on India '
                                           'and carbon team won the match',
                                'document_id': '9876',
                                ...},
                               {'answer': 'no_answer',
                                'context': '',
                                'document_id': '9876',
                                ...}],
                   'ground_truth': [],
                   'id': '9876',
                   'no_ans_gap': 6.950742244720459,
                   'question': 'who won the foozo game'}],
  'task': 'qa'}]
```

Could you try these steps on your setup? I did this on the latest master.

**Comment by brandenchan** [comment]
Closing this for now. Feel free to reopen if you have any questions or updates!
