### ISSUE TITLE
Using question_answering_crossvalidation.py on the COVID-QA data fails

### ISSUE THREAD

**Issue by sbhttchryy** [deepset-ai/FARM#580]
Hello developers. 
I tried to run the question_answering_crossvalidation.py on the COVID-QA data (https://github.com/deepset-ai/COVID-QA/blob/master/data/question-answering/COVID-QA.json) and it did not work. It gave the error :

 assert datasilo.tensor_names[4] == "id", f"Expected tensor 'id' at index 4, found {datasilo.tensor_names[4]}"
AssertionError: Expected tensor 'id' at index 4, found passage_start_t

**Comment by Timoeller** [comment]
Hey @sbhttchryy I could not reproduce the issue on current FARM master.

I also remember we changed these tensor indices some while ago to be correct, so could you update your FARM version and try again?

**Comment by Timoeller** [comment]
Any updates on this @sbhttchryy ?
Does the error persist when using the current FARM master?

**Comment by Timoeller** [comment]
Seems inactive and hopefully solved. Closing for now, feel free to reopen if the error persists.
