### ISSUE TITLE
Circular import in conversion/tranformers.py throwing AttributeError for python version below 3.7

### ISSUE THREAD

**Issue by Timoeller** [deepset-ai/FARM#582]
**Describe the bug**
When running any of our examples I get an attribute error during module importing

**Error message**
  File "/foo/FARM/farm/modeling/adaptive_model.py", line 19, in <module>
    import farm.conversion.transformers as conv
  File "/foo/FARM/farm/conversion/transformers.py", line 6, in <module>
    import farm.modeling.adaptive_model as am
AttributeError: module 'farm.modeling' has no attribute 'adaptive_model'

**Additional context**
This happens only for Python 3.6.
In Python 3.7 they changed import behavior, see https://bugs.python.org/issue30024

** Proposed Soltution**
Moving the Converter back to adaptive_model.py script. @bogdankostic @tholor what do you think? 
Alternative would be tanays quick fix in #581 but this fix might create problems on other setups.

**Comment by tholor** [comment]
> Alternative would be tanays quick fix in #581 but this fix might create problems on other setups.

@Timoeller What kind of problems do you see with other setups?

**Comment by Timoeller** [comment]
e.g. is the python version fix in haystack? What about python 3.5, does it work there? 
In general having circular dependencies is bad design practice and we should avoid it.

**Comment by Timoeller** [comment]
I merged #581 into master. Lets keep it like this for now and work on it once problems occur.
