### ISSUE TITLE
Separate max_seq_len for question and passages in DPR

### ISSUE THREAD

**Issue by tholor** [deepset-ai/FARM#593]
**Is your feature request related to a problem or particular use case?**
At the moment we have a single `max_seq_len` param that is applied to both text sequences (question and passage). 

**Describe the solution you'd like**
As questions are usually way shorter so we should allow a separate param here. 
This would save some compute during training as we have shorter sequences for the question encoder.

**Comment by kolk** [comment]
Fixed in PR #606
