### ISSUE TITLE
Could not convert this sample to features

### ISSUE THREAD

**Issue by SAIKIRAN0802** [deepset-ai/FARM#596]
**Question**
I am Trying to build a chatbot on reddit corpus and during the preprocessing we get the following errors and could not fully process all the documents or convert to features.the error logs that i see are as follows.

**Additional context**
Add any other context or screenshots about the question (optional).
Preprocessing Dataset file-uploads/123bfdb97e3d4a1692dc347c9e836826_annotate_21oct.json:  20%|█████▊                       | 5/25 [09:10<36:40, 110.00s/ Dicts]
10/21/2020 06:49:41 - WARNING - farm.modeling.prediction_head -   Some unused parameters are passed to the QuestionAnsweringHead. Might not be a problem. Params: {"training": false, "num_labels": 2, "ph_output_type": "per_token_squad", "model_type": "span_classification", "label_tensor_name": "question_answering_label_ids", "label_list": ["start_token", "end_token"], "metric": "squad", "name": "QuestionAnsweringHead"}
10/21/2020 06:49:42 - INFO - farm.modeling.optimization -   Loading optimizer `TransformersAdamW`: '{'correct_bias': False, 'weight_decay': 0.01, 'lr': 1e-05}'
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

10/21/2020 06:49:01 - ERROR - farm.data_handler.processor -   Basket id: id_internal: 5-6, id_external: 104
10/21/2020 06:49:01 - ERROR - farm.data_handler.processor -   Error message: Answer using start/end indices is 'ng an API Gateway instead of a Load Balancer for this use case. API Gateway supports custom domain names and TLS certificates provided by ACM.
Thanks for ' while gold label text is 'Consider using an API Gateway instead of a Load Balancer for this use case. API Gateway supports custom domain names and TLS certificates provided by ACM.'
10/21/2020 06:49:01 - ERROR - farm.data_handler.processor -   Could not convert this sample to features:

**Comment by SAIKIRAN0802** [comment]
do you think these errors are due to presence of special characters such as ‘@‘ and quotation marks. If so, what’s the best way to retain them and process them?

**Comment by Timoeller** [comment]
Hey thanks for using our annotation tool and haystack for it. The annotation tool has some offset problems, depending on operating system used and special symbols.
Please have a look at the answers in a very related issue on haystack deepset-ai/haystack/issues/492 for a solution.

btw this should also be related to the other issue #597 you opened about docs not being converted

**Comment by SAIKIRAN0802** [comment]
@Timoeller thanks for the reply btw i managed to get rid of errors by removing docs that could not be processed and removed errors and tried to fine-tune it i need help in understanding how does it fine-tune it convereted 5/13  and proceded with the training i could not understand what about the remaing mentioned in the issue #597

**Comment by Timoeller** [comment]
This 5/13 could also be a printing issue. I cannot really tell if your docs are converted or not from this message.

You could try setting the parameter `num_processes` to 1 in the FARMReader.train method and see if the printout changes.
Or you can use the script in FARM to train your model, there is more output: see https://github.com/deepset-ai/FARM/blob/master/examples/question_answering.py

**Comment by SAIKIRAN0802** [comment]
> This 5/13 could also be a printing issue. I cannot really tell if your docs are converted or not from this message.
> Did you verify that it only converted 5 out of 13 docs in the debugger, or is it just the printout?
> 
> You could try setting the parameter `num_processes` to 1 in the FARMReader.train method and see if the printout changes.
> Or you can use the script in FARM to train your model, there is more output: see https://github.com/deepset-ai/FARM/blob/master/examples/question_answering.py

i tried `num_processes ` that didnt work tried running the script and it works in that case but uses whole of gpu and gets me this error `CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 14.76 GiB total capacity; 13.77 GiB already allocated; 109.75 MiB free; 13.84 GiB reserved in total by PyTorch)`

**Comment by Timoeller** [comment]
Seems fixed, closing now, feel free to reopen.
