### ISSUE TITLE
Response truncated/incomplete in case of answer the end of the huge context

### ISSUE THREAD

**Issue by mdliyakat-dev** [deepset-ai/FARM#602]
I have come across a situation in which if the answer is at the end of huge context then the prediction response is either incomplete or truncated BUT when I paste the answer part at the beginning then it comes with complete response. Any help in this regard?

**Comment by brandenchan** [comment]
Hey @mdliyakat-dev, we've been noticing some issues with answers at the beginning at passages too (cf. #552). I'll be looking into both these issues this sprint.

**Comment by brandenchan** [comment]
In the meantime, it would be really helpful if you had an example script so we could reproduce your problem!

**Comment by mdliyakat-dev** [comment]
Examples below:
Payload 1 **for answer at the end of context and response is incomplete.**
{"qas": "What happens if I surrender my Rider",
"context": "FAQ’s What if I am not happy with the Rider after buying it? (Free look Cancellation) If you are not satisfied with any of the Terms and Conditions of the Rider, you may return the Rider document along with a letter stating the reasons for disagreement to us within 15 days or 30 days (in case of an electronic Policy or if purchased through Distance Marketing mode) from the date of receipt of the Rider document. On cancellation of the Rider within the free look period, we will return the Rider Premium paid under the Rider (including taxes) subject to the deduction of: • Proportionate risk premium (including taxes) and • Expense incurred by us for medical examination (if any) and stamp duty The Rider will terminate on payment of this amount and all rights, benefits and interests under this Rider will stand extinguished. On cancellation of the Base Plan, the Rider will also stand cancelled. What is Distance Marketing? Distance Marketing includes every activity of solicitation (including lead generation) and sale of insurance products through the following modes: (i) Voice mode, which includes telephone-calling (ii) Short Messaging service (SMS) (iii) Electronic mode which includes e-mail, internet and interactive television (DTH) (iv) Physical mode which includes direct postal mail and newspaper & magazine inserts and (v) Solicitation through any means of communication other than in person. What if I missed my premium due date? (Grace period) You are advised to pay premiums on or before the Premium due date to continue enjoying the benefits of this Rider. However, in case you are unable to do so, you have a Grace Period after the premium due date within which you can pay the due premium. Grace Period under this Rider will be same as applicable to the Base Policy. If any premium remains unpaid after the expiry of the Grace Period, the Rider will lapse, and the cover will cease to exist. The Rider will be in force during the Grace Period. In case of contingent event occurs during the grace period, benefit payable will be reduced by the level of Outstanding Instalment Premium (1) (including taxes) as at the date of occurrence of the event. (Outstanding Instalment Premium in the above case is the due instalment premium(s) that were due but unpaid before the death of the Life Insured.) What happens if I stop paying the due premiums? On non-payment of any due premiums within the grace period, the Rider will lapse, and all the benefits will cease to exist. No Benefit shall be payable for lapsed Rider under Regular Pay mode. In case of Limited Pay mode, Unexpired Risk Premium Value (if any) would be payable as Lapse Benefit under the following circumstances whichever is earlier: • The Policyholder voluntarily Surrenders the rider; or • The Life Assured dies; or • The Life Assured survives to the end of the revival period. The Unexpired Risk Premium Value (URPV) is computed as: URPV = 70% * ( Total Rider Premiums Paid / Total Premiums Payable over the Term) * (Outstanding Rider Term/Rider Term) * Total Rider Premium Paid (For the purpose of computation of URPV, the rider premiums shall exclude the underwriting extra premiums, any loadings for modal premiums and taxes.) The Rider will terminate on payment of this benefit. How can I revive my Rider? If your Rider has lapsed, you may revive the Rider along with the Base Policy. The revival period will be same as the revival period of the Base Policy to which the Rider has been attached. The revival will be subject to our underwriting guidelines and payment of all outstanding premiums without any interest. If the Rider is not revived along with the Base Plan, the Rider would be deemed Surrendered and revival of such surrendered Rider will not be allowed at a later stage. However, one or more of the benefit options within the rider can be added anytime during remaining premium payment term, provided the Base Plan is in-force and premiums will be applicable based on attained age of Life Assured. This addition will be subject to underwriting guidelines of the company. \n**What happens if I surrender my Rider? We advise you to continue your Rider for the complete Rider Term. However, in case if you still decide to surrender your Rider, surrender benefit will be payable in following manner: For Regular Pay Policies, no benefit is payable on surrender of the Rider and For Limited Pay policies, we will pay the Unexpired Risk Premium Value (URPV) which is computed as: URPV = 70% * ( Total Rider Premiums Paid / Total Premiums Payable over the Term) * (Outstanding Rider Term/Rider Term) * Total Rider Premium Paid (For the purpose of computation of URPV, the rider premiums shall exclude the underwriting extra premiums, any loadings for modal premiums and taxes.) The Rider will terminate on payment of this benefit.**"}

**Response incomplete** 
{
    "answer": "surrender benefit will be payable in following manner: For Regular Pay Policies, no benefit is payable",
    "score": 12.446493148803711
}

**Payload 2 for answer near to middle of context and response is truncated.**
{"qas": "What happens if I surrender my Rider",
"context": "FAQ’s What if I am not happy with the Rider after buying it? (Free look Cancellation) If you are not satisfied with any of the Terms and Conditions of the Rider, you may return the Rider document along with a letter stating the reasons for disagreement to us within 15 days or 30 days (in case of an electronic Policy or if purchased through Distance Marketing mode) from the date of receipt of the Rider document. On cancellation of the Rider within the free look period, we will return the Rider Premium paid under the Rider (including taxes) subject to the deduction of: • Proportionate risk premium (including taxes) and • Expense incurred by us for medical examination (if any) and stamp duty The Rider will terminate on payment of this amount and all rights, benefits and interests under this Rider will stand extinguished. On cancellation of the Base Plan, the Rider will also stand cancelled. \n**What happens if I surrender my Rider? We advise you to continue your Rider for the complete Rider Term. However, in case if you still decide to surrender your Rider, surrender benefit will be payable in following manner: For Regular Pay Policies, no benefit is payable on surrender of the Rider and For Limited Pay policies, we will pay the Unexpired Risk Premium Value (URPV) which is computed as: URPV = 70% * ( Total Rider Premiums Paid / Total Premiums Payable over the Term) * (Outstanding Rider Term/Rider Term) * Total Rider Premium Paid (For the purpose of computation of URPV, the rider premiums shall exclude the underwriting extra premiums, any loadings for modal premiums and taxes.) The Rider will terminate on payment of this benefit.** What is Distance Marketing? Distance Marketing includes every activity of solicitation (including lead generation) and sale of insurance products through the following modes: (i) Voice mode, which includes telephone-calling (ii) Short Messaging service (SMS) (iii) Electronic mode which includes e-mail, internet and interactive television (DTH) (iv) Physical mode which includes direct postal mail and newspaper & magazine inserts and (v) Solicitation through any means of communication other than in person. What if I missed my premium due date? (Grace period) You are advised to pay premiums on or before the Premium due date to continue enjoying the benefits of this Rider. However, in case you are unable to do so, you have a Grace Period after the premium due date within which you can pay the due premium. Grace Period under this Rider will be same as applicable to the Base Policy. If any premium remains unpaid after the expiry of the Grace Period, the Rider will lapse, and the cover will cease to exist. The Rider will be in force during the Grace Period. In case of contingent event occurs during the grace period, benefit payable will be reduced by the level of Outstanding Instalment Premium (1) (including taxes) as at the date of occurrence of the event. (Outstanding Instalment Premium in the above case is the due instalment premium(s) that were due but unpaid before the death of the Life Insured.) What happens if I stop paying the due premiums? On non-payment of any due premiums within the grace period, the Rider will lapse, and all the benefits will cease to exist. No Benefit shall be payable for lapsed Rider under Regular Pay mode. In case of Limited Pay mode, Unexpired Risk Premium Value (if any) would be payable as Lapse Benefit under the following circumstances whichever is earlier: • The Policyholder voluntarily Surrenders the rider; or • The Life Assured dies; or • The Life Assured survives to the end of the revival period. The Unexpired Risk Premium Value (URPV) is computed as: URPV = 70% * ( Total Rider Premiums Paid / Total Premiums Payable over the Term) * (Outstanding Rider Term/Rider Term) * Total Rider Premium Paid (For the purpose of computation of URPV, the rider premiums shall exclude the underwriting extra premiums, any loadings for modal premiums and taxes.) The Rider will terminate on payment of this benefit. How can I revive my Rider? If your Rider has lapsed, you may revive the Rider along with the Base Policy. The revival period will be same as the revival period of the Base Policy to which the Rider has been attached. The revival will be subject to our underwriting guidelines and payment of all outstanding premiums without any interest. If the Rider is not revived along with the Base Plan, the Rider would be deemed Surrendered and revival of such surrendered Rider will not be allowed at a later stage. However, one or more of the benefit options within the rider can be added anytime during remaining premium payment term, provided the Base Plan is in-force and premiums will be applicable based on attained age of Life Assured. This addition will be subject to underwriting guidelines of the company. ")

**Response truncated**
{
    "answer": "surrender benefit will be payable in following manner: For Regular Pay Policies, no benefit is payable on surrender of the Rider and For Limited Pay policies, we will",
    "score": 13.230949401855469
}

Payload 3 for answer near to middle:
Payload 2 **for answer near to middle of context and response is truncated.**
{"qas": "What happens if I surrender my Rider",
"context": "FAQ’s \n**What happens if I surrender my Rider? We advise you to continue your Rider for the complete Rider Term. However, in case if you still decide to surrender your Rider, surrender benefit will be payable in following manner: For Regular Pay Policies, no benefit is payable on surrender of the Rider and For Limited Pay policies, we will pay the Unexpired Risk Premium Value (URPV) which is computed as: URPV = 70% * ( Total Rider Premiums Paid / Total Premiums Payable over the Term) * (Outstanding Rider Term/Rider Term) * Total Rider Premium Paid (For the purpose of computation of URPV, the rider premiums shall exclude the underwriting extra premiums, any loadings for modal premiums and taxes.) The Rider will terminate on payment of this benefit.** What if I am not happy with the Rider after buying it? (Free look Cancellation) If you are not satisfied with any of the Terms and Conditions of the Rider, you may return the Rider document along with a letter stating the reasons for disagreement to us within 15 days or 30 days (in case of an electronic Policy or if purchased through Distance Marketing mode) from the date of receipt of the Rider document. On cancellation of the Rider within the free look period, we will return the Rider Premium paid under the Rider (including taxes) subject to the deduction of: • Proportionate risk premium (including taxes) and • Expense incurred by us for medical examination (if any) and stamp duty The Rider will terminate on payment of this amount and all rights, benefits and interests under this Rider will stand extinguished. On cancellation of the Base Plan, the Rider will also stand cancelled. What is Distance Marketing? Distance Marketing includes every activity of solicitation (including lead generation) and sale of insurance products through the following modes: (i) Voice mode, which includes telephone-calling (ii) Short Messaging service (SMS) (iii) Electronic mode which includes e-mail, internet and interactive television (DTH) (iv) Physical mode which includes direct postal mail and newspaper & magazine inserts and (v) Solicitation through any means of communication other than in person. What if I missed my premium due date? (Grace period) You are advised to pay premiums on or before the Premium due date to continue enjoying the benefits of this Rider. However, in case you are unable to do so, you have a Grace Period after the premium due date within which you can pay the due premium. Grace Period under this Rider will be same as applicable to the Base Policy. If any premium remains unpaid after the expiry of the Grace Period, the Rider will lapse, and the cover will cease to exist. The Rider will be in force during the Grace Period. In case of contingent event occurs during the grace period, benefit payable will be reduced by the level of Outstanding Instalment Premium (1) (including taxes) as at the date of occurrence of the event. (Outstanding Instalment Premium in the above case is the due instalment premium(s) that were due but unpaid before the death of the Life Insured.) What happens if I stop paying the due premiums? On non-payment of any due premiums within the grace period, the Rider will lapse, and all the benefits will cease to exist. No Benefit shall be payable for lapsed Rider under Regular Pay mode. In case of Limited Pay mode, Unexpired Risk Premium Value (if any) would be payable as Lapse Benefit under the following circumstances whichever is earlier: • The Policyholder voluntarily Surrenders the rider; or • The Life Assured dies; or • The Life Assured survives to the end of the revival period. The Unexpired Risk Premium Value (URPV) is computed as: URPV = 70% * ( Total Rider Premiums Paid / Total Premiums Payable over the Term) * (Outstanding Rider Term/Rider Term) * Total Rider Premium Paid (For the purpose of computation of URPV, the rider premiums shall exclude the underwriting extra premiums, any loadings for modal premiums and taxes.) The Rider will terminate on payment of this benefit. How can I revive my Rider? If your Rider has lapsed, you may revive the Rider along with the Base Policy. The revival period will be same as the revival period of the Base Policy to which the Rider has been attached. The revival will be subject to our underwriting guidelines and payment of all outstanding premiums without any interest. If the Rider is not revived along with the Base Plan, the Rider would be deemed Surrendered and revival of such surrendered Rider will not be allowed at a later stage. However, one or more of the benefit options within the rider can be added anytime during remaining premium payment term, provided the Base Plan is in-force and premiums will be applicable based on attained age of Life Assured. This addition will be subject to underwriting guidelines of the company. "}

Response complete :
{
    "answer": "surrender benefit will be payable in following manner: For Regular Pay Policies, no benefit is payable on surrender of the Rider and For Limited Pay policies, we will pay the Unexpired Risk Premium Value (URPV) which is computed as: URPV = 70% * ( Total Rider Premiums Paid / Total Premiums Payable over the Term) * (Outstanding Rider Term/Rider Term) * Total Rider Premium Paid (For the purpose of computation of URPV, the rider premiums shall exclude the underwriting extra premiums, any loadings for modal premiums and taxes.) The Rider will terminate on payment of this benefit.",
    "score": 9.938078880310059
}

**Comment by brandenchan** [comment]
So there could be a few different things at play here. 

1) I'm not sure which model you're using, but if it was trained on Squad, it is maybe quite challenging for the model generally to extract longer answers like the one that you have in your example. The answers in the Squad dataset are on average only 10 words long. Also, in Squad, answers more often come at the beginning of passages rather than at the end. This might partially explain why your model does better when the answer is at the beginning of the document.

2) Another angle into this is to do with the sliding window used in QA systems. Long contexts, like the ones you've shown, are split into smaller, overlapping passages. This is so that they can be processed by the transformer models which are limited in the length of their input. The size of this input is set by a max_seq_len parameter. Models cannot return answers that are longer than max_seq_len, and often they are constrained to return answers that are significantly shorter. If you are using a FARM QAInferencer, the default max_seq_len is 256. You could try increasing this to 384 and seeing if that helps.

Let us know if this helps or not!

**Comment by brandenchan** [comment]
Closing this for now. Feel free to reopen if you have any questions or updates!
