### ISSUE TITLE
Percentage of masked tokens in LM task

### ISSUE THREAD

**Issue by pashok3d** [deepset-ai/FARM#610]
**Question**
How can I define the probability of masking each token for LM task?

**Additional context**
As far as I know, the probability of masking each token for the LM task is 0.15. Is there a way to change it?

**Comment by Timoeller** [comment]
Hey thanks for using FARM. This feature is actually annoyingly hidden from the user.

You can set the masked_lm_prob parameter inside the mask_random_words() function used [here in FARM](https://github.com/deepset-ai/FARM/blob/78fb5cfb02cdb38f01b66d67f9ab640e6da4e79b/farm/data_handler/input_features.py#L266) or depending on your finetuning style a little bit below the linked lined.

If you want to extent FARM by making this an optional Parameter of the BertStyleLMProcessor Class we are more than happy to accept a PR.

**Comment by Timoeller** [comment]
Could you resolve your issue with the parameter I showed you? If so please close the issue (or even create a PR with your solution. Would be happy to include it if it is simple).

**Comment by pashok3d** [comment]
#630

**Comment by Timoeller** [comment]
Thanks for implementing the functionality. Great PR that I could just merge as is!
