### ISSUE TITLE
Inference Benchmarks of QA models are off 

### ISSUE THREAD

**Issue by tholor** [deepset-ai/FARM#611]
**Describe the bug**
EM and F1 are significantly low when running the [reader benchmarks](https://github.com/deepset-ai/haystack/blob/add_cml_benchmarks/test/benchmarks/reader.py) in Haystack.

Latest Master
|    |       EM |      f1 |   top_n_accuracy |   top_n |   reader_time |   seconds_per_query |   passages_per_second | reader                         | error   |
|---:|---------:|--------:|-----------------:|--------:|--------------:|--------------------:|----------------------:|:-------------------------------|:--------|
|  0 | 0.323024 | 0.37967 |          0.95584 |       5 |       123.854 |           0.0104377 |               99.7142 | deepset/bert-base-cased-squad2 |         |

FARM 0.4.9
|    |       EM |       f1 |   top_n_accuracy |   top_n |   reader_time |   seconds_per_query |   passages_per_second | reader                      | error   |
|---:|---------:|---------:|-----------------:|--------:|--------------:|--------------------:|----------------------:|:----------------------------|:--------|
|  0 | 0.758975 | 0.806799 |         0.967133 |       5 |       135.263 |           0.0113992 |               91.3039 | deepset/roberta-base-squad2 |         |

However, it doesn't seem to be any of the latest changes as already with this commit I get bad results.

FARM @ dac388aa00eb63ad12452f97e40f51a218110b90 (Oct 21) 
|    |       EM |       f1 |   top_n_accuracy |   top_n |   reader_time |   seconds_per_query |   passages_per_second | reader                      | error   |
|---:|---------:|---------:|-----------------:|--------:|--------------:|--------------------:|----------------------:|:----------------------------|:--------|
|  0 | 0.330777 | 0.383186 |         0.963341 |       5 |       134.598 |           0.0113432 |               91.7545 | deepset/roberta-base-squad2 |         |

**Expected behavior**
Similar EM and F1

**Additional context**
I tried to switch transformers from 3.3.1 back to 3.1.0 (as it was used in FARM 0.4.9) => no effect

**To Reproduce**
Run the above benchmark script from the haystack branch

**System:**
 - OS: Ubuntu 18.04 
 - GPU/CPU: GPU
 - FARM version: latest master  / 0.4.9

**Comment by tholor** [comment]
Similar for 2ab42d2

**Comment by brandenchan** [comment]
Results are high again at c106bca (Oct 4)

**Comment by brandenchan** [comment]
Results are high at 7c38fc5 (Oct 14)

**Comment by brandenchan** [comment]
Results are high at  b9dbd7d (Oct 15)

**Comment by brandenchan** [comment]
The problematic commit is 9055094 (Oct 16)

**Comment by brandenchan** [comment]
On 9055094, running the benchmark script using Reader.eval_on_file( ) instead of Reader.eval( ) gives the following results
{'EM': 0.7511159774277774, 'f1': 0.7991178464867065, 'top_n_accuracy': 0.9633622504842921}

**Comment by tholor** [comment]
This seemed rather like a FARM related bug as performance changed between FARM versions, dear @Timoeller  ;)

**Comment by brandenchan** [comment]
This has been addressed by [a new PR](https://github.com/deepset-ai/haystack/pull/531) in Haystack which corrects the creation of no_answer sample dictionaries in FARMReader.eval( ). In future we would like to fix this problem also on the FARM preprocessing side by filtering out empty string spans.

**Comment by tholor** [comment]
Just to clarify: we want to add a check in FARM preprocessing that identifies labels with: 
- empty string
- start / end = 0
as no_answer and not as regular span labels.

**Comment by tholor** [comment]
Might be related to #614

**Comment by brandenchan** [comment]
Span labels with an empty string are now checked for and removed in FARM preprocessing #635

**Comment by tholor** [comment]
Closing by #635.
