### ISSUE TITLE
Problems running NER example inside of Docker Container 

### ISSUE THREAD

**Issue by leonardomra** [deepset-ai/FARM#612]
**Describe the bug**
When I run examples/ner.py inside of Docker Container, the program paralyzes when processing `processor = NERProcessor(tokenizer=tokenizer, max_seq_len=128, data_dir=Path("./data/conll03-de"), delimiter=" ", metric="seq_f1", label_list=ner_labels)`. Outside of container, the code run just fine.

**Error message**
Stops at `Preprocessing Dataset ../data/conll03-de/dev.txt:   9%|██▎                      | 266/2867 [00:13<00:15, 163.36 Dicts/s]` without displaying any kind of error.

**Expected behavior**
Running the code outside of the container runs just fine. Same behavior is expected inside of container.

**Additional context**
I have tried different Dockerfile configurations, but without success. It's hard to debug, because the same code performs differently inside and outside of a docker container.

Example of a tested dockerfile config:
```
FROM ubuntu:18.04
RUN apt-get update && apt-get upgrade -y && apt-get clean
RUN apt-get install -y curl make wget git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex bison gettext texinfo ncurses-dev autoconf rsync
RUN apt-get install -y curl python3.6 python3.6-dev python3.6-distutils
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
RUN update-alternatives --set python /usr/bin/python3.6
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py --force-reinstall && \
    rm get-pip.py
...
```

**To Reproduce**
Just run examples/ner.py

**System:**
 - OS: Ubuntu & WSL3 Ubuntu 
 - GPU/CPU: CPU only
 - FARM version: 0.4.9

**Comment by Timoeller** [comment]
Hey @leonardomra thanks for posting this issue. It might be related to multiprocessing inside a docker container.

Could you try setting `max_processes=1` as a parameter of the DataSilo and report back here, please?

**Comment by leonardomra** [comment]
Hi @Timoeller , thanks for the fast feedback. It works well now!

**Comment by Timoeller** [comment]
Nice, thanks for getting back. Closing now.
