### ISSUE TITLE
Do you open source the code of farm-inference-ui?

### ISSUE THREAD

**Issue by demarant** [deepset-ai/FARM#620]
**Question**
We are looking for the source code of the docker image deepset/farm-inference-ui that demonstrates the FARM capabilities. 
Is the source code already available somewhere? if not.
Could you make it availble on github under same open-source license?

**Additional context**
Motivation: It would facilitate other developers to bootstrap a similar UI-app, demonstrate and accelerate the adoption of the haystack framework in other NLP-projects.

**Comment by avoinea** [comment]
Would be cool to also open-source https://hub.docker.com/r/deepset/haystack-demo-ui

**Comment by tholor** [comment]
Hey @demarant, 

We currently don't plan to open-source the code base for those two UIs. The main reason: If you publish it, you need to maintain and support it. We currently don't have the capacity to do this for these two "side components" and rather want to focus on FARM and Haystack. There will be the option in [Haystack Hub](https://haystack.deepset.ai/pricing/pricing), to do conduct fast PoCs and demonstrate results in a simple UI. 
If you want to build something custom, I would probably go for streamlit (https://www.streamlit.io/). For demonstrating a prototype this should be enough and the implementation is super quick.

**Comment by demarant** [comment]
@tholor 
thanks for coming back. 

We understand your choice.

if it is openly available, any other company / organisation can fork it and continue to develop it. 
Of course, the ultimate choice is yours, and your business needs to find a sweet spot.

In this case, maybe you can just make the code available as a one time off, a zip-archive? and clearly indicate that you don't accept PR or not releasable. It will help us a lot, of course we can try to replicate it with react/nodejs...and do our own thing.

**Comment by tholor** [comment]
Sorry, I somehow missed your answer here. 

We can share the FARM Demo UI code as a one-time thing if you need it. Please reach out via email to us.
For Haystack, we will deprecate the existing demo UI soon why we don't think there's a big value in sharing it. The plan is to have a simple streamlit replacement (I already saw your comment there, too) plus an option within Haystack Hub to showcase and test your search pipelines.

**Comment by Timoeller** [comment]
Seems fixed, closing now. Feel free to reopen

**Comment by thenewera-ru** [comment]
> Sorry, I somehow missed your answer here.
> 
> We can share the FARM Demo UI code as a one-time thing if you need it. Please reach out via email to us.
> For Haystack, we will deprecate the existing demo UI soon why we don't think there's a big value in sharing it. The plan is to have a simple streamlit replacement (I already saw your comment there, too) plus an option within Haystack Hub to showcase and test your search pipelines.

May I also join the discussion :-) We also use `FARM` framework in our pipelines and right now we're required to add additional UI `checkbox` whether or not using the `fancy-preprocessing` (like replacing smiles with contextual meaning or simply remove them, etc...). 

So, if one-time UI code sharing as a zip-archive is possible, it would be so cool 😎 . As @demarant mentioned the UI added code by the community could be reused and improved in the already existing FARM models, couldn't it?

Best regards
