### ISSUE TITLE
OpenSource Farm React UI

### ISSUE THREAD

**Issue by avoinea** [deepset-ai/FARM#621]
**Question**
Is it possible to open-source the React App within this docker image `deepset/farm-inference-ui`

**Comment by Timoeller** [comment]
Is something happening? : ) a similar issue just got opened 5 minutes ago #620

**Comment by avoinea** [comment]
> Is something happening? : ) a similar issue just got opened 5 minutes ago #620

:smile: Ha, bad coordination, me and @demarant are in the same team, playing with your awesome products.
