### ISSUE TITLE
Failed to run "docker-compose up" for API + UI

### ISSUE THREAD

**Issue by jpzhangvincent** [deepset-ai/FARM#622]
**Question**
I followed the documentation to launch the docker for the API and UI. But it seemed it failed at the step when loading the language model. Do you have any thoughts on how to debug or any workaround? Thanks for the amazing open-source project!

**Additional context**

<img width="1087" alt="Screen Shot 2020-11-10 at 6 13 59 PM" src="https://user-images.githubusercontent.com/7220686/98757635-d4085000-2381-11eb-9484-4368e74b53b6.png">

**Comment by Timoeller** [comment]
Hey @jpzhangvincent  thanks for using FARM. The Error code 137 means most likely you do not have enough memory. The error happens when loading the bert-english-qa-large model, which is about 2GB large. So it is not an issue we can solve on FARM side.
Can you allocate more memory to the instance where you run the docker compose up?

**Comment by jpzhangvincent** [comment]
> Hey @jpzhangvincent thanks for using FARM. The Error code 137 means most likely you do not have enough memory. The error happens when loading the bert-english-qa-large model, which is about 2GB large. So it is not an issue we can solve on FARM side.
> Can you allocate more memory to the instance where you run the docker compose up?

Do you mean the docker container or my laptop? Is it something I can configure in the docker yaml file? It would be good to document the caveat in the documentation.

**Comment by Timoeller** [comment]
When googling for this error or docker memory limits it say docker by default uses all the RAM your machine offers. So I suspect it is related to your machine. How much do you have?

**Comment by Timoeller** [comment]
Seems to be a hardware issue. Closing now, feel free to reopen any time.
