### ISSUE TITLE
converting ORQA/REALM tensorflow checkpoints to pytorch checkpoints

### ISSUE THREAD

**Issue by mchari** [deepset-ai/FARM#626]
I would like to use ORQA/REALM pre-training model checkpoints to load into DPR (using the EmbeddedRetriever).

I see the following statement in farm/convert_tf_checkpoint_to_pytorch.py :
from farm.modeling.bert.modeling import (
    BertConfig,
    BertForPreTraining,
    load_tf_weights_in_bert,
)

I find all of the above symbols in transformers.modeling_bert.

**Comment by Timoeller** [comment]
Hey @mchari the functionality you suggest would be very convenient. One quick question: what do you mean by "I find all of the above symbols in transformers.modeling_bert."? Do you mean that the conversion should be possible?

I think the problem comes from locating the right model files in the open sourced ORQA/Realm files. If you can find the retrieval weights (they should be bert style) in the data, you should be able to convert them to pytorch and then load them similar to DPR retrievers.

Please have a look at https://github.com/deepset-ai/haystack/issues/312 where @antoniolanza1996 already looked into which files should include the retrieval weights.

**Comment by mchari** [comment]
@Timoeller ,  in the import statement above, _farm.modeling.bert.modeling_ needs to be replaced by transformers.modeling_bert, I think.

Yes, I started this conversion after following the discussion in #312. 
 I am trying out conversion of checkpoint in **https://console.cloud.google.com/storage/browser/orqa-data/ict**. Haven't quite got it working. Gives me weird errors related to the developer's internal folder!
File "/gstore/home/madabhuc/hayEnv/env/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 409, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: /cns/lu-d/home/lumiere/public/models/kentonl/ict-20181220-final/6202369/1-mask_rate=0.9/export/tf_hub/1558813192/ict/encoded; No such file or directory

**Comment by Timoeller** [comment]
K understood, fixed in #631

About the conversion of the checkpoints in the gcp bucket. If you find a solution or hit a barrier please let us know here or in haystack. Maybe antoniolanza or me can help.

**Comment by mchari** [comment]
@timoeller, thanks for your offer to help. Appreciate it.

I downloaded the checkpoint from 
https://console.cloud.google.com/storage/browser/orqa-data/ict/encoded/

This is how I am running the conversion script 
python convert_tf_checkpoint_to_pytorch.py \
       --tf_checkpoint_path="/gstore/home/madabhuc/encode.ckpt.data-00000-of-00001" \
       --bert_config_file="/gstore/home/madabhuc/hayEnv/runs/bert_config.json" \
       --pytorch_dump_path="/gstore/home/madabhuc/hayEnv/pytorch"

I get an error : 
2020-11-16 10:51:07.524375: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /gstore/home/madabhuc/encode.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/gstore/home/madabhuc/.local/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))

I also tried convert_bert_original_tf2_checkpoint_to_pytorch.py from huggingface, in case there is a tensorflow version issue, but I got the same error message.

**Comment by Timoeller** [comment]
Hey mchari, why are you using the ORQA files instead of REALM? I think REALM is more recent and also much more performant. You could extract question and document encoders there.

About the REALM checkpoint locations I will cite antoniolanza1996:
- REALM document encoder could be downloaded from realm-data/cc_news_pretrained/embedder/
- REALM question encoder (and REALM reader encoder - both finetuned on NQ) should be extracted from realm-data/orqa_nq_model_from_realm/export/best_default/checkpoint/

**Comment by mchari** [comment]
Yes, we downloaded the REALM checkpoints last night. It is making its way to a folder that I can access...
Will update here later today...

**Comment by mchari** [comment]
I set
--tf_checkpoint_path="./cc_news_pretrained/embedder/encoded/encoded.ckpt" and I see the following messages :  
Loading TF weight block_emb with shape [13353718, 128]
Skipping block_emb

Building PyTorch model from configuration: BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

Traceback (most recent call last):
  File "convert_tf_checkpoint_to_pytorch.py", line 78, in <module>
    args.tf_checkpoint_path, args.bert_config_file, args.pytorch_dump_path
  File "convert_tf_checkpoint_to_pytorch.py", line 44, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_bert(model, config, tf_checkpoint_path)
  File "/gstore/home/madabhuc/hayEnv/env/lib/python3.6/site-packages/transformers/modeling_bert.py", line 155, in load_tf_weights_in_bert
    pointer.shape == array.shape
  File "/gstore/home/madabhuc/hayEnv/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'BertForPreTraining' object has no attribute 'shape'


Following the suggestion in https://github.com/huggingface/transformers/issues/393, I I hacked transformers/src/transformers/modeling_bert.py, and I now see the following : 
Converting TensorFlow checkpoint from ./cc_news_pretrained/embedder/encoded/encoded.ckpt
Loading TF weight block_emb with shape [13353718, 128]
Skipping block_emb
Initialize PyTorch weight ['block_emb']

Building PyTorch model from configuration: BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

Save PyTorch model to /gstore/home/madabhuc/hayEnv/pytorch/pytorch.bin

Skipping and intializing block_emb tells me that I have lost the weights info from the checkpoint. Don't believe this is correct.

**Comment by Timoeller** [comment]
Ok, difficult to judge what actually happened. Still, this looks like progress : )

I see a couple of options to evaluate:
1. How about you create some sample question and doc embeddings from NQ (maybe use passages from the 100 words version of NQ that DPR used) with your extracted REALM encoders and with vanilla BERT and compare the similarity. The REALM encoders should produce more similar embeddings for related question+document pairs than vanilla BERT... 
2. Use the encoders and stick them into DPR for evaluation. You can do so in haystack in the [Evaluation tutorial](https://github.com/deepset-ai/haystack/blob/master/tutorials/Tutorial5_Evaluation.py#L68). I pointed you to the code where you can exchange the default fb dpr encoders with your ones.

Do you think these are good ideas? Do you see alternatives? If you need help with haystack evaluation let me know and we have a short call. 
Getting REALM to work would be amazing!

**Comment by mchari** [comment]
I confirmed from transformers/modeling_bert.py that the weights actually did get copied !

when I use the pytorch.bin file that was generated from converting the REALM embedder model, I get errors:
File "/gstore/home/madabhuc/.local/lib/python3.6/site-packages/haystack/retriever/dense.py", line 77, in __init__
    self.passage_encoder = DPRContextEncoder.from_pretrained(passage_embedding_model).to(self.device)
File "/gstore/home/madabhuc/.local/lib/python3.6/site-packages/transformers/modeling_utils.py", line 784, in from_pretrained
    **kwargs,
  File "/gstore/home/madabhuc/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 311, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/gstore/home/madabhuc/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 354, in get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/gstore/home/madabhuc/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 436, in _dict_from_json_file
    text = reader.read()
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

**Comment by mchari** [comment]
When I try to convert the question + reader encoder model orqa_nq_model_from_realm/export/best_default/checkpoint/model.ckpt-300000, I get 
File "/gstore/home/madabhuc/hayEnv/env/lib/python3.6/site-packages/transformers/modeling_bert.py", line 135, in load_tf_weights_in_bert
    pointer = getattr(pointer, "bias")
  File "/gstore/home/madabhuc/hayEnv/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'BertForPreTraining' object has no attribute 'bias'

**Comment by Timoeller** [comment]
Hey mchari, please send me a message to timo.moeller (at) deepset.ai so we can arrange a call.

Did you solve the `UnicodeDecodeError:`? Seems like your config `cls._dict_from_json_file(resolved_config_file)` is malformed. Please have a look at its content.

I dont understand what you mean by "question + reader encoder". Do you mean by "reader encoder" the document encoder or do you mean an extractive QA model?

**Comment by mchari** [comment]
What I meant by "Question + reader encoder" is , from your statement above :
>REALM question encoder (and REALM reader encoder - both finetuned on NQ) should be extracted from realm->data/orqa_nq_model_from_realm/export/best_default/checkpoint/

**Comment by Timoeller** [comment]
Hey, lets close this thread and post updates in https://github.com/deepset-ai/haystack/issues/312 instead
