### ISSUE TITLE
How to quantize models?

### ISSUE THREAD

**Issue by skiran252** [deepset-ai/FARM#627]
**Question**
Put your question here
How to quantize a Roberta model 
**Additional context**
I tried conversion script in the adaptive model and could convert to onnx model but when i tried to use quantize and fp16 params i got error saying folder is not empy
Add any other context or screenshots about the question (optional).

**Comment by Timoeller** [comment]
Hey @skiran252 thanks for using the QA models and trying to tweak the speed performance.
So you want to use fp16 during QA inference, right?

Have you tried using amp in our [initialize_model](https://github.com/deepset-ai/FARM/blob/master/farm/modeling/optimization.py#L58) function. There you can use native pytorch amp which supports fp16:
```
:param use_amp: Optimization level of nvidia's automatic mixed precision (AMP). 
The higher the level, the faster the model.
Options:
                    "O0" (Normal FP32 training)
                    "O1" (Mixed Precision => Recommended)
                    "O2" (Almost FP16)
                    "O3" (Pure FP16).
                    See details on: https://nvidia.github.io/apex/amp.html

**Comment by skiran252** [comment]
> Hey @skiran252 thanks for using the QA models and trying to tweak the speed performance.
> So you want to use fp16 during QA inference, right?
> 
> Have you tried using amp in our [initialize_model](https://github.com/deepset-ai/FARM/blob/master/farm/modeling/optimization.py#L58) function. There you can use native pytorch amp which supports fp16:
> 
> ```
> :param use_amp: Optimization level of nvidia's automatic mixed precision (AMP). 
> The higher the level, the faster the model.
> Options:
>                     "O0" (Normal FP32 training)
>                     "O1" (Mixed Precision => Recommended)
>                     "O2" (Almost FP16)
>                     "O3" (Pure FP16).
>                     See details on: https://nvidia.github.io/apex/amp.html
> ```

so quantization does not work on all models is it

**Comment by Timoeller** [comment]
IF you mean by model the language models like bert, roberta, elctra the fp16 should work on all models.

If you mean frameworks (pytorch, ONNX) by models I cannot tell since. You would need to checkout ONNX and how to use fp16 there. Could you please report back if you find insights?

**Comment by Timoeller** [comment]
Issue seems fixed, closing now, feel free to reopen
