### ISSUE TITLE
Getting data directly into FARM

### ISSUE THREAD

**Issue by Reza2311** [deepset-ai/FARM#632]
**Question**
How to get data directly into FARM i/o using intermediate files?

**Comment by Timoeller** [comment]
I guess you mean like an API?

We have a docker which exposes an API, see https://github.com/deepset-ai/FARM#3-showcase-your-models-api--ui

**Comment by Reza2311** [comment]
Sorry I made a small mistake in my last question. I think that makes confusion. My question is: 

How to get data directly into FARM without using intermediate files?

**Comment by Timoeller** [comment]
Hey, so my problem comes from "intermediate files". What do you mean by that. 
Maybe explain the use case what you need it for.

**Comment by Timoeller** [comment]
Issue seems stale. Closing now, feel free to reopen.
