### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by ftesser** [deepset-ai/FARM#636]
**Describe the bug**
After installing farm and its dependencies on Windows, running the tests produce the error below.
This does not happen on Linux OS.

**Error message**
```
ImportError while loading conftest 'C:\builds\fairmat\dev\FARM\test\conftest.py'.
conftest.py:7: in <module>
    from farm.modeling.adaptive_model import AdaptiveModel
..\venv\lib\site-packages\farm\modeling\adaptive_model.py:17: in <module>
    from farm.modeling.prediction_head import PredictionHead, pick_single_fn
..\venv\lib\site-packages\farm\modeling\prediction_head.py:14: in <module>
    from torch.distributed import all_gather
E   ImportError: cannot import name 'all_gather' from 'torch.distributed' (c:\builds\fairmat\dev\farm\venv\lib\site-packages\torch\distributed\__init__.py)
```

**Expected behavior**
Successfully run the tests also on Windows.

**Additional context**
- pytorch version: 1.6.0

Looking to `torch.distributed.__init__`  I have noticed that `all_gather` probably is imported only for Linux and MacOS:   

```python
def is_available():
    """
    Returns ``True`` if the distributed package is available. Otherwise,
    ``torch.distributed`` does not expose any other APIs. Currently,
    ``torch.distributed`` is available on Linux and MacOS. Set
    ``USE_DISTRIBUTED=1`` to enable it when building PyTorch from source.
    Currently, the default value is ``USE_DISTRIBUTED=1`` for Linux and
    ``USE_DISTRIBUTED=0`` for MacOS.
    """
    return hasattr(torch._C, "_c10d_init")
```

**To Reproduce**

```bash
cd test && pytest
```
**System:**
 - OS: Windows
 - GPU/CPU: CPU
 - FARM version: 0.5.0

**Comment by Timoeller** [comment]
This would normally be quite difficult to debug, but I do not find any usage of all_gather in our code currently.

@tholor could you verify this, since you added this import during the MultiGPU DDP support for DPR and if it is needed.

**Comment by ftesser** [comment]
Thanks @Timoeller, in the meantime I can run the tests without the import line `from torch.distributed import all_gather` in `farm\modeling\prediction_head.py`.

**Comment by Timoeller** [comment]
I added a potential solution to #637

**Comment by Timoeller** [comment]
#637 merged.

Will also update to newer pytorch soon, which should reduce errors related to DDP as well.
