### ISSUE TITLE
Could you please turn on auto-build on dockerhub for deepset images?

### ISSUE THREAD

**Issue by demarant** [deepset-ai/FARM#640]
**Question**
Could you please configure autobuild on docker hub?
See
https://docs.docker.com/docker-hub/builds/#tag-and-branch-builds

**Additional context**
I noticed that the tags on docker hub for the images created by you are behind, they seem to be pushed manually.
e.g. for deepset/farm-inference-api, the latest docker image is v0.4.3 from 7months ago.
https://hub.docker.com/r/deepset/farm-inference-api/tags?page=1&ordering=last_updated
It would be very useful for all, if you could configure auto-build on tags, very simple configuration. This way when you do a new release in github (say v0.6.0), docker would automatically build a new docker version automatically, with no extra work on your side.
this question/feature request, is also relevant for haystack images of course.

**Comment by tholor** [comment]
Yep, good point! Just enabled automatic builds for the major images. I don't have time at the moment to configure them for `deepset/farm-inference-ai:base-models-x.x.x` (they need the models to be baked in), but the rest should be fine...
