### ISSUE TITLE
What's the model structure of NER ?

### ISSUE THREAD

**Issue by JiangYanting** [deepset-ai/FARM#642]
**Question**
Hello, I try to use the ner.py to do Named Entity Recognition on my own dataset. Could I ask you what's the model structure of NER ? May be bert + CRF？

**Additional context**
Add any other context or screenshots about the question (optional).

**Comment by Timoeller** [comment]
Hey @JiangYanting thanks for bringing this up. We currently do not have a CRF on top of Bert. It only uses a linear NN layer on each token and uses the first token of a word (if the word is split into multie tokens) for the prediction the NER tag. Sorry, I know that is quite boring : (

We tried alternatives, especially adding a CRF on top but did not find meaningful performance improvements. See https://github.com/deepset-ai/FARM/issues/40 for more details.

**Comment by JiangYanting** [comment]
> 
> 
> Hey @JiangYanting thanks for bringing this up. We currently do not have a CRF on top of Bert. It only uses a linear NN layer on each token and uses the first token of a word (if the word is split into multie tokens) for the prediction the NER tag. Sorry, I know that is quite boring : (
> 
> We tried alternatives, especially adding a CRF on top but did not find meaningful performance improvements. See #40 for more details.

I've got it ~ thank you!
