### ISSUE TITLE
Refactor Processor Stages in FARM

### ISSUE THREAD

**Issue by tholor** [deepset-ai/FARM#645]
We currently have dict_to_samples and samples_to_features as two very separate stages.
For some use cases (e.g. fast tokenizers) this is not ideal. Let's redesign this crucial part in FARM.

- [x] @Timoeller  implement "dataset_from_dicts" and do basic cleaning for squad => "boilerplate for dataset_from_dicts for other processors",  "get rid of dict_to_samples etc. and just call dataset_from_dicts"
- [x] @brandenchan : refactor text classification
- [x] @tholor : refactor lm finetuning
- [x] @Timoeller: identify speed bottlenecks beside tokenization
- [x] @tholor @Timoeller @brandenchan : optimize those bottlenecks (vectorization / batching)
- [x] @brandenchan refactor ner
- [x] @brandenchan benchmark ner
- [x] split NQ and SQuAD processors in a cleaner way

**Comment by Timoeller** [comment]
Fixed with #649
