### ISSUE TITLE
Dependency conflict with latest mlflow 

### ISSUE THREAD

**Issue by Aslizy** [deepset-ai/FARM#647]
**Is your feature request related to a problem or particular use case?**
Hi, my project is using the latest version of mlflow==1.12.1. I want to use farm-haystack ==0.5.0, of which it required farm==0.5.0. However farm==0.5.0 (and also previous versions) requires mlflow==1.0.0, which is a quite old version. Thus, I have dependency conflicts. I wonder is there a reason for such an elder version of mlflow, and is it possible to enlarge the mlflow accepted version. 

**Describe the solution you'd like**
Update or widen the mlflow accepted dependency in the farm requirement.txt 

**Additional context**

**Comment by tholor** [comment]
Hey @Aslizy , 
Thanks for bringing this up. The pinned mlflow version is indeed quite old. We'll test if there are any compatibility issues with 1.12.1 and if not, upgrade.

**Comment by julian-risch** [comment]
Hi @Aslizy , I checked that mlflow==1.12.1 works with both FARM 0.5.0 and the latest 0.6.1. All tests passed successfully. So you are good to go. I will update the FARM requirements.txt accordingly and then close this issue.
