### ISSUE TITLE
lm_finetuning.py is getting stuck on my machine

### ISSUE THREAD

**Issue by sajastu** [deepset-ai/FARM#652]
Thanks for the amazing library! 

I'm trying to run `lm_finetuning.py` (unmodified with `lm_finetune_nips` dataset in the base code. Everything goes well, until it gets to the training point, after doing pre-processing on the dataset. However, it gets stuck at the beginning of the training point, and even the processes on GPUs became Zombie (i.e., I'm not able to kill them in the normal way). I'm totally puzzled about what should be wrong in the process as I followed instructions to set the package up. 

I'm using python 3.6.8, Cuda toolkit 10.1, and transformers 3.3.1

**Comment by tholor** [comment]
Hey @sajastu, 

Happy to investigate this together. Can you please give some more details on your environment? It would be helpful to understand: 
- OS
- FARM version
- Pytorch version
- Number of CPU cores
- Running in container?

Thanks!

**Comment by sajastu** [comment]
Hey @tholor, 

Thanks for your quick response. I'm actually running the example on GPU. I modified the `lm_finetuning.py` a bit --setting `use_cuda=True` The requested fields are as bellow:

- OS: Linux
- FARM version: farm-0.5.0
- Pytorch version: 1.6
- Number of CPU cores: Not using CPU, but GPU cores are 2. 
- Running in container? I'm using the source for initialization, and then running `pip install -r requirements.txt`. Thereafter, I'm getting to `examples/` and running: `python lm_finetuning.py`

**Comment by tholor** [comment]
Hey @sajastu , 

Just a quick update: we didn't forget you here, but decided to actually refactor the whole lm_finetuning preprocessing (see #659 ). The issue should hopefully be resolved after this refactoring plus it should be significantly faster (we currently measure 5-10x speed improvements). We will keep you posted!

**Comment by sajastu** [comment]
Hey @tholor,

Thanks for the update, and your considerations regarding fixing this issue. I really appreciate that :). Will try my experiments soon.

**Comment by Timoeller** [comment]
Hey, we updated the processing stages in #649 on current master
Could you try running your code again (dont forget to update to transformers 3.5.1)

**Comment by Timoeller** [comment]
Hey @sajastu could you test our new processing stages?

**Comment by Timoeller** [comment]
Seems fixed, closing now, feel free to reopen.
