### ISSUE TITLE
documentation is outdated 

### ISSUE THREAD

**Issue by sadakmed** [deepset-ai/FARM#654]
documentation is not updated, classes like `processor.TextSimilarityHead` `processor.TextSimilarityProcessor` and `biadaptive_model.BiAdaptiveModel` are not documented.

**Comment by Timoeller** [comment]
Lets also check if the documentation website works.

**Comment by sadakmed** [comment]
> Lets also check if the documentation website works.

@Timoeller  still not

**Comment by Timoeller** [comment]
Ah thanks for checking as well : )

I actually made this note for our engineer branden, so he will look into it. We are working on this issue in the current sprint, so it should be resolved within the next 2 weeks.

**Comment by brandenchan** [comment]
This should be fixed now! Feel free to reopen if you see anything is still missing
