### ISSUE TITLE
Problem with DataSilo and pandas-parser

### ISSUE THREAD

**Issue by naty88** [deepset-ai/FARM#666]
**Question**
I dont' know, if it is a bug or the problem with my code, but I get an Error by calling DataSilo and so the Processor. 
`ValueError: Usecols do not match columns, columns expected but not found: ['text', 'language']`
The problem is, I have the columns "language", where I store my labels. 

**Additional context**
![Screenshot from 2021-01-04 19-26-48](https://user-images.githubusercontent.com/44298164/103566754-e3f46a00-4ec2-11eb-8779-ab2a38c94e75.png)

![Screenshot from 2021-01-04 19-01-50](https://user-images.githubusercontent.com/44298164/103565985-9297ab00-4ec1-11eb-8acd-829f540ecdd6.png)

![Screenshot from 2021-01-04 19-02-43](https://user-images.githubusercontent.com/44298164/103565920-7562dc80-4ec1-11eb-84cb-bd686a0e7cc7.png)

**Comment by stefan-it** [comment]
Hi @naty88 ,

I think you need to specify/adjust the `delimiter` for the `TextClassificationProcessor`. By default it is set to tab:

https://github.com/deepset-ai/FARM/blob/a11ea46a71d708aa48947a640daa30283dd7289c/farm/data_handler/utils.py#L49

But as you're using a comma-separated file, just pass `delimiter=","` as an additional argument, like:

```python
processor = TextClassificationProcessor(tokenizer=tokenizer,
                                            max_seq_len=512, # BERT can only handle sequence lengths of up to 512
                                            data_dir='./', 
                                            label_list=label_list,
                                            label_name="language",
                                            label_column_name='language',
                                            metric=metric,
                                            quote_char='"',
                                            multilabel=True,
                                            delimiter=",",
                                            train_filename='train.csv',
                                            dev_filename=None,
                                            test_filename='test.csv',
                                            dev_split=0.1 # this will extract 10% of the train set to create a dev set
                                            )
```

Hope this helps :hugs:

**Comment by naty88** [comment]
It works!!! Thank you so much!!! :hugs:

**Comment by Timoeller** [comment]
Nice, thanks for fixing this issue so quickly @stefan-it 
closing now
