### ISSUE TITLE
Data preprocessing for finetuning LM

### ISSUE THREAD

**Issue by AhmedIdr** [deepset-ai/FARM#687]
**Question**
Hey, im just wondering how my additional unlabeled data should be preprocessed before using it for the LM finetuning. 
**Additional context**
I am trying to finetune gbert-large, the used preprocessing was unfortunately not mentioned in the original paper or i might have missed it. 
 
Thank you in advance

**Comment by Timoeller** [comment]
Hey @AhmedIdr havent heard of you in a while : )

When you run our [LM finetuning example](https://github.com/deepset-ai/FARM/blob/master/examples/lm_finetuning.py) it will download some sample files - they are one sentence per line and documents are separated by a newline. Hope that helps?

**Comment by AhmedIdr** [comment]
Hey @Timoeller yes just got back lately to working on some NLP stuff :) . I looked at the example but it doesnt help much. I was mainly wondering how was the training data for gbert-large preprocessed cause i wanted to preprocess my additional data in the same way. Im not sure if this the best approach but i didnt want to use my data in its raw form. It is mainly tweets and they sometimes have links, emojis. etc.

**Comment by Timoeller** [comment]
Hey, we did not open source our preprocessing scripts because they is rather hacky and we do not want to offer support for them.

Nevertheless I can send you some code that you can base your work on by mail, just write me there.
