### ISSUE TITLE
How to load local model weights for evaluation using question_answering.py

### ISSUE THREAD

**Issue by snat1505027** [deepset-ai/FARM#696]
**Question**

I want to use the **question_answering.py**  script for inference on SQuAD2.0 dataset. 

So the code snippet mentioned below will be replaced: 

`save_dir = Path("../saved_models/bert-english-qa-tutorial")`
`model.save(save_dir)`
`processor.save(save_dir)`

by this:

`model = QAInferencer.load(my_model_dir, batch_size=40, gpu=True)`

Now, I have my fine-tuned model weights and checkpoints. How can I upload them directly into the model?

**Comment by Timoeller** [comment]
Hey you have to use an Evaluator. Please have a look at this example on how to use it: https://github.com/deepset-ai/FARM/blob/master/examples/evaluation.py#L67

**Comment by snat1505027** [comment]
> Hey you have to use an Evaluator. Please have a look at this example on how to use it: https://github.com/deepset-ai/FARM/blob/master/examples/evaluation.py#L67

Hi, thanks for your reply. 

So, I can only load models of type AdaptiveModel? Can't I use this script to evaluate a custom model (e.g. hugging face model finetuned on SQuAD)?

**Comment by Timoeller** [comment]
Sure, the [line loading the model](https://github.com/deepset-ai/FARM/blob/master/examples/evaluation.py#L114) actually loads a model from the modelhub finetuned on SQuAD, see lang_model = "deepset/roberta-base-squad2"

**Comment by snat1505027** [comment]
> Sure, the [line loading the model](https://github.com/deepset-ai/FARM/blob/master/examples/evaluation.py#L114) actually loads a model from the modelhub finetuned on SQuAD, it loads lang_model = "deepset/roberta-base-squad2"

Thanks again. I have stored a fine-tuned model of distilbert-base-uncased:

```
output_model = 'model_distilbert_base.pth'
def save(model, optimizer):
   torch.save({
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict()
    }, output_model)

save(model, optim)
```

I want to pass a model loaded from my local machine.

```
model = DistilBertForQuestionAnswering.from_pretrained("distilbert-base-uncased")
checkpoint = torch.load(output_model , map_location='cpu')
model.load_state_dict(checkpoint['model_state_dict'])
```
now I want to use this model for the inference stage. But when I try to do it, I get errors for not having some parameters in the model (e.g., language_type).

Thanks in advance.

**Comment by Timoeller** [comment]
Mhh, did you try using standard functions for saving from transformers? There is a `trainer.save_model()` function available in transformers. Your current save method seems rather custom and missing parts...

An alternative is to finetune your model in FARM alltogether. You can also load a distilled model in FARM, see our question answering [example](https://github.com/deepset-ai/FARM/blob/master/examples/question_answering.py).

**Comment by snat1505027** [comment]
Hi again. I am now using the [question_answering.py](https://github.com/deepset-ai/FARM/blob/master/examples/question_answering.py) script for fine-tuning and evaluation. I want to fine-tune t5-base model on SQuAD2.0 dataset using this script. For that, I need to use [T5tokenizer](https://github.com/huggingface/transformers/blob/285c6262a84490270d2f1a1c06ee9ccfc1b60e8f/src/transformers/models/t5/tokenization_t5.py#L64) and T5ForConditionalGeneration from Huggingface's transformers library. 

How can I import those models into the script?

**Comment by Timoeller** [comment]
Sorry, but a T5 model is currently not supported in FARM.
Would you be interested in contributing the support to FARM?

**Comment by snat1505027** [comment]
> Sorry, but a T5 model is currently not supported in FARM.
> Would you be interested in contributing the support to FARM?

I would love to contribute after 1st February. Thanks.

**Comment by Timoeller** [comment]
Cool than ill be closing this issue. When you should start on T5 please open another issue describing what you want to do and if you raise a PR please do so early in the process, so we can help you.
