### ISSUE TITLE
Handling large file in DPR model 

### ISSUE THREAD

**Issue by voidful** [deepset-ai/FARM#730]
In DPR data loading https://github.com/deepset-ai/FARM/blob/5ab5b1620cb51ceb874d4b30c887e377ad1a6e9a/farm/data_handler/utils.py#L186

It read the entire JSON file at once and it would occur memory issue when reading a large file.

**Describe the solution you'd like**
Changing it to support both JSON and jsonl file determent by the input file type.
jsonl format is more suitable for handling large files. 
we can also provide a dpr_to_jsonl for conversion.

**Comment by Timoeller** [comment]
Hey  @voidful seems like a good idea. 
Though just reading from JSONL would not solve the memory issue.
The whole file (weather it is json or jsonl) is loaded into python dicts and then converted into pytorch tensors (by multiple processes).

I see two options:
- For LM pretraining we have a StreamingDataSilo that does not convert the whole dataset at once. I shortly tested it for DPR processing, it does not work out of the box unfortunately. You could try fixing this.
- For training DPR only few/one negative passage is used. You could remove other unused passages from the file and drastically reduce its size. We would highly appreciate this downsampling in our `read_dpr_json` method.

Would any of those solve your issues?

**Comment by voidful** [comment]
> Hey @voidful seems like a good idea.
> Though just reading from JSONL would not solve the memory issue.
> The whole file (weather it is json or jsonl) is loaded into python dicts and then converted into pytorch tensors (by multiple processes).
> 
> I see two options:
> 
> * For LM pretraining we have a StreamingDataSilo that does not convert the whole dataset at once. I shortly tested it for DPR processing, it does not work out of the box unfortunately. You could try fixing this.
> * For training DPR only few/one negative passage is used. You could remove other unused passages from the file and drastically reduce its size. We would highly appreciate this downsampling in our `read_dpr_json` method.
> 
> Would any of those solve your issues?

In my situation, it's because json load takes too much memory, iterative reading and appending data can solve my problem. (128GB memory, 30GB Data).
After that, all seems to be fine. However, I agree using the above strategy can further reduce memory usage. 
https://github.com/deepset-ai/FARM/blob/5ab5b1620cb51ceb874d4b30c887e377ad1a6e9a/farm/data_handler/utils.py#L217

**Comment by Timoeller** [comment]
Ok, makes sense.
Happy to accept a PR with the functionality. 

Otherwise I would highly recommend modifying your 30GB DPR file or did you hand select those 30GB of data?
We only use 1 positive and 1 hard negative context for training (maybe using more hard negatives can increase performance - I am unsure about the false negative rate if the hard negative ctxs are not checked by hand).
Checking in on original DPR train dataset, there are on average
positive_ctxs 8.5
negative_ctxs 50
hard_negative_ctxs 92.5
So the 7.4 GB train file could be reduced to just about a 10MB that is actually used.
