### ISSUE TITLE
Where is the QA model

### ISSUE THREAD

**Issue by kruthikakr** [deepset-ai/FARM#732]
I am refering this demo https://demos.deepset.ai/ : where is the model and script in the github link  to reproduce this ? and how to customise this above 15000 words ?

**Comment by Timoeller** [comment]
Hey, here you can find some more documentation about how to load your models: https://farm.deepset.ai/basic_usage.html#showcase-your-model-api-ui

Do you want to apply QA on a large document or multiple documents? Have you seen our other OSS project [Haystack](https://github.com/deepset-ai/haystack) that enables exactly that (and much more).

**Comment by kruthikakr** [comment]
Thank you for replying ..I am trying to apply the QA on large document as in the demo.. I am not able to find the model which was used in the demo.. Also is there upper limit of 15000 , which parameter decides this.. 

Yeah i saw the Haystack..But i am trying to work with 1 large document QA.

**Comment by kruthikakr** [comment]
Hi ..you are referring to this image  deepset/farm-inference-api:base-models-0.4.1 , for model source ?

**Comment by kruthikakr** [comment]
I am using the model from deepset/farm-inference-api:base-models-0.4.1
 nlp = Inferencer.load("base_models/bert-english-qa-large", task_type="question_answering")

# Run predictions
QA_input = [{"qas": ["Why is model conversion important?"],
             "context": "Model conversion lets people easily switch between frameworks."}]
result = nlp.inference_from_dicts(dicts=QA_input)

and getting the error as 

File "/home/kruthika/FARMAPI/farm/ex.py", line 3, in <module>
    nlp = Inferencer.load("/home/kruthika/FARMAPI/base_models/bert-english-qa-large", task_type="question_answering")
  File "/home/kruthika/FARMAPI/farm/infer.py", line 252, in load
    model = BaseAdaptiveModel.load(load_dir=model_name_or_path, device=device, strict=strict)
  File "/home/kruthika/FARMAPI/farm/modeling/adaptive_model.py", line 53, in load
    model = cls.subclasses["AdaptiveModel"].load(**kwargs)
  File "/home/kruthika/FARMAPI/farm/modeling/adaptive_model.py", line 340, in load
    head = PredictionHead.load(config_file, strict=strict)
  File "/home/kruthika/FARMAPI/farm/modeling/prediction_head.py", line 126, in load
    prediction_head.load_state_dict(torch.load(model_file, map_location=torch.device("cpu")), strict=strict)
  File "/home/kruthika/PycharmProjects/FARM/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for QuestionAnsweringHead:
	Missing key(s) in state_dict: "temperature_for_confidence"

**Comment by julian-risch** [comment]
Hi @kruthikakr unfortunately the model is a bit older and might not work with the most recent release of FARM out of the box. Let me check whether I can provide a workaround and fix that issue. However, I will need some more time to do that. In the meantime you could try with the previous FARM release: https://github.com/deepset-ai/FARM/releases/tag/v0.6.2

**Comment by julian-risch** [comment]
@kruthikakr another option would be to set `strict=False` when you load the Inferencer like so: 
`nlp = Inferencer.load("base_models/bert-english-qa-large", task_type="question_answering", strict=False)`

**Comment by julian-risch** [comment]
Hello @kruthikakr I will close this issue now. Feel free to re-open it if you still have a question regarding the described problem.
