### ISSUE TITLE
About natural_questions.py in the /examples

### ISSUE THREAD

**Issue by gabinguo** [deepset-ai/FARM#739]
**Question**
How do we use the model that trained with natural questions? 

Those are the files after I ran the code in natural_questions.py till save model/precessor
<img width="381" alt="Screenshot 2021-03-09 at 13 58 04" src="https://user-images.githubusercontent.com/27879119/110474020-78f02b00-80df-11eb-8bff-693e7aa81b0b.png">

I should now have a language model, a QA head and a classifier head in this folder.
But how to load the head for inference?

I've tried with the code below (Try to build lm + qa-head pipeline and lm + cls-head separately):
<img width="558" alt="Screenshot 2021-03-09 at 14 03 55" src="https://user-images.githubusercontent.com/27879119/110474761-59a5cd80-80e0-11eb-8e22-58ddef83e105.png">

It gives this error:
![image](https://user-images.githubusercontent.com/27879119/110474982-9bcf0f00-80e0-11eb-9d0d-d720e4777c72.png)

**Comment by julian-risch** [comment]
Hi @gabinguo , I think I know what the problem is but I will need some more time to fix that. In the meantime you could try with the previous FARM release: https://github.com/deepset-ai/FARM/releases/tag/v0.6.2

**Comment by gabinguo** [comment]
Ok, thanks for the quick reply : )
I will try the workaround you propose 👍

**Comment by gabinguo** [comment]
> Hi @gabinguo , I think I know what the problem is but I will need some more time to fix that. In the meantime you could try with the previous FARM release: https://github.com/deepset-ai/FARM/releases/tag/v0.6.2

I've tried with v0.6.2, and this gives back the error like:
<img width="1353" alt="Screenshot 2021-03-09 at 17 39 00" src="https://user-images.githubusercontent.com/27879119/110505509-810b9300-80fe-11eb-867a-464edf5d0177.png">

Is the code wrong for loading the model with multi-heads?

**Comment by julian-risch** [comment]
As of now, the Inferencer, in particular, the tokenizer is not working for NQ as described here: https://github.com/deepset-ai/FARM/blob/ae4b515dab4db4d55fd34588326b5a67868831a0/examples/natural_questions.py#L126 Unfortunately, I don't see an easy solution to that problem.

**Comment by Timoeller** [comment]
Hey @gabinguo for what reason do you want to use an NQ model? Do you want to try the yes/no capabilities, just the extractive (short answer) part, or something completely different?

Happy to interact and find a solution. Unfortunately, as @julian-risch pointed out, the current Inferencer does not work with NQ out of the box because we were simplifying the preprocessing for all other tasks a lot.

**Comment by gabinguo** [comment]
> Hey @gabinguo for what reason do you want to use an NQ model? Do you want to try the yes/no capabilities, just the extractive (short answer) part, or something completely different?
> 
> Happy to interact and find a solution. Unfortunately, as @julian-risch pointed out, the current Inferencer does not work with NQ out of the box because we were simplifying the preprocessing for all other tasks a lot.

Thanks for reply, I wanted to test a network that consists of one lm with two heads(qa and classifier for answerability), that's why I thought NQ model will be a perfect fit.

No worries, it's a great framework. I will wait for the update : )

**Comment by gabinguo** [comment]
> As of now, the Inferencer, in particular, the tokenizer is not working for NQ as described here:
> 
> https://github.com/deepset-ai/FARM/blob/ae4b515dab4db4d55fd34588326b5a67868831a0/examples/natural_questions.py#L126
> 

Hi there, for the example natural_questions.py, would it work If I change the model/tokenizer to bert? Since you mentioned in the comment that fast RobertaTokenizer is not working for NQ.

**Comment by Timoeller** [comment]
I'm unsure if this swapping tokenizers will work to be honest.

But please try an earlier version of FARM. Julian pointed you to a version where the changes actually happened...
Please try out FARM==0.5.0 and report back if that works out. Make sure to also downgrade transformers and your pytorch version.

**Comment by gabinguo** [comment]
> I'm unsure if this swapping tokenizers will work to be honest.
> 
> But please try an earlier version of FARM. Julian pointed you to a version where the changes actually happened...
> Please try out FARM==0.5.0 and report back if that works out. Make sure to also downgrade transformers and your pytorch version.

Thanks for the reply.

I tried with farm==0.5.0 transformers=3.3.1 torch=1.6. And it works fine. Thanks for the instructions : )

**Comment by Timoeller** [comment]
Thanks for reporting back and sorry that the solution took so long...

**Comment by ftesser** [comment]
Hello everyone, for what I understand NaturalQuestions does not work with farm>0.5.0, is that correct?

@Timoeller do you have any plan about re-fixing NaturalQuestions in the framework?

**Comment by gabinguo** [comment]
> Hello everyone, for what I understand NaturalQuestions does not work with farm>0.5.0, is that correct?
> 
> @Timoeller do you have any plan about re-fixing NaturalQuestions in the framework?

Hello, @ftesser
For the first question, yes currently you can only use farm under version 0.5.0 to run natural_question.py in /examples.
> Happy to interact and find a solution. Unfortunately, as @julian-risch pointed out, the current Inferencer does not work with NQ out of the box because we were simplifying the preprocessing for all other tasks a lot.

And based on the conversion before I think they are working on that.
