### ISSUE TITLE
Running in the windows

### ISSUE THREAD

**Issue by kruthikakr** [deepset-ai/FARM#740]
Trying to run the inference 
from farm.infer import *
nlp = Inferencer.load(r"C:\Users\Desktop\FARM\bert-english-qa-tutorial", task_type="question_answering")
# Run predictions[{"questions": ["What is X?"], "text":  "Some context containing the answer"}]
QA_input = [{"questions": ["Why is model conversion important?"],"text": "Model conversion lets people easily switch between frameworks."}]
result = nlp.inference_from_dicts(dicts=QA_input)
print(result)

And same error is looping repeatedly.

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable

**Comment by julian-risch** [comment]
HI @kruthikakr the problem that you describe seems to be specific to multiprocessing on Windows. Could you please share the exact and full script that you are trying to run? I assume that your problem could be solved by encapsulating your code in a method:
```
from farm.infer import *

def your_code():
    nlp = Inferencer.load(r"C:\Users\Desktop\FARM\bert-english-qa-tutorial", task_type="question_answering")
    QA_input = [{"questions": ["Why is model conversion important?"],"text": "Model conversion lets people easily switch between frameworks."}]
    result = nlp.inference_from_dicts(dicts=QA_input)
    print(result)

if __name__ == "__main__":
    your_code()
```

**Comment by julian-risch** [comment]
Hello @kruthikakr did you try the proposed fix? Did it solve your problem or did you find another solution?

**Comment by julian-risch** [comment]
Hi @kruthikakr are you still facing the described problem or can I close this issue?

**Comment by kruthikakr** [comment]
I did not try this in windows , working fine in ubuntu
