### ISSUE TITLE
Multi-task learning

### ISSUE THREAD

**Issue by Simons2017** [deepset-ai/FARM#742]
**Question**
Could you give me some advice on how to train the BERT using MTL （Multi-class Text Classification + Reading Comprehension）?

**Comment by Timoeller** [comment]
Hey @Simons2017 good point, I linked a similar issue. Maybe we can get @imdiptanu to push the example he used.

For your use case you will probalbly need some tailoring. With "Reading Comprehension" do you mean QA or what exactly?

**Comment by imdiptanu** [comment]
Hi @Simons2017, I am on vacation so it may take a week. However, if you could reach out to me privately I can share a notebook to get you started if it's urgent.

**Comment by Simons2017** [comment]
> Hey @Simons2017 good point, I linked a similar issue. Maybe we can get @imdiptanu to push the example he used.
> 
> For your use case you will probalbly need some tailoring. With "Reading Comprehension" do you mean QA or what exactly?

QA

**Comment by Simons2017** [comment]
> Hi @Simons2017, I am on vacation so it may take a week. However, if you could reach out to me privately I can share a notebook to get you started if it's urgent.
Thank you very much. How can I contact you?

**Comment by imdiptanu** [comment]
> Hi @Simons2017, I am on vacation so it may take a week. However, if you could reach out to me privately I can share a notebook to get you started if it's urgent.
> Thank you very much. How can I contact you?

I thought you could see my email on my profile- diptanusarkar[at]hotmail[dot]com.

**Comment by Timoeller** [comment]
Hey gentlemen, any progress on the MTL front?
