### ISSUE TITLE
Wights and Biases logger support

### ISSUE THREAD

**Issue by thenewera-ru** [deepset-ai/FARM#743]
Integrate one more remote logging option:[wandb](https://wandb.ai/site).

**Comment by thenewera-ru** [comment]
I can work on that and open PR if that logging option would benefit most of the users.

**Comment by Timoeller** [comment]
Hey sure, that would be appreciated. Would it be possible to wrap W&B logging around the existing logging class [BaseMLLogger](https://github.com/deepset-ai/FARM/blob/master/farm/utils.py#L95)?

**Comment by thenewera-ru** [comment]
Yep, I think it fits nicely into [this](https://github.com/deepset-ai/FARM/blob/master/farm/utils.py#L95) interface. 
The only possible misunderstanding would potentially be between `experiment` and `run`. In [WANDB](https://wandb.ai/site) context they call any experiment `run`. Everything else is more or less the same, I hope :-)
