### ISSUE TITLE
Add Big Bird to FARM

### ISSUE THREAD

**Issue by tanmaylaud** [deepset-ai/FARM#747]
This issue will be used to track the integration of Google's BigBird into FARM.

After initial code integration, the following will be explored:
- Train BigBird on SQUAD.
- Train BigBird on TriviaQA
- Evaluate the efficiency gain in training time for BigBird vs current models in haystack.

Huggingface has a nice implementation of tokenizers and model for BigBird. we can use that.

**Comment by Timoeller** [comment]
Hey @tanmaylaud I like the suggestion. BigBird from Google improves on long context QA significantly. I believe this will be especially relevant for multihop QA, where the necessary information to answer a question can come from different text/positions in text. Attending over long context or multiple texts will be key to success.

Just as a sidenote: there is also a [BIGBIRD](https://twitter.com/sleepinyourhat/status/1075889120386248704?s=19) from Microsoft, though it is just normal Bert with multi task learning to achieve back then SOTA on GLUE.

Would you like to work on this? I think an integration through Transformers should be straightforward. We will have to include the next [release](https://github.com/huggingface/transformers/issues/6113#issuecomment-811504316) that should happen this week. If you say you want to try working on it, we can commit to a including latest transformers this week into FARM.

**Comment by tanmaylaud** [comment]
Hi @Timoeller , yes I can work on this. 
I have started with first adding fast tokenizer for the model in HF. 
here is the [PR](https://github.com/huggingface/transformers/pull/11075)

**Comment by Timoeller** [comment]
Nice!

We have also increased the Transformers Version to 4.5.0 in https://github.com/deepset-ai/FARM/pull/749 so you could use the Big Bird code

**Comment by Timoeller** [comment]
Hey @tanmaylaud would you like to contribute Bigbird to FARM, so we can also merge it to haystack in a meaningful way soon?
Would be pretty cool!

**Comment by tanmaylaud** [comment]
Hi @Timoeller , yes I would like to.
As mentioned earlier, I am facing some issues with the Fast tokenizer in the upstream HF code.
Once that is resolved, we will be able to use the Fast tokenizer in Haystack.
Does that sound good?

**Comment by Timoeller** [comment]
Ah sorry, yes, we need to wait until the fast tokenizer support for Bigbird is inside transformers of course.

**Comment by Timoeller** [comment]
Lets wait for the next release to get the changes in, if you cannot wait you can of course create a PR on transformers master branch : )

**Comment by Timoeller** [comment]
BigBird is now in FARM with #790 
Thanks @tanmaylaud
