### ISSUE TITLE
Getting a ton of WARNING messages: "Currently no support in Processor for returning problematic ids" 

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#759]
Using the latest FARM installed with `pip install farm`, I am getting many many WARNING messages on the log:

" WARNING - farm.data_handler.processor -   Currently no support in Processor for returning problematic ids" 

What does this mean and is there anything I can do about it?

**Comment by Timoeller** [comment]
Hey @johann-petrak cool to see you using FARM again :smile: 

So this warning is not that there are problematic input samples per se but that we do not have functionality for it in place for some processors.

For the QA processor we can return problematic samples during preprocessing, e.g. for TextclassificationProcessor and its derivatives we cannot. See https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/processor.py#L675 
If you want to improve FARM in this respect I see two options:
1. [quick win] Change the message to Info or reduce the number it is displayed.
2. [correct but difficult] Implement the problemtaic id check for the processor you need.

**Comment by johann-petrak** [comment]
Sorry, TBH so far what I do not understand is much more basic: what is actually meant by "problematic input sample" i.e. which error conditions make a sample problematic? And what error conditions could actually already occur when converting samples in the TextclassificationProcessor?
Apparently the only way how these ids can bubble up is through an exception in `self._sample_to_features(sample=sample)` ?

**Comment by Timoeller** [comment]
Hey @johann-petrak would you be interested in contributing the quick improvement I proposed as method 1?

Method 1: Change the message to Info and/or reduce the number of times it is displayed.

**Comment by Timoeller** [comment]
Makes sense to put it there! Would you like to create a PR?

**Comment by johann-petrak** [comment]
https://github.com/deepset-ai/FARM/pull/772
