### ISSUE TITLE
Convert FARM gelectra Model to HuggingFace Model

### ISSUE THREAD

**Issue by florianbaer** [deepset-ai/FARM#763]
**Describe the bug**
I have trained a classification model of gelectra to classify text. Worked so far as expected. I want to integrate the model in a microservice. For this, i wanted to convert the **FARM-Model** to a **HuggingFace-Model**. To do so, i went through the docs and found the examples [here](https://github.com/deepset-ai/FARM/blob/master/examples/conversion_huggingface_models.py). But when i run the code (same code, different directories), i get the messages below:

**Error message**
05/11/2021 19:39:56 - INFO - farm.modeling.prediction_head -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
05/11/2021 19:39:56 - INFO - farm.modeling.language_model -   
05/11/2021 19:39:56 - INFO - farm.modeling.language_model -   LOADING MODEL
05/11/2021 19:39:56 - INFO - farm.modeling.language_model -   =============
05/11/2021 19:39:56 - INFO - farm.modeling.language_model -   Model found locally at /home/myname/Models/Competence/deepset/gelectra-base
05/11/2021 19:39:58 - INFO - farm.modeling.language_model -   Loaded /home/myname/Models/Competence/deepset/gelectra-base
05/11/2021 19:39:58 - INFO - farm.modeling.adaptive_model -   Found files for loading 1 prediction heads
05/11/2021 19:39:58 - WARNING - farm.modeling.prediction_head -   `layer_dims` will be deprecated in future releases
05/11/2021 19:39:58 - INFO - farm.modeling.prediction_head -   Prediction head initialized with size [768, 4]
05/11/2021 19:39:58 - INFO - farm.modeling.prediction_head -   Using class weights for task 'text_classification': [1.0, 1.0, 1.0, 1.0]
05/11/2021 19:39:58 - INFO - farm.modeling.prediction_head -   Loading prediction head from /home/myname/Models/Competence/deepset/gelectra-base/prediction_head_0.bin
file /home/myname/Models/Competence/deepset/gelectra-base/config.json not found
05/11/2021 19:39:58 - INFO - farm.modeling.tokenization -   Loading tokenizer of type 'ElectraTokenizer'
Traceback (most recent call last):
  File "/home/myname/source/hslu/ba/Code/Models/HuggingFace/convert_to_transformers_classification.py", line 46, in <module>
    convert_to_transformers()
  File "/home/myname/source/hslu/ba/Code/Models/HuggingFace/convert_to_transformers_classification.py", line 29, in convert_to_transformers
    transformer_model = model.convert_to_transformers()[0]
  File "/home/myname/anaconda3/envs/ba/lib/python3.8/site-packages/farm/modeling/adaptive_model.py", line 511, in convert_to_transformers
    return conv.Converter.convert_to_transformers(self)
  File "/home/myname/anaconda3/envs/ba/lib/python3.8/site-packages/farm/conversion/transformers.py", line 42, in convert_to_transformers
    transformers_model = Converter._convert_to_transformers_classification_regression(adaptive_model,
  File "/home/myname/anaconda3/envs/ba/lib/python3.8/site-packages/farm/conversion/transformers.py", line 178, in _convert_to_transformers_classification_regression
    transformers_model.classifier.load_state_dict(
  File "/home/myname/anaconda3/envs/ba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ElectraClassificationHead:
	Missing key(s) in state_dict: "dense.weight", "dense.bias", "out_proj.weight", "out_proj.bias". 
	Unexpected key(s) in state_dict: "weight", "bias". 

Process finished with exit code 1

**Expected behavior**
Model should convert without an error :ok_hand: 

**Additional context**
-

**To Reproduce**
Train an deepset/gelectra model for a classification task with farm - convert it 

**System:**
 - OS: Ubuntu 20.04.2 LTS x86_64
 - GPU/CPU: NVIDIA GeForce GTX 1080 (others are too expensive :sob: )
 - FARM version: farm~=0.7.0

**Comment by Timoeller** [comment]
Hey @florianbaer thanks for using FARM and our Gelectra models.

I see you are using class weights, but all are 1. Those class weights are not supported in HF transformers. Could you try switching those of (by passing None in the datasilo) and try the conversion again?

We were able to successfully convert Gelectra Language Models and Question Answering models, so it should work for this achitecture.

**Comment by florianbaer** [comment]
Hi, thanks for your superfast answer! :rocket: 
First of all, thank you for open sourcing this awesome tool!
As far as I understand, I have to retrain the model for this?

**Comment by Timoeller** [comment]
I think retraining is the simplest solution.

Please retrain the model on sample data first before converting, I havent tested Gelectra + classification conversion yet and cannot confirm that it works. I can only confirm LM + QA conversion.

**Comment by florianbaer** [comment]
I will look into it in the afternoon and then provide feedback. Thank you :smiley:

**Comment by florianbaer** [comment]
Hi @Timoeller 
The problem persists:
`
05/12/2021 14:28:48 - INFO - farm.modeling.prediction_head -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
05/12/2021 14:28:48 - INFO - farm.modeling.language_model -   
05/12/2021 14:28:48 - INFO - farm.modeling.language_model -   LOADING MODEL
05/12/2021 14:28:48 - INFO - farm.modeling.language_model -   =============
05/12/2021 14:28:48 - INFO - farm.modeling.language_model -   Model found locally at /home/florian/Models/Competence/deepset/gelectra-base
05/12/2021 14:28:49 - INFO - farm.modeling.language_model -   Loaded /home/florian/Models/Competence/deepset/gelectra-base
05/12/2021 14:28:49 - INFO - farm.modeling.adaptive_model -   Found files for loading 1 prediction heads
05/12/2021 14:28:49 - WARNING - farm.modeling.prediction_head -   `layer_dims` will be deprecated in future releases
05/12/2021 14:28:49 - INFO - farm.modeling.prediction_head -   Prediction head initialized with size [768, 4]
05/12/2021 14:28:49 - INFO - farm.modeling.prediction_head -   Loading prediction head from /home/florian/Models/Competence/deepset/gelectra-base/prediction_head_0.bin
file /home/florian/Models/Competence/deepset/gelectra-base/config.json not found
05/12/2021 14:28:49 - INFO - farm.modeling.tokenization -   Loading tokenizer of type 'ElectraTokenizer'
Traceback (most recent call last):
  File "/home/florian/source/hslu/ba/Code/Models/HuggingFace/convert_to_transformers_classification.py", line 46, in <module>
    convert_to_transformers()
  File "/home/florian/source/hslu/ba/Code/Models/HuggingFace/convert_to_transformers_classification.py", line 29, in convert_to_transformers
    transformer_model = model.convert_to_transformers()[0]
  File "/home/florian/anaconda3/envs/ba/lib/python3.8/site-packages/farm/modeling/adaptive_model.py", line 511, in convert_to_transformers
    return conv.Converter.convert_to_transformers(self)
  File "/home/florian/anaconda3/envs/ba/lib/python3.8/site-packages/farm/conversion/transformers.py", line 42, in convert_to_transformers
    transformers_model = Converter._convert_to_transformers_classification_regression(adaptive_model,
  File "/home/florian/anaconda3/envs/ba/lib/python3.8/site-packages/farm/conversion/transformers.py", line 178, in _convert_to_transformers_classification_regression
    transformers_model.classifier.load_state_dict(
  File "/home/florian/anaconda3/envs/ba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ElectraClassificationHead:
	Missing key(s) in state_dict: "dense.weight", "dense.bias", "out_proj.weight", "out_proj.bias". 
	Unexpected key(s) in state_dict: "weight", "bias".`

**Comment by Timoeller** [comment]
K thanks for checking, we will look into this in detail and come back to you. I am pretty sure we wont find a solution before next week.

**Comment by julian-risch** [comment]
Hi @florianbaer the problem is the slightly different architecture of the ElectraClassificationHead. As you reported, there is a mismatch of the names of the layers that we store in FARM ("weight", "bias") and the names of the layers that are expected by the ElectraClassificationHead of transformers ("dense.weight", "dense.bias", "out_proj.weight", "out_proj.bias").
```
RuntimeError: Error(s) in loading state_dict for ElectraClassificationHead:
Missing key(s) in state_dict: "dense.weight", "dense.bias", "out_proj.weight", "out_proj.bias".
Unexpected key(s) in state_dict: "weight", "bias".
```
https://github.com/huggingface/transformers/blob/0d1f67e651220bffef1441fa7589620e426ba958/src/transformers/models/electra/modeling_electra.py#L904 

I see two options:
1. Implement functionality in FARM that correctly maps the layers here: https://github.com/deepset-ai/FARM/blob/c144c5cb29466eeac744d4abf72fbd64c12fe97e/farm/conversion/transformers.py#L156
2. FARM does not support the conversion of ElectraClassificationHead and we log an error message in the same way as for RobertaClassificationHead: https://github.com/deepset-ai/FARM/blob/c144c5cb29466eeac744d4abf72fbd64c12fe97e/farm/conversion/transformers.py#L157
@florianbaer Would you like to implement one of the two options? What's your workaround at the moment?

**Comment by florianbaer** [comment]
Hi @julian-risch 
I would love to help. Currently, i am in the military service - I could take a look at it in about a month (if it's not too late).  As workaround, I use the FARM-Infer Module for the predictions - it was only for a demonstration application for my bsc thesis - regarding my thesis I would love to say the following: THANKS for providing FARM as Open Source Software - it was **VERY HELPFUL**.

**Comment by julian-risch** [comment]
Great to hear that Florian! Let me know if any questions come up in a month. It's no problem if it takes some time. I would encourage you to create a work-in-progress pull request when you start working on this topic and reference this issue here. This way, we can give feedback early on.

**Comment by julian-risch** [comment]
Hi @florianbaer I hope you are doing well. Any updates regarding this issue here on electra models? If you start working on this issue, feel free to create a work-in-progress pull request and link this issue.

**Comment by florianbaer** [comment]
Hi @julian-risch 
Sorry, totally forgot about it (shame on me). I will create a work on progress pull request when I will start it.

**Comment by florianbaer** [comment]
@julian-risch I took a quick look into the code. I would be able to integrate the warning - but for fixing the conversion - i think i am not qualified enought. So should i just implement the warning and then make the pr?

**Comment by julian-risch** [comment]
Hi @florianbaer thanks for having a look at the code. I think the warning would be a nice addition. However, we are in the process of migrating FARM into haystack. I am not sure whether it's a good point in time now to work on this issue (even if it is a small issue). @Timoeller what do you think? Could Florian work on the issue here in FARM and we move his changes to haystack later on or should he wait until haystack 1.0 release? I prefer the second option.

**Comment by Timoeller** [comment]
Hey, so the warning is about converting classification electra models. We wont merge the classification part of FARM to Haystack so we can add the warning here in FARM.

@florianbaer yes please add the awarning, it would be a good addition so others at least know why it fails. But keep in mind, since we migrate most parts of FARM to haystack, we cannot support you much in the contribution (sorry).
