### ISSUE TITLE
requirements.txt -> Werkzeug

### ISSUE THREAD

**Issue by drellxor** [deepset-ai/FARM#764]
**Question**
Hello! 
FARM has strictly specified `Werkzeug==0.16.1` version in requirements. And it is not really comfortable for integrating your another project [haystack](https://github.com/deepset-ai/haystack) into existing flask application, because version 0.16.1 is quite outdated and dependency conflict occurs. 

What do you think about removing Werkzeug version number from requirements? I can do it on my own, check if everything works fine and then create pull request. Just want to know, maybe version was strictly specified for some particular reason.

**Comment by julian-risch** [comment]
Hi @drellxor The reason why we fixed the version of Werkzeug is that flask-restplus library was broken by an update of Werkzeug (noirbizarre/flask-restplus#777). As a quick-fix, we pinned the version of Werkzeug in FARM requirements. Here is the corresponding pull request #250 
It would be great if you could check whether this problem has been fixed and whether a more recent version of Werkzeug works with flask-restplus!

**Comment by drellxor** [comment]
@julian-risch Thank you for you answer! As I know, flask-restplus is no longer maintained and I'm afraid there is no way it will be fixed there. But there's a great fork [flask-restx](https://github.com/python-restx/flask-restx) and it's official as I know. They fixed problem with Werkzeug there (issue: https://github.com/python-restx/flask-restx/issues/34, pull request: https://github.com/python-restx/flask-restx/pull/35)

What do you think about changing from flask-restplus to flask-restx?

**Comment by julian-risch** [comment]
You are right. flask-restx is a better alternative. 👍 I would appreciate changing from flask-restplus to flask-restx and upgrading Werkzeug.

**Comment by julian-risch** [comment]
@drellxor would you like to contribute by making the change, checking if everything works fine and then creating a pull request?

**Comment by drellxor** [comment]
@julian-risch Yeah, sure. 
But we probably should wait a couple of days until flast-restx 0.4.0 release, because latest flask 2.0.0 release that happened about a week ago breaks current flask-restx release. 

Other option may be just to pin flask version to `<= 2.0.0`. But in this case we may face similar issue a bit later. 

Which option do you think will be better?

**Comment by julian-risch** [comment]
Great to hear that! I think the first option is better. We can wait until flast-restx 0.4.0 release.
