### ISSUE TITLE
DPR saving and loading, also for non-bert architectures

### ISSUE THREAD

**Issue by Timoeller** [deepset-ai/FARM#771]
We need to tackle DPR saving and loading within FARM to make it compatible with architectures other than Bert and also the HF modelhub.
People should be able to train models, save them, load them in FARM or haystack and convert them to HF transformers to upload them to the model hub. 

Related to https://github.com/deepset-ai/haystack/issues/1046

**Comment by julian-risch** [comment]
Fixed in #765
