### ISSUE TITLE
Very first example in Readme.rst won't run

### ISSUE THREAD

**Issue by nothingTVatYT** [deepset-ai/FARM#788]
The very first example a new user may want to run is the code snippet in the README, but it does not mention the pathlib and there is a bracket missing.

Can we add the line:

    from pathlib import Path

and close the Path() call with a bracket?

I think it's quite an obstacle for curious new users like me when the first code snippet fails due to unclear assumptions and typos.

**Comment by julian-risch** [comment]
@nothingTVatYT  Thank you. Good catch! I prepared a fix here: #789
