### ISSUE TITLE
Any experience of using FARM with AWS SageMaker?

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#794]
Especially deploying a FARM model on AWS SageMaker?

**Comment by tholor** [comment]
Unfortunately, just for training (in our case language models from scratch, see [blog](https://aws.amazon.com/blogs/machine-learning/deepset-achieves-a-3-9x-speedup-and-12-8x-cost-reduction-for-training-nlp-models-by-working-with-aws-and-nvidia/), [example script for the container](https://github.com/deepset-ai/FARM/blob/master/examples/train_from_scratch_with_sagemaker.py) and [marketplace algorithm](https://aws.amazon.com/marketplace/pp/prodview-bpq22kfqxt376) ). I guess you are more interested in the inference side of things?! We don't use SageMaker there - so probably cannot help that much there.

**Comment by johann-petrak** [comment]
Thank you for those pointers, I will check them out! 
Yes, in my case mainly inference, but as I am totally new with AWS / SageMaker, everything helps.

**Comment by johann-petrak** [comment]
OK, short update: to get inference to work with SageMaker the "standard" approach would be to get inference to work with 
torchserve 
Did anyone ever try to do that? TBH I do not really understand why torchserve does things the way it wants to do it and what the best way could be to fit FARM inference into this.

**Comment by vbankov** [comment]
hi @johann-petrak, it is definitely possible to use FARM for serving predictions on a SageMaker endpoint by wrapping it up with an API like Flask and containerizing all of the code responsible for inference. 

The basic need is for the API to respond to requests against */invocations* and */ping* in order for it to be compatible with SageMaker's serving framework. Some documentation that could help you can be found [on this link](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html)
