### ISSUE TITLE
Allow torch 1.9 version in requirements.txt

### ISSUE THREAD

**Issue by vblagoje** [deepset-ai/FARM#810]
Hi, is there reason for torch 1.9 to be excluded from requirements.txt dependencies? These days I am working on LFQA demos on Colab which comes with torch 1.9 pre-installed. Every time I install haystack pip picks up torch<1.9,>1.5 dependency from farm and it installs 1.8.1 torch, while 1.9 is already preinstalled. 

I've seen that you guys do torch compatibility testing for every new torch release. How likely are new torch releases to break farm? Would it be possible to leave upper bound on torch dependency open?

**Comment by Timoeller** [comment]
Good point. We don't mind the update.

How about we test torch 1.9 compatibility first and then increase the range? We had non obvious trouble with torch updates before.
Anyways, getting the new range into Haystack will require a new FARM release first unfortunately...

**Comment by vblagoje** [comment]
Yeah, sure no problem, that sounds great! Thanks @Timoeller
