### ISSUE TITLE
Does the public MLFlow server support uploading artifacts and models?

### ISSUE THREAD

**Issue by Ark-kun** [deepset-ai/FARM#831]
First of all, thank you a lot for providing public MLFlow server. MLFlow is surprisingly inconvenient to deploy, so this really helps trying out `farm`.

I'm trying to get a grip on model logging and it looks like I cannot log any artifacts.

```python
from farm.utils import set_all_seeds, MLFlowLogger
ml_logger = MLFlowLogger(tracking_uri="https://public-mlflow.deepset.ai/")
ml_logger.init_experiment(experiment_name="Public_FARM", run_name="Run_doc_regression")
ml_logger.log_artifacts(mlflow_model_path, artifact_path="Artifact_1")
```
```
07/18/2021 02:22:25 - WARNING - farm.utils -   Failed to log artifacts: Failed to upload /home/jupyter/mlflow_model.MLFlowModel/conda.yaml to public-mlflow/2/da79489fac914ae7b2f59cf9691e57d2/artifacts/Artifact_1/conda.yaml: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

Is this expected?

**Comment by Timoeller** [comment]
Our public MLFlow instance is rather small, so logging artifacts or even whole models would made it crash.

What kind of problems arise when setting up your own MLFlow, maybe also the MLFlow community help there?
