### ISSUE TITLE
requirements.txt -> loosen up mlflow restriction

### ISSUE THREAD

**Issue by codingmercy1993** [deepset-ai/FARM#834]
**Question**
Hey guys!
FARM has strictly specified mlflow<=1.13.1 version in requirements. 
This version is more than one year old. 
We want to use FARM in a corporate context where we need to use a relatively new mlflow version (mlflow == 1.19.0).
Unfortunately this procudes conflicts that we can not resolve. 
We already discuss about forking FARM to manage these conlicts.

What do you think about integrating a newer mlflow version or loosen up your restrictions a bit (e.g.  mlflow~= 1.13.*) in requirements.txt?
 I can do it on my own, check if everything works fine and then create pull request. 
Just want to know, maybe version was strictly specified for some particular reason.

Thanks you! :-)

**Comment by Timoeller** [comment]
Hey sure, this is a good idea.

Could you create a PR and test if the logging works for some of the examples in combination with our https://public-mlflow.deepset.ai/#/ server?
