### ISSUE TITLE
AdaptiveModel.convert_to_onnx does not save float16 model conversion to output_path

### ISSUE THREAD

**Issue by cjb06776** [deepset-ai/FARM#845]
I think there is a small bug with `AdaptiveModel.convert_to_onnx` when enabling float16 conversion:

https://github.com/deepset-ai/FARM/blob/7305a17979b0a80dbe2dbebe5815450883f20627/farm/modeling/adaptive_model.py#L614-L624

The resulting model file ends up in the current working directory instead of `output_path/model.onnx`.

Should be something like:

```
            optimized_model.save_model_to_file(str(output_path/"model.onnx"))
```

**Comment by Timoeller** [comment]
Good catch, do you want to create a PR for it?
