### ISSUE TITLE
Suggestion: Add Option to use Processor.dataset_from_dicts() in datasilo.load_data()

### ISSUE THREAD

**Issue by FlorianRauls** [deepset-ai/FARM#85]
When initializing a new DataSilo it automatically calls self._load_data() which in turn calls self.processor.dataset_from_file().

The option to pass data via dictionaries would be much appreciated since Processor.dataset_from_dicts() is already implemented and manually working around is causing much inconvenience when doing preprocessing (i.e. getting Errors since train.tsv was not found).

**Comment by tanaysoni** [comment]
Hi @FlorianRauls, thank you the suggestion! We are currently refactoring `DataSilo` and `Processor` in #88, so we can consider adding this option. It'd be helpful if you could provide more details on your use case.

**Comment by tholor** [comment]
Hi @FlorianRauls, 
after finishing refactoring, I had now some time to look into your request.
It would be actually quite easy to add your desired functionality. 

Please have a look at the pull request #127 and let me know, if that's what you need.

**Comment by FlorianRauls** [comment]
> Hi @FlorianRauls,
> after finishing refactoring, I had now some time to look into your request.
> It would be actually quite easy to add your desired functionality.
> 
> Please have a look at the pull request #127 and let me know, if that's what you need.

Hi @tholor,
this is would resolve the issue quite nicely!

Thanks for looking into it!

**Comment by tholor** [comment]
Fixed by #127
