### ISSUE TITLE
how to predict on single data points for classification problem.?

### ISSUE THREAD

**Issue by shrikantpandey13** [deepset-ai/FARM#850]
**Question**
how to predict on single data points for classification problem.

**Additional context**
 I am not able to see any context, how to predict on single data points for classification problem.

Please help here...

**Comment by shrikantpandey13** [comment]
I found the solution for single data points predictions.

Thanks a lot.

**Comment by Timoeller** [comment]
Great self help :)

Can you share what was the solution?
