### ISSUE TITLE
Error Importing Inferencer

### ISSUE THREAD

**Issue by Stefan-Pasch** [deepset-ai/FARM#851]
Hi, 

since today, I receive the following error when important Inferencer from farm.infer.:

**_OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory_**

I am running FARM on Colab. The error also occurs when installing FARM in the way specified in the FARM-Colab Tutorials: 

_!pip install farm 
!pip install torch==1.5.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html_

When I ran the exact same code 3 days ago, there appeared no error. 

Many thanks in advance!

![libtorch_error](https://user-images.githubusercontent.com/45234256/142845520-cfd473e9-8d2c-414b-896a-3d072996b004.png)

**Comment by Timoeller** [comment]
Hey Stefan, we also receive this error when our Haystack notebooks are used.
Please have a look at this issue and if Bogdans answer also resolves your FARM colab problems:
https://github.com/deepset-ai/haystack/issues/1786

**Comment by Stefan-Pasch** [comment]
Hi Timo, 
many thanks for your quick reply! In fact, the problem in my FARM colab was resolved when installing torch in the following way:

`!pip install torch==1.10.0+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html
`

**Comment by Timoeller** [comment]
Perfect.

Please be aware that other (possibly hidden) bugs could emerge when updating the torch version without thorough testing.
We have experienced problems with TAPAS in Haystack when using some torch==1.10.X versions.

**Comment by Serbernari** [comment]
The problem of libtorch_cuda_cpp.so stays now in the Colab even with torch==1.10.0+cu111

upd: !pip install torch==1.10.0+cu111 torchvision==0.11.0 torchaudio==0.10.0 -f https://download.pytorch.org/whl/cu111/torch_stable.html helped
