### ISSUE TITLE
Max token size?

### ISSUE THREAD

**Issue by kishb87** [deepset-ai/FARM#854]
**Question**
I am currently using the Huggingface deepset/roberta-base-squad2 model for Question-Answering. From what I understand, RoBERTa has a max token length of 512 yet I am able to provide larger documents as context. 

Can you provide some insight into how this model is able to do this? Does the model chunk the context into multiple tokens or is this a variation of RoBERTa that allows for longer token lengths?

**Comment by Timoeller** [comment]
Hey sure, thanks for reaching out. We recently moved all our QA functionality to https://github.com/deepset-ai/haystack, so please ask future questions there.

About your question: yes, roberta has a 512 token lengths limit but QA methods chunk text into smaller pieces and aggregate the answers over these multiple chunks (or even across multiple documents).

Hope that helps?

**Comment by kishb87** [comment]
It does. Thanks for the help. Will definitely ask future questions in the other thread.
