### ISSUE TITLE
Need a guidance on Multi label Classification

### ISSUE THREAD

**Issue by pbsprashanth113** [deepset-ai/FARM#858]
**Question**
Need a guidance on Multi label Classification

**Additional context**
We are working on Multi label text classification problem to classify to classes such as current states(Negative low, Negative high, Positive High, Positive low) and desired states(Positive High, Positive low ), currently we have labelled around 50 posts,

As I am beginner to this, could someone guide right approaches or reference code or article to go about this.  

-Thanks
Add any other context or screenshots about the question (optional).
![Screen Shot 2022-04-25 at 4 55 05 PM (1)](https://user-images.githubusercontent.com/78494482/165979051-c9b151ee-691d-4827-b787-b0b478b69635.png)

**Comment by sjrl** [comment]
Sorry, we do not actively maintain this project any longer. 

We migrated the core modeling parts of FARM into [Haystack](https://github.com/deepset-ai/haystack/). All active development is happening there and this repo is not actively maintained anymore! Go over there to ask questions & create issues!
