### ISSUE TITLE
Which pytorch (and other package) versions are actually required

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#860]
When `pip install farm` is run, only certain PyTorch versions are allowed (<1.10) and mlflow versions are restricted to <=1.13.1

Why is this? It makes it increasingly difficult to use the library with other software that expects more recent versions of those libraries.

Is it precautionary or are there actual known problems with more recent versions (which could possibly get solved, of course)?

**Comment by tholor** [comment]
Hey @johann-petrak, this is mainly precautionary and due to the fact that we don't actively maintain FARM anymore. In the past, there were quite some cases where even minor pytorch releases included breaking changes. So we rather opted for pinning a known working version here.

**Comment by Serbernari** [comment]
!pip install torch==1.10.0+cu111 torchvision==0.11.0 torchaudio==0.10.0 -f https://download.pytorch.org/whl/cu111/torch_stable.html  worked

**Comment by johann-petrak** [comment]
Also clamping the transformers version is problematic since it has progressed a lot. 
I updated to 4.21.0 without problem, but starting at 4.22.0 it becomes evident that farm was using the private function cached_path which got removed in 4.22.0, so things break. 

`transformers.utils.hub.cached_file` from https://github.com/huggingface/huggingface_hub is probably the closest approximation
