### ISSUE TITLE
KeyError: 'text_classification'

### ISSUE THREAD

**Issue by guggio** [deepset-ai/FARM#94]
Hi guys, 

Unfortunately, it is me again. This time, I am reporting an issue during text classification which did not appear yesterday despite running the same code. Everything works fine until training the model.

```
tokenizer = BertTokenizer.from_pretrained(
    pretrained_model_name_or_path="bert-base-german-cased",
    do_lower_case=False)

processor = TextClassificationProcessor(
    tokenizer=tokenizer,
    max_seq_len=128,
    data_dir="",
    train_filename="train.tsv",
    dev_filename='dev.tsv',
    labels=["Claim","Premise"],
    metric="f1_macro",
    dev_split=0.0
    )

BATCH_SIZE = 32
data_silo = DataSilo(
    processor=processor,
    batch_size=BATCH_SIZE)

MODEL_NAME_OR_PATH = "bert-base-german-cased"
language_model = Bert.load(MODEL_NAME_OR_PATH)

LAYER_DIMS = [768, 2]
prediction_head = TextClassificationHead(layer_dims=LAYER_DIMS)

EMBEDS_DROPOUT_PROB = 0.1
model = AdaptiveModel(
    language_model=language_model,
    prediction_heads=[prediction_head],
    embeds_dropout_prob=EMBEDS_DROPOUT_PROB,
    lm_output_types=["per_sequence"],
    device=device)

LEARNING_RATE = 2e-5
WARMUP_PROPORTION = 0.1
N_EPOCHS = 1
optimizer, warmup_linear = initialize_optimizer(
    model=model,
    learning_rate=LEARNING_RATE,
    warmup_proportion=WARMUP_PROPORTION,
    n_batches=len(data_silo.loaders["train"]),
    n_epochs=N_EPOCHS)

N_GPU = 1
trainer = Trainer(
    optimizer=optimizer,
    data_silo=data_silo,
    epochs=N_EPOCHS,
    n_gpu=N_GPU,
    warmup_linear=warmup_linear,
    device=device,
)

```

**Error message**
```
/usr/local/lib/python3.6/dist-packages/farm/modeling/adaptive_model.py in connect_heads_with_processor(self, tasks)
    231         """
    232         for head in self.prediction_heads:
--> 233             head.label_tensor_name = tasks[head.task_name]["label_tensor_name"]
    234             head.label_list = tasks[head.task_name]["label_list"]
    235             head.metric = tasks[head.task_name]["metric"]
KeyError: 'text_classification'
```

Due to this error message, i added a task to the processor which resulted in an error when I wanted to create the datasilo.

```
processor.add_task(name='text_classification', metric='f1_macro',label_list=['Claim', 'Premise'])
```
```
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1250             if not(self.name == 'loc' and not raise_missing):
   1251                 not_found = list(set(key) - set(ax))
-> 1252                 raise KeyError("{} not in index".format(not_found))
   1253 
   1254             # we skip the warning on Categorical/Interval
KeyError: '[None] not in index'
```

Thus, I assume the bug lies in the 'text_classification' task name.

Thanks in advance,
Sebastian

**System:**
 - OS: Mac OS 10.14.6 running on Google Colab
 - GPU/CPU: GPU
 - FARM version: 0.2.0

**Comment by Timoeller** [comment]
Hey Sebastian. No problem at all.

Could you try changing the labels parameter to label_list in the TextClassificationProcessor. If this doesn't fix the problem I will have to look more deeply into the code first thing tomorrow morning.
Keep on :)

**Comment by guggio** [comment]
Hi @Timoeller , thanks a lot for the quick help! Your suggestions (changing to label_list) worked perfectly and I was able to run my model. I am running the init of the processor and the .add_task in the same Colab cell (like in your Colab NER tutorial). 

I ran my model and unfortunately observed new issues with the classification reports. While the f1_macro works well, the classification report only shows the labels and zeros (for dev and test set). 

```
09/19/2019 20:32:07 - INFO - farm.eval -   loss: 0.4662770001645643
09/19/2019 20:32:07 - INFO - farm.eval -   task_name: text_classification
09/19/2019 20:32:07 - INFO - farm.eval -   f1_macro: 0.7745135759041442
09/19/2019 20:32:07 - INFO - farm.eval -   report: 
               precision    recall  f1-score   support

       Claim     0.0000    0.0000    0.0000         0
     Premise     0.0000    0.0000    0.0000         0

   micro avg     0.0000    0.0000    0.0000         0
   macro avg     0.0000    0.0000    0.0000         0
weighted avg     0.0000    0.0000    0.0000         0
```

**Comment by Timoeller** [comment]
Coding late?
Good that I could help.

About the new classification report issue: actually [this commit](https://github.com/deepset-ai/FARM/commit/f6734cb88cb29a872cbe6dcc2ba7cbf81855cd50) from yesterday should have fixed that particular problem. Could you pull FARM again please?

**Comment by guggio** [comment]
I was about to go to bed, then I saw your answer and had to give it a try ;)

I just restarted my Colab, ran my model again and now the classification report looks fine. Thanks again for your help and great work! I am happy to share my results once I am finished :)
